# This is overrides values for F1R3FLY RNode Helm Chart for local (Minikube) env

shardConfig:
  # Configure a number of deployable nodes. Bootstrap will be 1th node (value can't be not 0)
  deployableReplicas: 1

  # Configure a number of read-only nodes excluding deployable nodes
  readOnlyReplicas: 1

image:
  repository: sjc.ocir.io/axd0qezqa9z3/f1r3fly-rust
  pullPolicy: IfNotPresent # Pull from OCIR on first use; override to `Never` when using a locally loaded image
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

resources:
  limits:
    cpu: 1
    memory: 512Mi

persistence:
  storageClassName: "standard"

imagePullSecrets: []