//! Finite, located spatial/modal resource checking for `Cost(Rho)`.
//!
//! The checker is the native reference implementation of the resource fragment
//! generated by applying OSLF to the cost-accounted calculus. Formulas observe
//! authenticated supply and either exact realized demand or a certified static
//! upper bound. Exact evidence can establish modal post-state claims; an upper
//! bound can establish sufficiency but cannot be promoted into evidence that a
//! particular interaction occurred.
//!
//! Spatial composition is separating over named authority surfaces. Each side
//! receives only its own per-surface observation, which makes independent purse
//! proofs compositional and prevents ambient or candidate-created authority from
//! funding a term. The finite maps make every check terminating and decidable.

use std::collections::BTreeSet;

use models::rhoapi::Par;
use thiserror::Error;

use super::authority::{ResourceMultiset, UnprovableDemand};
use super::delta_sigma::{self, SigKey};
use super::Sig;

/// The finite supply and demand facts visible to a formula checker.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ResourceObservation<K> {
    /// Supply authenticated in the pre-state from which execution begins.
    pub available: ResourceMultiset<K>,
    /// Exact realized demand or a conservative static upper bound.
    pub demand: DemandKnowledge<K>,
}

/// The evidence strength attached to a finite per-surface demand map.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DemandKnowledge<K> {
    /// A replay-authenticated map of interactions that actually occurred.
    Exact(ResourceMultiset<K>),
    /// A certified maximum that may exceed the interactions that occur.
    UpperBound(ResourceMultiset<K>),
}

/// A three-valued formula result that preserves uncertainty soundly.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Verdict {
    /// Available evidence proves the formula.
    Satisfied,
    /// Available evidence disproves the formula.
    Unsatisfied,
    /// A conservative bound cannot prove or disprove the formula.
    Indeterminate,
}

/// The finite located resource fragment of the OSLF formula language.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Formula<K> {
    /// Truth.
    True,
    /// Conjunction evaluated over one observation.
    All(Vec<Self>),
    /// Three-valued negation.
    Not(Box<Self>),
    /// Separating composition over disjoint surface footprints.
    Spatial(Box<Self>, Box<Self>),
    /// Restriction to one named authority surface.
    Located { surface: K, body: Box<Self> },
    /// A lower bound on authenticated supply at one surface.
    Available { surface: K, amount: u64 },
    /// A lower bound on exact or conservatively bounded demand.
    Required { surface: K, amount: u64 },
    /// The local funding inequality for one surface.
    Sufficient { surface: K },
    /// An exact graded interaction followed by a post-state formula.
    Spend {
        grade: ResourceMultiset<K>,
        continuation: Box<Self>,
    },
}

/// The paper's opt-in token usage disciplines.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UsageDiscipline {
    /// Exactly one live use and a mandatory spend.
    Linear,
    /// Weakening and multiplicity are permitted.
    Copyable,
    /// Multiplicity is permitted but at least one spend is mandatory.
    Relevant,
}

/// A failed or unprovable native formula check.
#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum CheckError {
    #[error("the OSLF formula is not satisfied")]
    Unsatisfied,
    #[error("the OSLF formula requires exact demand evidence")]
    Indeterminate,
    #[error("the native rho demand is not statically provable: {0:?}")]
    Unprovable(UnprovableDemand),
}

impl<K: Ord + Clone> Formula<K> {
    /// Builds the exact-single-use spatial constraint plus modal spend.
    pub fn linear(surface: K) -> Self {
        Self::Located {
            surface: surface.clone(),
            body: Box::new(Self::All(vec![
                Self::Available {
                    surface: surface.clone(),
                    amount: 1,
                },
                Self::Required {
                    surface: surface.clone(),
                    amount: 1,
                },
                Self::Not(Box::new(Self::Required {
                    surface: surface.clone(),
                    amount: 2,
                })),
                Self::Spend {
                    grade: ResourceMultiset::singleton(surface, 1),
                    continuation: Box::new(Self::True),
                },
            ])),
        }
    }

    /// Builds the discipline that permits both weakening and multiplicity.
    pub fn copyable(surface: K) -> Self {
        Self::Located {
            surface,
            body: Box::new(Self::True),
        }
    }

    /// Builds the discipline that permits multiplicity but requires a spend.
    pub fn relevant(surface: K) -> Self {
        Self::Located {
            surface: surface.clone(),
            body: Box::new(Self::Spend {
                grade: ResourceMultiset::singleton(surface, 1),
                continuation: Box::new(Self::True),
            }),
        }
    }

    /// Builds the formula corresponding to an asserted usage discipline.
    pub fn discipline(surface: K, discipline: UsageDiscipline) -> Self {
        match discipline {
            UsageDiscipline::Linear => Self::linear(surface),
            UsageDiscipline::Copyable => Self::copyable(surface),
            UsageDiscipline::Relevant => Self::relevant(surface),
        }
    }

    fn surfaces(&self, out: &mut BTreeSet<K>) {
        match self {
            Self::True => {}
            Self::All(formulas) => {
                for formula in formulas {
                    formula.surfaces(out);
                }
            }
            Self::Not(formula) => formula.surfaces(out),
            Self::Spatial(left, right) => {
                left.surfaces(out);
                right.surfaces(out);
            }
            Self::Located { surface, body } => {
                out.insert(surface.clone());
                body.surfaces(out);
            }
            Self::Available { surface, .. } => {
                out.insert(surface.clone());
            }
            Self::Required { surface, .. } | Self::Sufficient { surface } => {
                out.insert(surface.clone());
            }
            Self::Spend {
                grade,
                continuation,
            } => {
                out.extend(grade.0.keys().cloned());
                continuation.surfaces(out);
            }
        }
    }
}

impl<K: Ord + Clone> ResourceObservation<K> {
    /// Constructs an observation backed by exact realized demand.
    pub fn exact(available: ResourceMultiset<K>, demand: ResourceMultiset<K>) -> Self {
        Self {
            available,
            demand: DemandKnowledge::Exact(demand),
        }
    }

    /// Constructs an observation backed by a conservative demand bound.
    pub fn upper_bound(available: ResourceMultiset<K>, demand: ResourceMultiset<K>) -> Self {
        Self {
            available,
            demand: DemandKnowledge::UpperBound(demand),
        }
    }

    fn restricted(&self, surfaces: &BTreeSet<K>) -> Self {
        let restrict = |resources: &ResourceMultiset<K>| {
            ResourceMultiset(
                resources
                    .0
                    .iter()
                    .filter(|(key, _)| surfaces.contains(*key))
                    .map(|(key, amount)| (key.clone(), *amount))
                    .collect(),
            )
        };
        Self {
            available: restrict(&self.available),
            demand: match &self.demand {
                DemandKnowledge::Exact(demand) => DemandKnowledge::Exact(restrict(demand)),
                DemandKnowledge::UpperBound(demand) => {
                    DemandKnowledge::UpperBound(restrict(demand))
                }
            },
        }
    }

    fn after_spend(&self, grade: &ResourceMultiset<K>) -> Option<Self> {
        let DemandKnowledge::Exact(demand) = &self.demand else {
            return None;
        };
        Some(Self::exact(
            self.available.checked_sub(grade).ok()?,
            demand.checked_sub(grade).ok()?,
        ))
    }
}

/// Evaluates a formula without collapsing conservative uncertainty into truth.
pub fn evaluate<K: Ord + Clone>(
    observation: &ResourceObservation<K>,
    formula: &Formula<K>,
) -> Verdict {
    match formula {
        Formula::True => Verdict::Satisfied,
        Formula::All(formulas) => {
            let mut verdict = Verdict::Satisfied;
            for formula in formulas {
                match evaluate(observation, formula) {
                    Verdict::Unsatisfied => return Verdict::Unsatisfied,
                    Verdict::Indeterminate => verdict = Verdict::Indeterminate,
                    Verdict::Satisfied => {}
                }
            }
            verdict
        }
        Formula::Not(formula) => match evaluate(observation, formula) {
            Verdict::Satisfied => Verdict::Unsatisfied,
            Verdict::Unsatisfied => Verdict::Satisfied,
            Verdict::Indeterminate => Verdict::Indeterminate,
        },
        Formula::Spatial(left, right) => {
            let mut left_surfaces = BTreeSet::new();
            let mut right_surfaces = BTreeSet::new();
            left.surfaces(&mut left_surfaces);
            right.surfaces(&mut right_surfaces);
            if !left_surfaces.is_disjoint(&right_surfaces) {
                Verdict::Unsatisfied
            } else {
                evaluate(&observation.restricted(&left_surfaces), left)
                    .and(evaluate(&observation.restricted(&right_surfaces), right))
            }
        }
        Formula::Located { surface, body } => {
            let mut body_surfaces = BTreeSet::new();
            body.surfaces(&mut body_surfaces);
            if body_surfaces.iter().any(|candidate| candidate != surface) {
                Verdict::Unsatisfied
            } else {
                evaluate(
                    &observation.restricted(&BTreeSet::from([surface.clone()])),
                    body,
                )
            }
        }
        Formula::Available { surface, amount } => {
            Verdict::from_bool(observation.available.get(surface) >= *amount)
        }
        Formula::Required { amount: 0, .. } => Verdict::Satisfied,
        Formula::Required { surface, amount } => match &observation.demand {
            DemandKnowledge::Exact(demand) => Verdict::from_bool(demand.get(surface) >= *amount),
            DemandKnowledge::UpperBound(demand) if demand.get(surface) < *amount => {
                Verdict::Unsatisfied
            }
            DemandKnowledge::UpperBound(_) => Verdict::Indeterminate,
        },
        Formula::Sufficient { surface } => {
            let demand = match &observation.demand {
                DemandKnowledge::Exact(demand) | DemandKnowledge::UpperBound(demand) => demand,
            };
            Verdict::from_bool(observation.available.get(surface) >= demand.get(surface))
        }
        Formula::Spend {
            grade,
            continuation,
        } if grade.0.is_empty() => Verdict::Unsatisfied,
        Formula::Spend {
            grade,
            continuation,
        } if !observation.available.dominates(grade) => Verdict::Unsatisfied,
        Formula::Spend {
            grade,
            continuation,
        } => match &observation.demand {
            DemandKnowledge::UpperBound(demand) if !demand.dominates(grade) => Verdict::Unsatisfied,
            DemandKnowledge::UpperBound(_) => Verdict::Indeterminate,
            DemandKnowledge::Exact(demand) if !demand.dominates(grade) => Verdict::Unsatisfied,
            DemandKnowledge::Exact(_) => observation
                .after_spend(grade)
                .map_or(Verdict::Unsatisfied, |next| evaluate(&next, continuation)),
        },
    }
}

impl Verdict {
    fn from_bool(value: bool) -> Self {
        if value {
            Self::Satisfied
        } else {
            Self::Unsatisfied
        }
    }

    fn and(self, other: Self) -> Self {
        match (self, other) {
            (Self::Unsatisfied, _) | (_, Self::Unsatisfied) => Self::Unsatisfied,
            (Self::Indeterminate, _) | (_, Self::Indeterminate) => Self::Indeterminate,
            (Self::Satisfied, Self::Satisfied) => Self::Satisfied,
        }
    }
}

/// Returns whether the observation proves the formula.
pub fn satisfies<K: Ord + Clone>(
    observation: &ResourceObservation<K>,
    formula: &Formula<K>,
) -> bool {
    evaluate(observation, formula) == Verdict::Satisfied
}

/// Checks a formula and preserves the distinction between false and unprovable.
pub fn check<K: Ord + Clone>(
    observation: &ResourceObservation<K>,
    formula: &Formula<K>,
) -> Result<(), CheckError> {
    match evaluate(observation, formula) {
        Verdict::Satisfied => Ok(()),
        Verdict::Unsatisfied => Err(CheckError::Unsatisfied),
        Verdict::Indeterminate => Err(CheckError::Indeterminate),
    }
}

/// Builds the admission-time Rho observation from authenticated pre-state supply.
///
/// The candidate program's newly created stacks are excluded from `available`.
/// The static analyzer supplies a conservative external reservation, so modal
/// claims remain indeterminate until exact replay evidence exists.
pub fn rho_observation(
    canonical: &Par,
    deploy_sig: &Sig,
    authenticated_supply: &ResourceMultiset<SigKey>,
) -> Result<ResourceObservation<SigKey>, CheckError> {
    let plan = delta_sigma::static_authority_plan(canonical, deploy_sig)
        .map_err(CheckError::Unprovable)?;
    Ok(ResourceObservation::upper_bound(
        authenticated_supply.clone(),
        plan.external_reservation,
    ))
}

/// Checks a native Rho program against an admission-time resource formula.
pub fn check_rho(
    canonical: &Par,
    deploy_sig: &Sig,
    authenticated_supply: &ResourceMultiset<SigKey>,
    formula: &Formula<SigKey>,
) -> Result<(), CheckError> {
    check(
        &rho_observation(canonical, deploy_sig, authenticated_supply)?,
        formula,
    )
}

#[cfg(test)]
mod tests {
    use proptest::prelude::*;

    use super::*;
    use crate::rust::interpreter::accounting::authority::cost_signature_to_sig;
    use crate::rust::interpreter::compiler::compiler::Compiler;

    fn key(byte: u8) -> SigKey { [byte; 32] }

    fn observation(entries: &[(SigKey, u64, u64)]) -> ResourceObservation<SigKey> {
        let mut available = ResourceMultiset::default();
        let mut required = ResourceMultiset::default();
        for (surface, supply, demand) in entries {
            if *supply != 0 {
                available.0.insert(*surface, *supply);
            }
            if *demand != 0 {
                required.0.insert(*surface, *demand);
            }
        }
        ResourceObservation::exact(available, required)
    }

    #[test]
    fn linear_usage_requires_one_available_copy_and_one_spend() {
        let surface = key(1);
        let formula = Formula::linear(surface);
        assert!(satisfies(&observation(&[(surface, 1, 1)]), &formula));
        assert!(satisfies(&observation(&[(surface, 2, 1)]), &formula));
        assert!(!satisfies(&observation(&[(surface, 1, 2)]), &formula));
        assert!(!satisfies(&observation(&[(surface, 1, 0)]), &formula));
        assert!(!satisfies(&observation(&[(surface, 0, 1)]), &formula));
    }

    #[test]
    fn copyable_and_relevant_usage_have_distinct_weakening_rules() {
        let surface = key(2);
        let copyable = Formula::copyable(surface);
        let relevant = Formula::relevant(surface);
        let absent = observation(&[]);
        let unused_copies = observation(&[(surface, 8, 0)]);
        let used_copies = observation(&[(surface, 8, 3)]);
        assert!(satisfies(&absent, &copyable));
        assert!(satisfies(&unused_copies, &copyable));
        assert!(!satisfies(&unused_copies, &relevant));
        assert!(satisfies(&used_copies, &copyable));
        assert!(satisfies(&used_copies, &relevant));
    }

    #[test]
    fn modal_continuation_observes_the_exact_post_spend_state() {
        let surface = key(3);
        let formula = Formula::Spend {
            grade: ResourceMultiset::singleton(surface, 1),
            continuation: Box::new(Formula::Not(Box::new(Formula::Available {
                surface,
                amount: 1,
            }))),
        };
        assert!(satisfies(&observation(&[(surface, 1, 1)]), &formula));
        assert!(!satisfies(&observation(&[(surface, 2, 1)]), &formula));
    }

    #[test]
    fn spatial_composition_requires_disjoint_locations() {
        let left = key(4);
        let right = key(5);
        let state = observation(&[(left, 1, 1), (right, 4, 2)]);
        assert!(satisfies(
            &state,
            &Formula::Spatial(
                Box::new(Formula::linear(left)),
                Box::new(Formula::relevant(right)),
            ),
        ));
        assert!(!satisfies(
            &state,
            &Formula::Spatial(
                Box::new(Formula::copyable(left)),
                Box::new(Formula::relevant(left)),
            ),
        ));
        assert!(satisfies(
            &state,
            &Formula::All(vec![Formula::copyable(left), Formula::relevant(left),]),
        ));
    }

    #[test]
    fn located_formula_cannot_observe_an_unrelated_surface() {
        let here = key(6);
        let there = key(7);
        let formula = Formula::Located {
            surface: here,
            body: Box::new(Formula::Available {
                surface: there,
                amount: 1,
            }),
        };
        assert!(!satisfies(
            &observation(&[(here, 1, 0), (there, 1, 0)]),
            &formula,
        ));
    }

    #[test]
    fn rho_reference_checker_uses_native_structural_demand() {
        let canonical = Compiler::source_to_adt(r#"{% @"x"!(0) %}[ a ]"#).unwrap();
        let signature =
            cost_signature_to_sig(canonical.cost_signed_terms[0].signature.as_ref().unwrap())
                .unwrap();
        let surface = signature.lane_hash();
        let authenticated_supply = ResourceMultiset::singleton(surface, 1);
        check_rho(
            &canonical,
            &signature,
            &authenticated_supply,
            &Formula::Located {
                surface,
                body: Box::new(Formula::Sufficient { surface }),
            },
        )
        .unwrap();
    }

    #[test]
    fn structural_upper_bound_cannot_prove_a_modal_spend() {
        let surface = key(10);
        let state = ResourceObservation::upper_bound(
            ResourceMultiset::singleton(surface, 1),
            ResourceMultiset::singleton(surface, 1),
        );
        assert_eq!(
            evaluate(&state, &Formula::relevant(surface)),
            Verdict::Indeterminate,
        );
        assert_eq!(
            check(&state, &Formula::relevant(surface)),
            Err(CheckError::Indeterminate),
        );
        let unfunded = ResourceObservation::upper_bound(
            ResourceMultiset::default(),
            ResourceMultiset::singleton(surface, 1),
        );
        assert_eq!(
            evaluate(&unfunded, &Formula::relevant(surface)),
            Verdict::Unsatisfied,
        );
    }

    #[test]
    fn conservative_upper_bound_can_prove_sufficiency_but_not_positive_demand() {
        let surface = key(11);
        let state = ResourceObservation::upper_bound(
            ResourceMultiset::singleton(surface, 3),
            ResourceMultiset::singleton(surface, 2),
        );
        assert_eq!(
            evaluate(&state, &Formula::Sufficient { surface }),
            Verdict::Satisfied,
        );
        assert_eq!(
            evaluate(&state, &Formula::Required { surface, amount: 1 }),
            Verdict::Indeterminate,
        );
        assert_eq!(
            evaluate(&state, &Formula::Required { surface, amount: 3 }),
            Verdict::Unsatisfied,
        );
    }

    #[test]
    fn zero_requirement_is_proved_for_exact_and_bounded_observations() {
        let surface = key(12);
        let exact =
            ResourceObservation::exact(ResourceMultiset::default(), ResourceMultiset::default());
        let bounded = ResourceObservation::upper_bound(
            ResourceMultiset::default(),
            ResourceMultiset::singleton(surface, 7),
        );
        let formula = Formula::Required { surface, amount: 0 };
        assert!(satisfies(&exact, &formula));
        assert!(satisfies(&bounded, &formula));
    }

    #[test]
    fn empty_modal_grade_cannot_witness_an_interaction() {
        let state = ResourceObservation::<SigKey>::exact(
            ResourceMultiset::default(),
            ResourceMultiset::default(),
        );
        assert_eq!(
            evaluate(&state, &Formula::Spend {
                grade: ResourceMultiset::default(),
                continuation: Box::new(Formula::True),
            }),
            Verdict::Unsatisfied,
        );
    }

    #[test]
    fn candidate_created_stack_does_not_fund_its_own_transfer() {
        let canonical = Compiler::source_to_adt("a :: ()").unwrap();
        let signature = Sig::Ground(b"deploy".to_vec());
        let deploy_surface = signature.lane_hash();
        let observation =
            rho_observation(&canonical, &signature, &ResourceMultiset::default()).unwrap();
        assert_eq!(
            evaluate(&observation, &Formula::Located {
                surface: deploy_surface,
                body: Box::new(Formula::Sufficient {
                    surface: deploy_surface,
                }),
            },),
            Verdict::Unsatisfied,
        );
    }

    proptest! {
        #[test]
        fn disjoint_local_spends_compose_for_arbitrary_supply(
            left_supply in 1_u64..=u32::MAX as u64,
            right_supply in 1_u64..=u32::MAX as u64,
            left_demand in 1_u64..=u32::MAX as u64,
            right_demand in 1_u64..=u32::MAX as u64,
        ) {
            let left = key(8);
            let right = key(9);
            let state = observation(&[
                (left, left_supply, left_demand),
                (right, right_supply, right_demand),
            ]);
            let formula = Formula::Spatial(
                Box::new(Formula::relevant(left)),
                Box::new(Formula::relevant(right)),
            );
            prop_assert_eq!(satisfies(&state, &formula), true);
            let swapped = Formula::Spatial(
                Box::new(Formula::relevant(right)),
                Box::new(Formula::relevant(left)),
            );
            prop_assert_eq!(satisfies(&state, &formula), satisfies(&state, &swapped));
        }
    }
}
