[package]
name = "cordial-rholang"
version = "0.1.0"
edition = "2024"

[dependencies]
cordial-consensus = { path = "../cordial-consensus" }
casper = { path = "../../casper" }
models = { path = "../../models" }
crypto = { path = "../../crypto" }
rholang = { path = "../../rholang" }
rspace_plus_plus = { path = "../../rspace++" }
prost.workspace = true
k256.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
hex.workspace = true
tokio.workspace = true

[dev-dependencies]
consensus-api = { path = "../../consensus-api" }
consensus-runtime = { path = "../../consensus-runtime" }
tempfile.workspace = true
tokio.workspace = true
hex.workspace = true
