//! # The GROUP BOMB — the falsifying test for the unknown-field skipper
//!
//! `models/src/rust/rholang/mod.rs`'s `protobuf_decoder` module (generated by
//! `models/codegen/schema_codegen.rs` §8) carries one function,
//! `skip_unknown_field`. It is an iterative re-implementation of
//! `prost::encoding::skip_field` (`prost-0.14.3/src/encoding.rs:166-199`),
//! whose `StartGroup` arm at `:187` self-recurses once per nesting level.
//!
//! ## Why wire type 3 is an ATTACKER'S choice
//!
//! proto3 has no group syntax, so no `rhoapi` message can legitimately carry
//! `StartGroup`. That constrains what this node WRITES. It says nothing about
//! what it READS: skipping an *unknown* field is a walk over bytes a peer sent,
//! and the peer decides how many `StartGroup` keys to send. The unknown-field
//! path is therefore a recursive descent whose depth is chosen entirely by the
//! sender and bounded by nothing in the schema — a separate hazard from the
//! known-field walk, reachable on a message whose known fields are trivial.
//!
//! ## The three subjects, and what each shows
//!
//! | subject | on the bomb | what it demonstrates |
//! |---|---|---|
//! | `prost::encoding::skip_field`, stock | `Err(RecursionLimitReached)` | the ARTIFICIAL LIMIT: it refuses input that is perfectly well-formed protobuf |
//! | the same body with the budget removed | **killed by a signal** | why the limit cannot simply be deleted: the recursion is the hazard |
//! | `skip_unknown_field` | `Ok(())` / a clean `Err` | the limit is unnecessary once the recursion is gone |
//!
//! ⚠★ **The middle row is the RED, and it is NOT stock prost.** The `prost`
//! this workspace builds does **not** enable `no-recursion-limit` (verified:
//! the feature appears in no `Cargo.toml` in the tree), so
//! `prost::RECURSION_LIMIT` is 100 and stock `skip_field` returns a clean
//! `Err(RecursionLimitReached)` at depth 100 rather than overflowing. Stock
//! prost is SAFE, and safe *precisely because that limit exists*. The
//! transcription in §C is what the workspace's standing "artificial limits are
//! removed outright" ruling produces when applied to prost's body **without**
//! first removing the recursion — and it is included because that is the
//! failure the iterative rewrite exists to make impossible, and because a
//! hazard nobody has ever SEEN fire is indistinguishable from no hazard.
//!
//! ## ⚠ Why child processes, and never `#[should_panic]`
//!
//! `models/src/rust/rholang/drive.rs:196-199` states the workspace rule: a
//! negative subject runs in a **child process** and the parent reads the
//! child's **exit status** and output, because *"an abort is not catchable and
//! a panic that fails to unwind prints nothing"* — and a stack overflow is a
//! `SIGSEGV` that no `catch_unwind` can observe at all. Every arm here follows
//! `models/tests/drive_configuration_gate.rs`'s shape.
//!
//! ## ★ The control that makes "prost rejects it" mean anything
//!
//! A deep nest that prost refuses could be refused because it is *malformed*
//! rather than because it is *deep*. So §D builds the identical construction at
//! depth 50 — under prost's limit of 100 — and requires **both** implementations
//! to accept it and to leave the buffer in the same place. The bomb is then the
//! same construction scaled, and the only thing that changed is the depth.

use std::os::unix::process::ExitStatusExt as _;
use std::process::{Command, Stdio};

use models::rust::rholang::protobuf_decoder::skip_unknown_field;
use prost::bytes::Buf;
use prost::encoding::{skip_field, DecodeContext, WireType};
use prost::DecodeError;

// ===========================================================================
// §A  The bytes
// ===========================================================================

/// The tag every group in the bomb uses. Any tag `>= MIN_TAG` would do; one
/// fixed tag keeps every key a single byte, so `|input|` and the nesting depth
/// are the same number and the space argument needs no arithmetic.
const BOMB_TAG: u32 = 1;

/// `key(tag, StartGroup)` for [`BOMB_TAG`]: `(1 << 3) | 3 == 0x0B`.
const START: u8 = ((BOMB_TAG << 3) | 3) as u8;

/// `key(tag, EndGroup)` for [`BOMB_TAG`]: `(1 << 3) | 4 == 0x0C`.
const END: u8 = ((BOMB_TAG << 3) | 4) as u8;

/// The bomb's size, in bytes. "~1 MiB of nested `StartGroup` keys."
const BOMB_BYTES: usize = 1 << 20;

/// UNTERMINATED: `BOMB_BYTES` `StartGroup` keys and no `EndGroup` at all.
///
/// The field the call is ENTERED on is a `StartGroup` too, so the nesting depth
/// is `BOMB_BYTES + 1`. Valid protobuf as far as it goes, and then it stops:
/// the correct answer is an error about the truncation, at whatever depth the
/// implementation reaches.
fn unterminated_bomb() -> Vec<u8> { vec![START; BOMB_BYTES] }

/// TERMINATED: a WELL-FORMED nest, `depth` levels deep, fully closed.
///
/// Entered on `(StartGroup, BOMB_TAG)`, so the buffer holds `depth - 1` further
/// `StartGroup` keys and then `depth` `EndGroup` keys. Every group closes with
/// the tag that opened it, and the buffer ends exactly when the outermost group
/// does. There is no defect in these bytes at any depth — which is the point.
fn terminated_nest(depth: usize) -> Vec<u8> {
    assert!(depth >= 1, "a nest needs at least the entered level");
    let mut bytes = Vec::with_capacity(2 * depth - 1);
    bytes.extend(std::iter::repeat(START).take(depth - 1));
    bytes.extend(std::iter::repeat(END).take(depth));
    bytes
}

/// The terminated bomb's depth, chosen so the whole buffer is ~1 MiB
/// (`2 * depth - 1` bytes).
const TERMINATED_DEPTH: usize = BOMB_BYTES / 2;

/// A depth comfortably UNDER `prost::RECURSION_LIMIT` (100), so both
/// implementations can be required to accept the same construction. See §D.
const SHALLOW_DEPTH: usize = 50;

// ===========================================================================
// §B  What the two implementations are asked
// ===========================================================================

/// Run `skip_unknown_field` on `(protobuf_wire_type, tag, bytes)`.
///
/// Returns the result and how many bytes were LEFT, so the two implementations
/// can be compared on buffer position as well as on outcome — an implementation
/// that returned the right error from the wrong offset would satisfy an
/// outcome-only comparison and then mis-decode the next field.
fn run_iterative(
    protobuf_wire_type: WireType,
    tag: u32,
    bytes: &[u8],
) -> (Result<(), DecodeError>, usize) {
    let mut buf: &[u8] = bytes;
    let result = skip_unknown_field(protobuf_wire_type, tag, &mut buf);
    (result, buf.remaining())
}

/// Run stock `prost::encoding::skip_field` on the same input, with the default
/// `DecodeContext` — i.e. with `RECURSION_LIMIT` at its shipped value of 100.
fn run_protobuf(
    protobuf_wire_type: WireType,
    tag: u32,
    bytes: &[u8],
) -> (Result<(), DecodeError>, usize) {
    let mut buf: &[u8] = bytes;
    let result = skip_field(protobuf_wire_type, tag, &mut buf, DecodeContext::default());
    (result, buf.remaining())
}

// ===========================================================================
// §C  ★★ The transcription: prost's body with the budget removed
// ===========================================================================
//
// A VERBATIM copy of `prost-0.14.3/src/encoding.rs:166-199` with exactly one
// edit — the `ctx: DecodeContext` parameter, the `ctx.limit_reached()?` at
// `:172` and the `ctx.enter_recursion()` argument at `:187` are gone. Nothing
// else is changed: the same `match`, the same arms, the same `len` arithmetic,
// the same `UnexpectedEndGroupTag` and `BufferUnderflow` conditions.
//
// ⚠ It is a TEST SUBJECT and nothing else. It is not exported, nothing in
// `models/src` calls it, and it exists for the same reason
// `drive_configuration_gate.rs` grows its own malformed visitors: the campaign
// is removing artificial limits, and this is the measurement of what removing
// THIS one costs if the recursion underneath it is left in place.
//
// The prost errors it cannot construct (`DecodeErrorKind` is `pub(crate)`) are
// irrelevant here — the arms that would produce them are unreachable on the
// bomb, so they are left as a panic that names itself. The subject is the
// STACK, not the error values; §E is where the error values are compared.

/// See the section header. `#[inline(never)]` so that no optimisation level can
/// flatten the frames the subject is about.
#[inline(never)]
fn recursion_without_the_budget(
    protobuf_wire_type: WireType,
    tag: u32,
    buf: &mut impl Buf,
) -> Result<(), &'static str> {
    let len = match protobuf_wire_type {
        WireType::Varint => prost::encoding::decode_varint(buf)
            .map(|_| 0)
            .map_err(|_| "varint")?,
        WireType::ThirtyTwoBit => 4,
        WireType::SixtyFourBit => 8,
        WireType::LengthDelimited => {
            prost::encoding::decode_varint(buf).map_err(|_| "length delimiter")?
        }
        WireType::StartGroup => loop {
            let (inner_tag, inner_wire_type) =
                prost::encoding::decode_key(buf).map_err(|_| "key")?;
            match inner_wire_type {
                WireType::EndGroup => {
                    if inner_tag != tag {
                        return Err("unexpected end group tag");
                    }
                    break 0;
                }
                // ⚠ THE RECURSION, at `encoding.rs:187`, with the budget gone.
                _ => recursion_without_the_budget(inner_wire_type, inner_tag, buf)?,
            }
        },
        WireType::EndGroup => return Err("unexpected end group tag"),
    };

    if len > buf.remaining() as u64 {
        return Err("buffer underflow");
    }
    buf.advance(len as usize);
    Ok(())
}

// ===========================================================================
// §D  The child harness
// ===========================================================================

const BOMB_ARM: &str = "GROUP_BOMB_ARM";

/// The child entry point's full test path, as libtest's `--exact` wants it.
const CHILD: &str = "bomb_child";

/// Printed by a child that ran its subject to completion, so the parent can
/// tell "the subject returned" from "the subject never ran".
const OK_MARKER: &str = "GROUP_BOMB_OK";

fn run_arm(arm: &str) {
    let report = match arm {
        // ── the ITERATIVE subject ──
        "iterative_unterminated" => {
            let bytes = unterminated_bomb();
            let (result, left) = run_iterative(WireType::StartGroup, BOMB_TAG, &bytes);
            format!("outcome={result:?} left={left}")
        }
        "iterative_terminated" => {
            let bytes = terminated_nest(TERMINATED_DEPTH);
            let (result, left) = run_iterative(WireType::StartGroup, BOMB_TAG, &bytes);
            format!("outcome={result:?} left={left}")
        }
        // ── STOCK prost, recursion-limited ──
        "protobuf_unterminated" => {
            let bytes = unterminated_bomb();
            let (result, left) = run_protobuf(WireType::StartGroup, BOMB_TAG, &bytes);
            format!("outcome={result:?} left={left}")
        }
        "protobuf_terminated" => {
            let bytes = terminated_nest(TERMINATED_DEPTH);
            let (result, left) = run_protobuf(WireType::StartGroup, BOMB_TAG, &bytes);
            format!("outcome={result:?} left={left}")
        }
        // ── ★ prost's BODY with the budget removed ──
        "unbudgeted_recursion_terminated" => {
            let bytes = terminated_nest(TERMINATED_DEPTH);
            let mut buf: &[u8] = &bytes;
            let result = recursion_without_the_budget(WireType::StartGroup, BOMB_TAG, &mut buf);
            format!("outcome={result:?} left={}", buf.remaining())
        }
        other => panic!("protobuf_decoder_group_bomb: unknown {BOMB_ARM}={other:?}"),
    };
    println!("{OK_MARKER} arm={arm} {report}");
}

/// The child entry point.
///
/// ⚠ A NO-OP when its environment is absent, because `cargo test --
/// --include-ignored` executes every `#[ignore]`d test and a child that
/// REQUIRED its environment would fail the suite for a reason unrelated to the
/// property. Same rationale as `drive_configuration_gate.rs`'s `gate_child`.
#[test]
#[ignore = "child process of the group-bomb gate; driven via GROUP_BOMB_ARM"]
fn bomb_child() {
    let Ok(arm) = std::env::var(BOMB_ARM) else {
        println!("bomb_child: no {BOMB_ARM} — not a child invocation, nothing to do");
        return;
    };
    run_arm(&arm);
}

/// What a child invocation produced.
struct Child {
    /// Exited 0.
    ok: bool,
    /// `Some(code)` for a normal exit; `None` when the child was KILLED BY A
    /// SIGNAL, which is the only way a stack overflow can be observed.
    code: Option<i32>,
    /// The terminating signal, when there was one. 11 (`SIGSEGV`) when the
    /// guard page is hit with no handler installed, 6 (`SIGABRT`) when Rust's
    /// overflow handler runs and aborts.
    signal: Option<i32>,
    output: String,
}

impl Child {
    /// A one-line, quotable statement of how the child ended.
    fn status(&self) -> String {
        match (self.code, self.signal) {
            (Some(code), _) => format!("exited with code {code}"),
            (None, Some(sig)) => format!("KILLED BY SIGNAL {sig}"),
            (None, None) => "ended without a code or a signal".to_string(),
        }
    }
}

fn run_child(arm: &str) -> Child {
    let exe = std::env::current_exe().expect("protobuf_decoder_group_bomb: current_exe");
    let out = Command::new(exe)
        // `--nocapture` so the child's own stderr (including the stack-overflow
        // banner, which libtest never sees) reaches the parent verbatim.
        .args(["--ignored", "--exact", CHILD, "--nocapture"])
        .env(BOMB_ARM, arm)
        .stdin(Stdio::null())
        .output()
        .expect("protobuf_decoder_group_bomb: failed to run the child");
    let mut output = String::from_utf8_lossy(&out.stdout).into_owned();
    output.push_str(&String::from_utf8_lossy(&out.stderr));
    Child {
        ok: out.status.success(),
        code: out.status.code(),
        signal: out.status.signal(),
        output,
    }
}

/// Pull the `outcome=` field out of a completed child's marker line.
///
/// Taken from the marker to the end of line, because a `Debug`-formatted
/// `DecodeError` contains spaces.
fn outcome(child: &Child) -> String {
    child
        .output
        .lines()
        .find_map(|line| {
            line.split_once("outcome=")
                .map(|(_, rest)| rest.to_string())
        })
        .unwrap_or_else(|| {
            panic!(
                "no `outcome=` in the child's output — it did not reach the end of its \
                 subject:\n{}",
                child.output
            )
        })
}

// ===========================================================================
// §E  ★★★ THE CONTROL — the construction is valid protobuf
// ===========================================================================

/// ★★★ Every claim below about "prost rejects a well-formed nest" is vacuous
/// until this passes.
///
/// The identical construction, at a depth prost's budget allows, must be
/// ACCEPTED by both implementations, with the buffer fully consumed by both.
/// Without this, `Err(RecursionLimitReached)` on the bomb would be
/// indistinguishable from `Err(<the bytes are junk>)`.
#[test]
fn the_nest_construction_is_valid_protobuf_at_a_depth_protobuf_accepts() {
    let bytes = terminated_nest(SHALLOW_DEPTH);
    let (protobuf_result, protobuf_left) = run_protobuf(WireType::StartGroup, BOMB_TAG, &bytes);
    let (mine_result, mine_left) = run_iterative(WireType::StartGroup, BOMB_TAG, &bytes);

    assert!(
        protobuf_result.is_ok(),
        "★ CONTROL FAILED: stock `prost::encoding::skip_field` REJECTED a {SHALLOW_DEPTH}-deep \
         terminated nest, which is under its recursion limit of 100. The bytes this file \
         builds are then not well-formed protobuf, and every 'prost refuses valid input' \
         claim below is measuring a defect in the FIXTURE. Got {protobuf_result:?}."
    );
    assert!(
        mine_result.is_ok(),
        "★ CONTROL FAILED: `skip_unknown_field` rejected a {SHALLOW_DEPTH}-deep terminated \
         nest that prost accepts. Got {mine_result:?}."
    );
    assert_eq!(
        (protobuf_left, mine_left),
        (0, 0),
        "a terminated nest ends exactly when its outermost group does, so both \
         implementations must consume the WHOLE buffer. prost left {protobuf_left} byte(s), \
         `skip_unknown_field` left {mine_left}."
    );
}

// ===========================================================================
// §F  ★★ THE GROUP BOMB
// ===========================================================================

/// ★★ **THE RED.** prost's recursive body, with the artificial limit removed
/// and nothing else changed, is KILLED BY A SIGNAL on the bomb.
///
/// This is the measurement that makes the iterative rewrite necessary rather
/// than merely tidy: the recursion at `encoding.rs:187` is what the limit was
/// holding back, so the limit cannot be removed on its own. The limit and the
/// recursion come out together, and in that order — never the reverse.
#[test]
fn protobuf_s_recursion_with_the_budget_removed_dies_on_the_bomb() {
    let child = run_child("unbudgeted_recursion_terminated");
    assert!(
        !child.ok,
        "★ THE BOMB DID NOT GO OFF. prost's recursive `skip_field` body, with its budget \
         removed, ran a {TERMINATED_DEPTH}-deep group nest to completion — so either the \
         recursion was optimised away (`#[inline(never)]` should prevent that) or the \
         fixture is not deep enough to reach the guard page. This test is the evidence \
         that the recursion, and not the budget, is the hazard; it has shown nothing.\n{}",
        child.output
    );
    assert!(
        child.code.is_none(),
        "the unbudgeted recursion FAILED, but by returning an exit code ({}) rather than \
         by being killed. A stack overflow is a signal — an ordinary failure here means \
         the child died of something that is not the subject.\n{}",
        child.status(),
        child.output
    );
    let signal = child
        .signal
        .expect("a child with no exit code was killed by a signal");
    assert!(
        signal == libc_sigsegv() || signal == libc_sigabrt(),
        "the unbudgeted recursion was killed by signal {signal}, which is neither SIGSEGV \
         ({}) nor SIGABRT ({}). A guard-page hit raises SIGSEGV; Rust's overflow handler \
         turns it into an abort. Another signal means the child died of something \
         else.\n{}",
        libc_sigsegv(),
        libc_sigabrt(),
        child.output
    );
    // Recorded, not asserted: the banner only appears when Rust's handler runs
    // before the abort, and requiring it would make this gate depend on a
    // runtime detail rather than on the observation that matters.
    println!(
        "RED (prost's recursion, budget removed): {} — stack-overflow banner {}",
        child.status(),
        if child.output.contains("has overflowed its stack") {
            "PRESENT"
        } else {
            "absent"
        }
    );
}

/// ★★ **THE GREEN, and the sharpest statement of the difference.** On the SAME
/// well-formed input, `skip_unknown_field` returns `Ok(())` where stock prost
/// returns `Err(RecursionLimitReached)`.
///
/// ⚠ Stock prost is not *unsafe* here — it is safe, and safe precisely because
/// the limit exists. What it is, is WRONG: it refuses a message that is valid
/// protobuf, at a depth a peer chose. That is the cost of the artificial limit,
/// and it is the cost this stage removes without paying the §F RED for it.
#[test]
fn the_iterative_skipper_accepts_the_bomb_that_protobuf_s_limit_refuses() {
    let mine = run_child("iterative_terminated");
    assert!(
        mine.ok,
        "★ `skip_unknown_field` did not survive a {TERMINATED_DEPTH}-deep terminated nest \
         ({}). Its stack use must be O(1) in the nesting depth.\n{}",
        mine.status(),
        mine.output
    );
    let mine_outcome = outcome(&mine);
    assert!(
        mine_outcome.starts_with("outcome=Ok(())") || mine_outcome.starts_with("Ok(())"),
        "`skip_unknown_field` survived the terminated bomb but did not ACCEPT it. The nest \
         is well-formed protobuf (§E proves the construction at depth {SHALLOW_DEPTH}), so \
         the answer is `Ok(())` and the buffer is empty. Got: {mine_outcome}"
    );
    assert!(
        mine_outcome.contains("left=0"),
        "`skip_unknown_field` accepted the terminated bomb without consuming it. A \
         terminated nest ends exactly when its outermost group does. Got: {mine_outcome}"
    );

    let theirs = run_child("protobuf_terminated");
    assert!(
        theirs.ok,
        "stock prost was expected to REFUSE the bomb cleanly, not to die on it ({}). It \
         still has its recursion limit — see this file's header.\n{}",
        theirs.status(),
        theirs.output
    );
    let their_outcome = outcome(&theirs);
    assert!(
        their_outcome.contains("recursion limit reached")
            || their_outcome.contains("RecursionLimitReached"),
        "★ stock prost did not refuse the {TERMINATED_DEPTH}-deep nest with its recursion \
         limit. This gate's whole framing is that prost is SAFE-BUT-WRONG here — safe \
         because the budget stops it, wrong because the input is valid. If prost now \
         accepts it, the budget has changed and §F's RED is measuring something else. \
         Got: {their_outcome}"
    );
    println!(
        "GREEN (skip_unknown_field): {} — {mine_outcome}\n\
         prost (stock, limited):     {} — {their_outcome}",
        mine.status(),
        theirs.status()
    );
}

/// The UNTERMINATED bomb: 1 MiB of `StartGroup` keys and no close.
///
/// `skip_unknown_field` must report the truncation rather than dying of it. It
/// pushes `BOMB_BYTES + 1` tags (4 MiB of heap) and then runs out of input, so
/// this is also the arm that shows the explicit stack is HEAP and that heap
/// exhaustion is the failure mode it trades the machine stack for.
#[test]
fn the_iterative_skipper_reports_an_unterminated_bomb_instead_of_dying_on_it() {
    let child = run_child("iterative_unterminated");
    assert!(
        child.ok,
        "★ `skip_unknown_field` did not survive {BOMB_BYTES} unterminated `StartGroup` \
         keys ({}).\n{}",
        child.status(),
        child.output
    );
    let got = outcome(&child);
    assert!(
        got.contains("Err("),
        "an unterminated group nest is truncated input and must be an ERROR. A skipper \
         that reported success would leave the caller decoding the next field from the \
         middle of nowhere. Got: {got}"
    );
    assert!(
        got.contains("left=0"),
        "the unterminated bomb was rejected without the whole buffer having been read — \
         the error is supposed to be the exhaustion itself. Got: {got}"
    );
    println!(
        "GREEN (unterminated, {BOMB_BYTES} B): {} — {got}",
        child.status()
    );
}

// ===========================================================================
// §G  ★★ EXACTNESS — the accept set, the reject set, and the ERROR VALUES
// ===========================================================================
//
// Every case here is under prost's recursion limit, so the budget cannot
// confound the comparison and the two implementations must agree EXACTLY:
// same `Result`, same `DecodeError` VALUE (`DecodeError: PartialEq`), and the
// same buffer position afterwards.
//
// ⚠ Comparing the VALUE and not the rendering is what the generated module's
// error minting exists for: `DecodeErrorKind` is `pub(crate)`, so an error
// written out by hand would be `Other { description }` and would differ here
// while still *printing* plausibly.

/// One differential case: a field key and the bytes that follow it.
struct Case {
    what: &'static str,
    protobuf_wire_type: WireType,
    tag: u32,
    bytes: Vec<u8>,
}

fn cases() -> Vec<Case> {
    let case = |what, protobuf_wire_type, tag, bytes: Vec<u8>| Case {
        what,
        protobuf_wire_type,
        tag,
        bytes,
    };
    vec![
        // ── the non-group arms, accepting ──
        case("varint, one byte", WireType::Varint, 1, vec![0x07]),
        case("varint, multi-byte", WireType::Varint, 1, vec![0x96, 0x01]),
        case("varint, trailing bytes left", WireType::Varint, 1, vec![
            0x07, 0xFF,
        ]),
        case("32-bit, exact", WireType::ThirtyTwoBit, 1, vec![1, 2, 3, 4]),
        case("64-bit, exact", WireType::SixtyFourBit, 1, vec![
            1, 2, 3, 4, 5, 6, 7, 8,
        ]),
        case(
            "length-delimited, exact",
            WireType::LengthDelimited,
            1,
            vec![3, 0xAA, 0xBB, 0xCC],
        ),
        case(
            "length-delimited, empty payload",
            WireType::LengthDelimited,
            1,
            vec![0],
        ),
        // ── the non-group arms, rejecting ──
        case("varint, empty buffer", WireType::Varint, 1, vec![]),
        case("varint, truncated continuation", WireType::Varint, 1, vec![
            0x80,
        ]),
        case("32-bit, one byte short", WireType::ThirtyTwoBit, 1, vec![
            1, 2, 3,
        ]),
        case("32-bit, empty buffer", WireType::ThirtyTwoBit, 1, vec![]),
        case("64-bit, one byte short", WireType::SixtyFourBit, 1, vec![
            1, 2, 3, 4, 5, 6, 7,
        ]),
        case(
            "length-delimited, payload past the end",
            WireType::LengthDelimited,
            1,
            vec![10, 1, 2],
        ),
        case(
            "length-delimited, no length",
            WireType::LengthDelimited,
            1,
            vec![],
        ),
        // ── EndGroup as the ENTERED field ──
        case("end-group at the top level", WireType::EndGroup, 1, vec![]),
        case(
            "end-group at the top level, bytes after",
            WireType::EndGroup,
            1,
            vec![1, 2, 3],
        ),
        // ── groups, accepting ──
        case("group, immediately closed", WireType::StartGroup, 1, vec![
            END,
        ]),
        case("group, one inner varint", WireType::StartGroup, 1, vec![
            0x28, 0x07, END,
        ]),
        case("group, nested twice", WireType::StartGroup, 1, vec![
            START, END, END,
        ]),
        case(
            "group, sibling groups inside",
            WireType::StartGroup,
            1,
            vec![START, END, START, END, END],
        ),
        case("group, mixed inner fields", WireType::StartGroup, 1, vec![
            0x28, 0x07, START, 0x2A, 0x02, 0xAA, 0xBB, END, END,
        ]),
        case(
            "group, bytes left after the close",
            WireType::StartGroup,
            1,
            vec![END, 0xFF, 0xFF],
        ),
        // ── groups, rejecting ──
        case("group, never closed", WireType::StartGroup, 1, vec![]),
        case("group, inner never closed", WireType::StartGroup, 1, vec![
            START, END,
        ]),
        // `key(2, EndGroup) == (2 << 3) | 4 == 0x14` closes tag 2, not tag 1.
        case(
            "group, closed with the wrong tag",
            WireType::StartGroup,
            1,
            vec![0x14],
        ),
        case(
            "group, inner closed with the wrong tag",
            WireType::StartGroup,
            1,
            vec![START, 0x14],
        ),
        case(
            "group, inner field runs past the end",
            WireType::StartGroup,
            1,
            vec![0x2A, 0x7F, 1, 2, END],
        ),
        // `(1 << 3) | 6 == 0x0E` — wire type 6 does not exist.
        case(
            "group, inner key has an invalid wire type",
            WireType::StartGroup,
            1,
            vec![0x0E],
        ),
        // `(0 << 3) | 4 == 0x04` — tag 0 is below `MIN_TAG`.
        case("group, inner key has tag 0", WireType::StartGroup, 1, vec![
            0x04,
        ]),
        // ── the shallow nests, both directions ──
        case(
            "terminated nest at a depth prost allows",
            WireType::StartGroup,
            BOMB_TAG,
            terminated_nest(SHALLOW_DEPTH),
        ),
        case(
            "unterminated nest at a depth prost allows",
            WireType::StartGroup,
            BOMB_TAG,
            vec![START; SHALLOW_DEPTH],
        ),
    ]
}

/// ★★ The exactness requirement, executed: identical outcome, identical
/// `DecodeError` value, identical buffer position, on every case.
#[test]
fn the_iterative_skipper_accepts_and_rejects_exactly_what_protobuf_does() {
    let cases = cases();
    assert!(
        cases.len() >= 30,
        "VACUOUS: the differential ran {} case(s). It must cover every arm of prost's \
         `match` in both directions.",
        cases.len()
    );

    let mut accepted = 0usize;
    let mut rejected = 0usize;
    for case in &cases {
        let (theirs, their_left) = run_protobuf(case.protobuf_wire_type, case.tag, &case.bytes);
        let (mine, my_left) = run_iterative(case.protobuf_wire_type, case.tag, &case.bytes);

        assert_eq!(
            mine.is_ok(),
            theirs.is_ok(),
            "★ ACCEPT-SET DIVERGENCE on {:?} ({:?}, tag {}, {:?}): prost said {:?} and \
             `skip_unknown_field` said {:?}. The two must accept and reject the same \
             inputs — a decoder that admits one byte string prost refuses is a consensus \
             fork.",
            case.what,
            case.protobuf_wire_type,
            case.tag,
            case.bytes,
            theirs,
            mine
        );
        assert_eq!(
            mine, theirs,
            "★ ERROR-VALUE DIVERGENCE on {:?}: prost produced {:?} and \
             `skip_unknown_field` produced {:?}. These are compared as VALUES, not as \
             renderings — `DecodeErrorKind` is `pub(crate)`, so an error written out by \
             hand rather than minted from prost would fail exactly here while still \
             printing plausibly.",
            case.what, theirs, mine
        );
        assert_eq!(
            my_left, their_left,
            "★ BUFFER-POSITION DIVERGENCE on {:?}: prost left {their_left} byte(s) and \
             `skip_unknown_field` left {my_left}. Skipping a field is defined by where it \
             leaves the cursor; the same answer from a different offset mis-decodes \
             everything after it.",
            case.what
        );

        if mine.is_ok() {
            accepted += 1;
        } else {
            rejected += 1;
        }
    }

    // ★ Both directions must be non-empty, or the differential is proving one
    // half of the contract and asserting the other vacuously.
    assert!(
        accepted >= 10 && rejected >= 10,
        "VACUOUS: {accepted} case(s) accepted and {rejected} rejected. A differential \
         that only ever exercises one side of the accept set cannot detect a skipper \
         that accepts everything, or one that accepts nothing."
    );
    println!(
        "exactness: {} case(s) — {accepted} accepted, {rejected} rejected, all identical \
         in outcome, error VALUE and buffer position",
        cases.len()
    );
}

/// ★ The two minted error values, checked against prost's in situ.
///
/// The generated module obtains `BufferUnderflow` and `UnexpectedEndGroupTag`
/// by calling `skip_field` on a constant input. This pins that the values it
/// mints are the values prost produces on a REAL malformed field, so the
/// minting cannot silently start returning a different error than the one it
/// is named for.
#[test]
fn the_minted_error_values_are_the_ones_protobuf_produces_in_situ() {
    // BufferUnderflow, from a 32-bit field with three bytes behind it.
    let (theirs, _) = run_protobuf(WireType::ThirtyTwoBit, 7, &[1, 2, 3]);
    let (mine, _) = run_iterative(WireType::ThirtyTwoBit, 7, &[1, 2, 3]);
    let theirs = theirs.expect_err("a 4-byte field cannot be read from 3 bytes");
    let mine = mine.expect_err("a 4-byte field cannot be read from 3 bytes");
    assert_eq!(
        mine, theirs,
        "the minted `BufferUnderflow` ({mine:?}) is not the value prost produces \
         ({theirs:?})."
    );
    assert!(
        theirs.to_string().contains("buffer underflow"),
        "prost's underflow error no longer renders as `buffer underflow` ({theirs}); the \
         generated module's table of minted values cites that text."
    );

    // UnexpectedEndGroupTag, from a group closed with the wrong tag.
    let (theirs, _) = run_protobuf(WireType::StartGroup, 1, &[0x14]);
    let (mine, _) = run_iterative(WireType::StartGroup, 1, &[0x14]);
    let theirs = theirs.expect_err("tag 2 cannot close a group opened at tag 1");
    let mine = mine.expect_err("tag 2 cannot close a group opened at tag 1");
    assert_eq!(
        mine, theirs,
        "the minted `UnexpectedEndGroupTag` ({mine:?}) is not the value prost produces \
         ({theirs:?})."
    );
    assert!(
        theirs.to_string().contains("unexpected end group tag"),
        "prost's end-group error no longer renders as `unexpected end group tag` \
         ({theirs})."
    );
}

/// ★ The ONE permitted difference, stated as a test rather than left in prose:
/// `skip_unknown_field` has no `RecursionLimitReached`, because it has no
/// recursion to limit.
///
/// The depth is chosen to straddle prost's budget of 100 — the shallow nest is
/// accepted by both, the deep one only by the iterative skipper. That is the
/// whole of the divergence, and it is in the direction the campaign intends:
/// strictly MORE valid protobuf accepted, never less.
#[test]
fn the_only_divergence_from_protobuf_is_the_absent_depth_budget() {
    let mut first_refused: Option<usize> = None;
    for depth in 1..=200 {
        let bytes = terminated_nest(depth);
        let (theirs, _) = run_protobuf(WireType::StartGroup, BOMB_TAG, &bytes);
        let (mine, my_left) = run_iterative(WireType::StartGroup, BOMB_TAG, &bytes);

        assert!(
            mine.is_ok() && my_left == 0,
            "`skip_unknown_field` refused a well-formed {depth}-deep nest ({mine:?}, \
             {my_left} byte(s) left). There is no depth at which it may refuse one."
        );
        if theirs.is_err() && first_refused.is_none() {
            first_refused = Some(depth);
        }
        if theirs.is_ok() {
            assert!(
                first_refused.is_none(),
                "prost accepted a {depth}-deep nest after having refused a shallower one \
                 — its budget is not monotone in the depth, and this file's model of it \
                 is wrong."
            );
        }
    }

    let refused_at = first_refused.expect(
        "★ prost accepted every nest up to depth 200. Its recursion limit is supposed to \
         be 100 — if the `no-recursion-limit` feature has been switched on somewhere in \
         this workspace, stock `skip_field` is no longer safe on the group bomb and \
         §F's framing (\"prost is safe because the limit exists\") is FALSE.",
    );
    assert_eq!(
        refused_at, 101,
        "prost first refused a well-formed nest at depth {refused_at}; \
         `prost::RECURSION_LIMIT` is 100 and the entered field is the first level, so the \
         first refusal is at 101. A different number means the budget has changed."
    );
    println!(
        "the sole divergence: prost refuses a well-formed nest from depth {refused_at} \
         upward; `skip_unknown_field` accepts every depth tried (1..=200) and the bomb \
         at {TERMINATED_DEPTH}."
    );
}

// ===========================================================================
// §H  Signal numbers, without a `libc` dependency
// ===========================================================================
//
// `models` does not depend on `libc` and this gate is not a reason to add one.
// Both numbers are fixed by POSIX and identical on every Linux ABI.

/// `SIGSEGV` — raised when the guard page below the stack is touched.
const fn libc_sigsegv() -> i32 { 11 }

/// `SIGABRT` — what Rust's stack-overflow handler raises after printing its
/// banner.
const fn libc_sigabrt() -> i32 { 6 }
