manifests = ["Cargo.toml", "fuzz/Cargo.toml", "scripts/soak-charts/Cargo.toml"]

[scanner]
version = "0.20.2"

[scanner.sha256]
aarch64-apple-darwin = "fe67d82a10d8597a3549364cb733a3f9cc1bfff9031b7ae46384a9f2a72090c3"
x86_64-apple-darwin = "248da7f581724e470071990c088ffc55c811981715f4cbdb258621fb79f8b7a6"
aarch64-unknown-linux-musl = "995c82be0defc7a025cae49a2aa2644ce8245c9a3318fc4103907c6a285e8c7d"
x86_64-unknown-linux-musl = "9f12ed4c49936e09b48bf862b595cde2fe64fcbd9d74dfacac6131ca824c8d5f"

[exceptions.RUSTSEC-2026-0098]
package = "rustls-webpki"
versions = ["0.101.7"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2026-0099]
package = "rustls-webpki"
versions = ["0.101.7"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2026-0104]
package = "rustls-webpki"
versions = ["0.101.7"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2026-0258]
package = "h2"
versions = ["0.3.27"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2025-0134]
package = "rustls-pemfile"
versions = ["1.0.4", "2.2.0"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2024-0387]
package = "opentelemetry_api"
versions = ["0.20.0"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2025-0141]
package = "bincode"
versions = ["1.3.3"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2021-0141]
package = "dotenv"
versions = ["0.15.0"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2021-0153]
package = "encoding"
versions = ["0.2.33"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2024-0436]
package = "paste"
versions = ["1.0.15"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2026-0247]
package = "bitmaps"
versions = ["3.1.0"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2024-0384]
package = "instant"
versions = ["0.1.13"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2024-0437]
package = "protobuf"
versions = ["2.28.0"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2025-0119]
package = "number_prefix"
versions = ["0.4.0"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06

[exceptions.RUSTSEC-2026-0173]
package = "proc-macro-error2"
versions = ["2.0.1"]
owner = "@F1R3FLY-io/ci-maintainers"
review-by = 2026-10-06
