#!/usr/bin/env bash
# Tracing-target inventory and drift checks.
#
# The EnvFilter expressions that operators and the integration harness use can
# only address tracing targets that actually exist in the source. This script
# keeps a checked-in inventory of every explicit `target: "..."` and offers
# three checks against it:
#
#   --write                      Regenerate docs/tracing-targets.txt from source.
#   --check                      (default) Fail if the inventory is stale.
#   --validate-filter <file>     Fail if any project-dotted directive target in
#                                an EnvFilter expression is absent from the
#                                inventory. <file> is either a HOCON conf with a
#                                `filter = "..."` line or a plain text file whose
#                                first line is the filter expression.
#   --ratchet                    Fail if any designated hot-path file contains a
#                                tracing macro without an explicit target.
#
# A directive target is validated only if it looks project-dotted (starts with
# "f1r3" and contains "."); bare levels, crate names (tonic, hyper, ...) and
# module paths (foo::bar) are out of scope.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INVENTORY="$REPO_ROOT/docs/tracing-targets.txt"
SRC_DIRS=(casper node comm rholang "rspace++" block-storage shared crypto graphz)

# Hot-path files where untargeted macros fail the ratchet. Extend this list as
# files are migrated; never shrink it.
RATCHET_FILES=(
  casper/src/rust/blocks/proposer/block_creator.rs
  casper/src/rust/blocks/proposer/proposer.rs
  casper/src/rust/merging/dag_merger.rs
  casper/src/rust/engine/multi_parent_casper/block_admission.rs
  casper/src/rust/engine/multi_parent_casper/validation_dispatcher.rs
  casper/src/rust/engine/multi_parent_casper/finalization_runner.rs
  casper/src/rust/util/rholang/interpreter_util.rs
)

extract_inventory() {
  local dirs=()
  for d in "${SRC_DIRS[@]}"; do
    [ -d "$REPO_ROOT/$d" ] && dirs+=("$REPO_ROOT/$d")
  done
  grep -rhoE 'target: "[^"]+"' "${dirs[@]}" --include='*.rs' 2>/dev/null \
    | sed -E 's/target: "([^"]+)"/\1/' \
    | sort -u
}

cmd_write() {
  {
    echo "# Tracing targets present in the source tree."
    echo "# Generated by scripts/ci/check-tracing-targets.sh --write; do not edit."
    extract_inventory
  } > "$INVENTORY"
  echo "wrote $(grep -vc '^#' "$INVENTORY") targets to ${INVENTORY#"$REPO_ROOT"/}"
}

cmd_check() {
  if [ ! -f "$INVENTORY" ]; then
    echo "ERROR: $INVENTORY missing — run: scripts/ci/check-tracing-targets.sh --write" >&2
    exit 1
  fi
  local current
  current=$(extract_inventory)
  local recorded
  recorded=$(grep -v '^#' "$INVENTORY")
  if [ "$current" != "$recorded" ]; then
    echo "ERROR: tracing-target inventory is stale. Diff (source vs inventory):" >&2
    diff <(echo "$recorded") <(echo "$current") >&2 || true
    echo "Fix with: scripts/ci/check-tracing-targets.sh --write" >&2
    exit 1
  fi
  echo "inventory up to date ($(echo "$current" | wc -l | tr -d ' ') targets)"
}

cmd_validate_filter() {
  local file="$1"
  if [ ! -f "$file" ]; then
    echo "ERROR: filter file not found: $file" >&2
    exit 1
  fi
  local expr
  expr=$(grep -E '^[[:space:]]*filter[[:space:]]*=' "$file" | head -1 \
    | sed -E 's/^[^"]*"([^"]*)".*/\1/')
  if [ -z "$expr" ]; then
    expr=$(head -1 "$file")
  fi
  if [ -z "$expr" ]; then
    echo "ERROR: no filter expression found in $file" >&2
    exit 1
  fi
  local missing=0
  local checked=0
  IFS=',' read -ra directives <<< "$expr"
  for d in "${directives[@]}"; do
    case "$d" in
      *=*) ;;
      *) continue ;;
    esac
    local tgt="${d%%=*}"
    case "$tgt" in
      f1r3*.*) ;;
      *) continue ;;
    esac
    checked=$((checked + 1))
    if ! grep -qxF "$tgt" <(grep -v '^#' "$INVENTORY"); then
      echo "ERROR: filter directive targets '$tgt' which does not exist in the source" >&2
      missing=$((missing + 1))
    fi
  done
  if [ "$missing" -gt 0 ]; then
    echo "($missing dead of $checked project targets in $file)" >&2
    exit 1
  fi
  echo "filter OK: $checked project targets in $file all exist"
}

cmd_ratchet() {
  local bad=0
  for f in "${RATCHET_FILES[@]}"; do
    local hits
    hits=$(awk '
      { lines[NR] = $0 }
      /tracing::(info|warn|error|debug|trace)!\(/ { if ($0 !~ /target: "/) pend[NR] = 1 }
      END {
        for (ln in pend)
          if (lines[ln + 1] !~ /target: "/ && lines[ln + 2] !~ /target: "/)
            print FILENAME ":" ln
      }' "$REPO_ROOT/$f")
    if [ -n "$hits" ]; then
      echo "ERROR: untargeted tracing macros in ratcheted file:" >&2
      echo "$hits" >&2
      bad=1
    fi
  done
  [ "$bad" -eq 0 ] && echo "ratchet clean (${#RATCHET_FILES[@]} files)"
  exit "$bad"
}

case "${1:---check}" in
  --write) cmd_write ;;
  --check) cmd_check ;;
  --validate-filter) cmd_validate_filter "${2:?usage: --validate-filter <file>}" ;;
  --ratchet) cmd_ratchet ;;
  *) echo "usage: $0 [--write|--check|--validate-filter <file>|--ratchet]" >&2; exit 2 ;;
esac
