// See casper/src/main/scala/coop/rchain/casper/ReportingProtoTransformer.scala

//! Convert rspace reporting events into the protobuf wire format
//! (`ReportProto`) consumed by the API and block info layer.
//!
//! [`ReportingProtoTransformer`] is the concrete transformer used by
//! the reporting path. It wraps rspace-level `ReportingConsume` /
//! `ReportingProduce` / `ReportingComm` values into the prost-generated
//! `ReportProto` enum, mirroring the Scala `ReportingProtoTransformer`.

use models::casper::{
    report_proto, PeekProto, ReportCommProto, ReportConsumeProto, ReportPhase as ProtoReportPhase,
    ReportProduceProto, ReportProto,
};
use models::rhoapi::{BindPattern, ListParWithRandom, Par, TaggedContinuation};
use rspace_plus_plus::rspace::reporting_rspace::{
    ReportPhase as RspaceReportPhase, ReportingComm, ReportingConsume, ReportingProduce,
};
use rspace_plus_plus::rspace::reporting_transformer::ReportingTransformer;

/// Map the rspace-level `ReportPhase` to the protobuf `ReportPhase`
/// discriminant. The proto enum is the single source of truth for
/// consumers. The default on both sides is `Unspecified`, which is what
/// reports predating the marker decode as.
pub fn to_proto_phase(phase: RspaceReportPhase) -> i32 {
    match phase {
        RspaceReportPhase::Unspecified => ProtoReportPhase::Unspecified as i32,
        RspaceReportPhase::Precharge => ProtoReportPhase::Precharge as i32,
        RspaceReportPhase::User => ProtoReportPhase::User as i32,
        RspaceReportPhase::Refund => ProtoReportPhase::Refund as i32,
    }
}

/// Transformer that serializes rspace reporting events into protobuf
/// `ReportProto` wire types. It is stateless. See the module docs and
/// the notes below for why `ReportProto` replaces Scala's
/// `ReportEventProto` and why cloning is acceptable here.
pub struct ReportingProtoTransformer;

/// ARCHITECTURAL NOTE: ReportEventProto replacement
///
/// In the original Scala version, the trait returns `ReportEventProto` which is a sealed trait
/// generated by ScalaPB from the protobuf definition with the preamble annotation:
/// `preamble: "sealed trait ReportEventProto"`
///
/// However, in Rust, protobuf generators (prost) don't understand ScalaPB annotations,
/// so instead of generating a trait, they generate:
/// - `ReportProto` struct with an optional `report` field of type `report_proto::Report`
/// - `report_proto::Report` enum with variants: `Consume`, `Produce`, `Comm`
///
/// Therefore, we replaced `ReportEventProto` with `ReportProto` and wrap concrete types
/// (ReportConsumeProto, ReportProduceProto, ReportCommProto) inside the enum variants.
///
/// This maintains the same semantic meaning but uses Rust's type system instead of Scala's.

/// PERFORMANCE NOTE: Clone usage
///
/// This transformer uses .clone() extensively because:
/// 1. We transform from borrowed references (&ReportingConsume) to owned protobuf structs
/// 2. Generated protobuf types require owned data for serialization
/// 3. This is a one-time transformation for reporting, not a hot path

impl ReportingProtoTransformer {
    /// Construct the stateless transformer.
    pub fn new() -> Self { ReportingProtoTransformer }

    /// Serialize a `ReportingConsume` into `ReportConsumeProto`,
    /// cloning the owned protobuf channel and pattern data.
    pub fn serialize_consume_proto(
        &self,
        rc: &ReportingConsume<Par, BindPattern, TaggedContinuation>,
    ) -> ReportConsumeProto {
        ReportConsumeProto {
            channels: rc.channels.clone(),
            patterns: rc.patterns.clone(),
            peeks: rc
                .peeks
                .iter()
                .map(|&idx| PeekProto { channel_index: idx })
                .collect(),
        }
    }

    /// Serialize a `ReportingProduce` into `ReportProduceProto`,
    /// cloning the owned channel and data `Par`.
    pub fn serialize_produce_proto(
        &self,
        rp: &ReportingProduce<Par, ListParWithRandom>,
    ) -> ReportProduceProto {
        ReportProduceProto {
            channel: Some(rp.channel.clone()),
            data: Some(rp.data.clone()),
        }
    }

    /// Serialize a `ReportingComm` into `ReportCommProto`,
    /// delegating to the consume and produce helpers for its parts.
    pub fn serialize_comm_proto(
        &self,
        rcm: &ReportingComm<Par, BindPattern, ListParWithRandom, TaggedContinuation>,
    ) -> ReportCommProto {
        ReportCommProto {
            consume: Some(self.serialize_consume_proto(&rcm.consume)),
            produces: rcm
                .produces
                .iter()
                .map(|p| self.serialize_produce_proto(p))
                .collect(),
        }
    }
}

/// Implementation of the generic ReportingTransformer trait
///
/// This implementation mirrors the Scala architecture where ReportingProtoTransformer
/// extends ReportingTransformer[..., ReportEventProto]. In Scala, the class has:
/// 1. Concrete methods (serializeConsume/Produce/Comm) returning specific Proto types
/// 2. Trait methods that wrap these concrete types into the generic ReportEventProto
///
/// Similarly, our Rust implementation has:
/// 1. Helper methods (*_proto) that return concrete protobuf types (ReportConsumeProto, etc.)
/// 2. This trait implementation that wraps concrete types into the generic ReportProto
///
/// This dual-layer approach is NOT redundant - it precisely replicates the Scala design
/// where you can work with both concrete protobuf types and the generic event wrapper.
impl ReportingTransformer<Par, BindPattern, ListParWithRandom, TaggedContinuation, ReportProto>
    for ReportingProtoTransformer
{
    /// Wrap a serialized consume into the generic `ReportProto`
    /// envelope (`Report::Consume`).
    fn serialize_consume(
        &self,
        rc: &ReportingConsume<Par, BindPattern, TaggedContinuation>,
    ) -> ReportProto {
        let consume_proto = self.serialize_consume_proto(rc);
        ReportProto {
            report: Some(report_proto::Report::Consume(consume_proto)),
        }
    }

    /// Wrap a serialized produce into the generic `ReportProto`
    /// envelope (`Report::Produce`).
    fn serialize_produce(&self, rp: &ReportingProduce<Par, ListParWithRandom>) -> ReportProto {
        let produce_proto = self.serialize_produce_proto(rp);
        ReportProto {
            report: Some(report_proto::Report::Produce(produce_proto)),
        }
    }

    /// Wrap a serialized comm into the generic `ReportProto`
    /// envelope (`Report::Comm`).
    fn serialize_comm(
        &self,
        rcm: &ReportingComm<Par, BindPattern, ListParWithRandom, TaggedContinuation>,
    ) -> ReportProto {
        let comm_proto = self.serialize_comm_proto(rcm);
        ReportProto {
            report: Some(report_proto::Report::Comm(comm_proto)),
        }
    }

    // Equivalent to Scala: override def transformEvent(re: ReportingRspace.ReportingEvent): ReportEventProto = super.transformEvent(re)
    // The default implementation from ReportingTransformer trait handles this automatically
}
