#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROOF_ROOT="$ROOT/formal/rocq/cost_accounted_rho"
THEORIES="$PROOF_ROOT/theories"
SLASHING_ROOT="$ROOT/formal/rocq/slashing"
VALIDATOR_ROOT="$ROOT/formal/rocq/validator"
VALIDATOR_THEORIES="$VALIDATOR_ROOT/theories"
VERIFICATION_DOCS=(
  "$ROOT/docs/casper/theory/cost-accounted-rho-verification.md"
  "$ROOT/docs/casper/theory/cost-accounting-migration.md"
  "$ROOT/docs/casper/theory/cost-accounting-use-cases.md"
  "$ROOT/docs/casper/theory/cost-accounting-threat-model.md"
)
WORK_ROOT="$ROOT/target/verification/cost-accounted-rho/proofs"
mkdir -p "$WORK_ROOT"

echo "Checking cost-accounted rho proof hygiene..."

proof_module_count="$(find "$THEORIES" -maxdepth 1 -type f -name '*.v' | wc -l | tr -d ' ')"
listed_module_count="$(rg -N '^[[:space:]]*theories/[A-Za-z0-9_]+\.v[[:space:]]*$' \
  "$PROOF_ROOT/_CoqProject" | wc -l | tr -d ' ')"
proof_line_count="$(find "$THEORIES" -maxdepth 1 -type f -name '*.v' -print0 \
  | xargs -0 wc -l | awk 'END {print $1}')"
proof_term_count="$(rg -o '\b(Qed|Defined)\.' "$THEORIES" --glob '*.v' \
  | wc -l | tr -d ' ')"

if [[ "$proof_module_count" != "$listed_module_count" ]]; then
  echo "error: _CoqProject lists $listed_module_count of $proof_module_count Rocq modules" >&2
  exit 1
fi

verification_doc_plain="$(perl -0pe \
  's/(?<=\d),(?=\d)//g; s/\n[[:space:]]*/ /g' \
  "${VERIFICATION_DOCS[0]}")"
required_scale_claims=(
  "across $proof_module_count modules and $proof_line_count lines of development"
  "All $proof_term_count \`Qed.\`/\`Defined.\` proof terms"
  "development spans $proof_module_count modules and $proof_line_count lines, with $proof_term_count \`Qed.\`"
  "| Rocq source files                                | $proof_module_count modules"
  "| Total lines of Rocq                              | $proof_line_count"
  "| Proven lemmas and theorems (\`Qed.\` / \`Defined.\`) | $proof_term_count"
  "foundational 32-module subgraph of the $proof_module_count-module formalization"
  "current $proof_module_count-module catalog"
)
for claim in "${required_scale_claims[@]}"; do
  if ! rg -q -F "$claim" <<<"$verification_doc_plain"; then
    echo "error: stale or missing Rocq scale claim: $claim" >&2
    exit 1
  fi
done

SANITIZED_THEORIES="$(mktemp -d "$WORK_ROOT/sanitized.XXXXXX")"
for proof in "$THEORIES"/*.v; do
  perl -0pe 's/\(\*.*?\*\)//gs' "$proof" > "$SANITIZED_THEORIES/$(basename "$proof")"
done
# Validator behavioral-contract aggregation (Workstream E, stage E5): a thin
# subtree that NAMES the contract by re-exporting already-proven obligations.
# Subject it to the same Admitted/Axiom/incompletion-marker hygiene gate.
for proof in "$VALIDATOR_THEORIES"/*.v; do
  perl -0pe 's/\(\*.*?\*\)//gs' "$proof" > "$SANITIZED_THEORIES/validator__$(basename "$proof")"
done
# Slashing development (Stage-C two-effect slash + redemption; #14): the
# validator-contract dependency compiled below. It was previously compiled but
# NOT axiom-gated; subject its theories to the same Admitted/Axiom/incompletion
# hygiene scan as the cost-accounted + validator trees.
for proof in "$SLASHING_ROOT/theories"/*.v; do
  perl -0pe 's/\(\*.*?\*\)//gs' "$proof" > "$SANITIZED_THEORIES/slashing__$(basename "$proof")"
done

assumptions="$(mktemp "$WORK_ROOT/assumptions.XXXXXX.log")"
trap 'rm -rf "$SANITIZED_THEORIES"; rm -f "$assumptions"' EXIT

if rg -n '(^|[[:space:]])(Admitted\.|admit\.)|^[[:space:]]*(Conjecture|Parameter)[[:space:]]' "$SANITIZED_THEORIES"; then
  echo "error: found an admitted proof or unsupported declaration" >&2
  exit 1
fi

if rg -n '^[[:space:]]*Axiom[[:space:]]+[A-Za-z0-9_]+[[:space:]]*:' "$SANITIZED_THEORIES"; then
  echo "error: found an axiom in the cost-accounted rho theories" >&2
  exit 1
fi

if rg -ni 'TODO|FIXME|future work|not formally proven|open work|deferred[[:space:]]+(to|until|work|implementation|proof|testing)|\b(implementation|proof|testing|work)[[:space:]]+(is[[:space:]]+)?deferred\b|\b(implementation|proof|testing|work)[[:space:]]+deferral\b' "$SANITIZED_THEORIES" "${VERIFICATION_DOCS[@]}"; then
  echo "error: found an incompletion marker in proof theories or verification docs" >&2
  exit 1
fi

# "placeholder" as an incompletion marker is rejected except for two modeled
# domain terms: unsigned threshold-cosigner slots and the historical unresolved
# PoS template literal that the fail-closed compiler model must name and refute.
# A genuine "placeholder proof / stub / section" carries neither vocabulary and
# is still rejected.
placeholder_hits="$(rg -n 'placeholder' "$SANITIZED_THEORIES" "${VERIFICATION_DOCS[@]}" \
  | rg -iv 'cosigner|threshold|signer|`sig`|\bsig\b|wallet|funding_sig|template|PoS|controller|literal|unresolved' || true)"
if [ -n "$placeholder_hits" ]; then
  printf '%s\n' "$placeholder_hits" >&2
  echo "error: found a non-domain 'placeholder' incompletion marker in proof theories or verification docs" >&2
  exit 1
fi

echo "Compiling and checking Rocq theories..."
(
  cd "$PROOF_ROOT"
  rocq makefile -f _CoqProject -o Makefile >/dev/null
  make -j"${ROCQ_JOBS:-2}" >/dev/null
  proof_modules=()
  while IFS= read -r proof; do
    module="${proof#theories/}"
    module="${module%.v}"
    proof_modules+=("CostAccountedRho.${module}")
  done < <(rg -N '^[[:space:]]*theories/[A-Za-z0-9_]+\.v[[:space:]]*$' _CoqProject | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  rocqchk -Q theories CostAccountedRho "${proof_modules[@]}" >/dev/null 2>&1
)

echo "Compiling the Slashing development (validator contract dependency)..."
(
  cd "$SLASHING_ROOT"
  rocq makefile -f _CoqProject -o Makefile >/dev/null
  make -j"${ROCQ_JOBS:-2}" >/dev/null
)

echo "Compiling and checking the validator contract aggregation..."
(
  cd "$VALIDATOR_ROOT"
  rocq makefile -f _CoqProject -o Makefile >/dev/null 2>&1
  make -j"${ROCQ_JOBS:-2}" >/dev/null
  rocqchk -Q ../cost_accounted_rho/theories CostAccountedRho \
          -Q ../slashing/theories Slashing \
          -Q theories Validator Validator.Contract >/dev/null 2>&1
)

if ! rocq repl -Q "$THEORIES" CostAccountedRho > "$assumptions" 2>&1 <<'EOF'
From CostAccountedRho Require Import CostAccountedSyntax TranslationFaithfulness Bisimulation Replication Settlement SlashingComposition MergeableChannelAccounting RuntimeBudgetRefinement AtomicCommAccounting MultiSignerRefinement LinearLogicResources LLIdentities MintingInjection MintingHalt UseCaseAdequacy SystemStructEquiv SyntacticSugar WalletNaming ChannelSeparation TokenConservation FuelEventDecomposition Exchange BoundedLedger GSLTOSLFCapstone Rule45ContinuationAdequacy CAReduction WrappingSubjectReduction SignatureMonoid CATokenConservation CAStrongNormalization CAConfluence CAStepDeterminism CACostDeterminism CAModulus ContinuedGSLTCapstone CAGradedTransition CATranslation CostMonad CATranslationLemmas CATranslationFaithfulness CABisimulation CASettlement CAMintingInjection CAExchange CAEconomicCapstone CALocatedPurses CAGradedAdequacy CAAdjunctions CATypeDiscipline CAOSLFSpatialModal CAGradedImageFinite CAGradedSuccPairs CAGradedCompleteness CAInternalisation CAGradedLimit CAForceSeparation CAJoinConservation CategoryInterface CACategory CACostFunctor CACostFunctorCI CACostMonadCat CAAdjunctionI CACostMonadInstances CASimulationBicat CAAdjunctionII CAProperSubcategory CAAbstractCapstone CAUntypedLambda CAUntypedLambdaCI EndToEndAuthority.
From CostAccountedRho Require Import LocatedAuthoritySettlement RuntimeBoundAuthority PayloadSortPersistence SettlementMergeVisibility StructuralAuthorityBound RuntimeAuthorityScope StackTransferConservation StackIntroductionAtomicity EvaluationTransactionIsolation MergeableEvidenceAuthentication ParallelStackMaterialization StateBoundFrontierExpansion VaultBackedCostLifecycle AtomicVaultSettlementRefinement WalletFundedLollipop FundingSlotBootstrap PoSVaultAuthority PhysicalSettlementWorklist ReplayRootMaterialization CanonicalRevRedemption RedemptionCustodyAtomicity RedemptionMintResumption BondIssuanceLifecycle VaultBackedByteAccounting MultiShardConcurrency DeterministicParallelReduction.
From CostAccountedRho Require Import ThresholdEnvelopeAuthority ReplayAdmissionPublication CanonicalCustodyAliasing EpochMintAtomicity MintedEpochRetention ValidatorEconomicsLifecycle ValidatorEconomicsRefinement ValidatorEconomicsReplay CheckpointAdmissionRecertification.
From CostAccountedRho Require Import StateImportClosure StateImportStorage StateImportPage StateImportCodec StateImportCursor StateImportTraversal StateImportStack StateImportExport StateImportExecution StateImportWire StateImportCold StateImportEncodedCold StateImportOccurrence StateImportOverlay StateImportReceivedCold StateImportObservations StateImportHistoryObservations StateImportReadTape StateImportOwnedPage StateImportScan StateImportCheckpoint.
From CostAccountedRho Require Import StateImportRetry.
Print Assumptions import_valid_physical_alias_encodings_are_disjoint_and_injective.
Print Assumptions import_absence_budget_is_bounded_by_physical_locations.
Print Assumptions import_two_alias_formats_give_two_locations_per_key.
Print Assumptions import_byte_preserving_extensions_cannot_increase_absence.
Print Assumptions import_changed_guard_under_extension_consumes_absence.
Print Assumptions import_physical_trace_retains_every_observed_byte.
Print Assumptions import_successful_physical_refresh_observes_initial_bytes.
Print Assumptions import_fresh_reads_after_definite_conflict_strictly_reduce_retry_budget.
Print Assumptions import_physical_retries_have_a_strict_finite_budget.
Print Assumptions import_initial_physical_trace_establishes_the_retry_premise.
Print Assumptions import_two_alias_retry_attempts_are_bounded_by_initial_absence.
Print Assumptions import_final_conflict_is_bounded_even_if_refresh_fails.
Print Assumptions import_normalized_transaction_conflict_requires_an_external_guard_mismatch.
Print Assumptions import_normalized_final_cas_failure_consumes_a_distinct_absence.
Print Assumptions import_normalization_preserves_every_required_physical_guard.
Print Assumptions import_normalization_produces_one_guard_per_physical_location.
Print Assumptions import_normalization_does_not_increase_the_two_alias_budget.
Print Assumptions import_checkpoint_delta_covers_new_reachability.
Print Assumptions import_checkpoint_delta_establishes_consumable_new_root.
Print Assumptions import_checkpoint_construction_derives_delta_cut.
Print Assumptions import_checkpoint_construction_is_ready_for_publication.
Print Assumptions import_checkpoint_publication_survives_independent_batches.
Print Assumptions import_checkpoint_first_root_requires_no_persisted_base.
Print Assumptions import_checkpoint_reuse_requires_the_original_context.
Print Assumptions import_checkpoint_physical_commits_preserve_new_and_captured_roots.
Print Assumptions import_checkpoint_compaction_preserves_absolute_reference.
Print Assumptions import_checkpoint_split_preserves_absolute_reference.
Print Assumptions import_encoded_run_fills_absence_only_with_resolved_content.
Print Assumptions import_observed_alias_bytes_or_repair_survive_guarded_writes.
Print Assumptions import_actual_alias_observations_retain_bytes_or_guarded_repairs.
Print Assumptions import_strict_resolution_identifies_any_present_decoded_alias.
Print Assumptions import_observed_strict_leaf_establishes_a_current_binding.
Print Assumptions import_successful_read_only_cold_check_has_a_current_binding.
Print Assumptions import_failed_or_unread_alias_cannot_pass_read_only_validation.
Print Assumptions import_read_only_history_check_uses_retained_physical_bytes.
Print Assumptions import_history_observation_trace_preserves_initial_bytes.
Print Assumptions import_validated_leaf_refines_consuming_read.
Print Assumptions import_actual_physical_reference_check_refines_consuming_reads.
Print Assumptions import_physical_episode_preserves_all_checked_bindings.
Print Assumptions import_scan_episode_failure_is_sticky.
Print Assumptions import_scan_required_read_failure_retains_unresolved_work.
Print Assumptions import_successful_physical_episode_refines_scan_steps.
Print Assumptions import_consumer_runs_compose.
Print Assumptions import_successful_physical_scan_refines_consuming_execution.
Print Assumptions import_complete_physical_scan_establishes_original_root_closure.
Print Assumptions import_completed_scan_remains_consumable_during_publication.
Print Assumptions import_failed_scan_cannot_recover_with_later_observations.
Print Assumptions import_scan_without_more_episodes_does_not_hide_pending_work.
Print Assumptions import_collector_erasure_preserves_slice_errors_and_reads.
Print Assumptions import_collector_erasure_preserves_anchor_errors_and_reads.
Print Assumptions import_collector_erasure_preserves_cursor_errors_and_reads.
Print Assumptions import_consumed_origin_authenticates_the_wire_root.
Print Assumptions import_owned_cursor_keeps_origin_and_page_phases_separate.
Print Assumptions import_owned_attempt_requires_preparation_before_origin_reads.
Print Assumptions import_owned_attempt_preserves_original_context_after_history_commit.
Print Assumptions import_owned_committed_page_has_exact_root_specific_occurrences.
Print Assumptions import_owned_committed_reply_preserves_metadata_and_singleton_origin.
Print Assumptions import_owned_advance_never_changes_the_original_root.
Print Assumptions import_owned_nonterminal_advance_retains_the_wire_root_and_origin.
Print Assumptions import_owned_leaf_only_exhaustion_retains_all_owner_coordinates.
Print Assumptions import_owned_singleton_advance_retains_the_exact_original_occurrence.
Print Assumptions import_owned_advance_preserves_its_authenticated_origin.
Print Assumptions import_located_collection_preserves_all_cursor_results.
Print Assumptions import_located_zero_skip_slice_is_a_page.
Print Assumptions import_located_collection_has_exact_step_occurrences.
Print Assumptions import_located_anchor_has_exact_occurrences.
Print Assumptions import_located_cursor_collector_returns_the_operational_occurrences.
Print Assumptions import_located_slice_has_complete_witnesses.
Print Assumptions import_located_cursor_has_complete_witnesses.
Print Assumptions import_owned_location_erasure_preserves_origin_errors_and_reads.
Print Assumptions import_owned_collector_authenticates_its_returned_locations.
Print Assumptions import_actual_owned_collector_authenticates_locations_before_writes.
Print Assumptions import_actual_owned_collector_preserves_the_same_locations_after_commit.
Print Assumptions import_history_byte_extension_preserves_checked_reads.
Print Assumptions import_owned_locations_survive_later_history_extensions.
Print Assumptions import_owned_preparation_checks_the_returned_list_before_any_commit.
Print Assumptions import_invalid_owned_page_has_no_attempt_writes.
Print Assumptions import_failed_owned_commit_never_advances_the_cursor.
Print Assumptions import_failed_cold_commit_keeps_history_and_the_previous_owner.
Print Assumptions import_owned_commit_success_requires_validation_and_both_commits.
Print Assumptions import_owned_commit_connects_actual_reads_to_exact_typed_consumption.
Print Assumptions import_owned_receipt_consumption_survives_compatible_writes.
Print Assumptions import_history_read_consumes_exactly_the_next_record.
Print Assumptions import_tape_rejection_cannot_be_replaced_by_a_later_result.
Print Assumptions import_tape_stack_refines_exact_stack_evaluation.
Print Assumptions import_tape_step_refines_exact_step_evaluation.
Print Assumptions import_tape_slice_refines_exact_slice_evaluation.
Print Assumptions import_prepared_observed_reader_equals_overlay_reader.
Print Assumptions import_tape_cursor_refines_operational_export.
Print Assumptions import_checked_tape_attempt_consumes_the_complete_invocation.
Print Assumptions import_history_first_callback_has_an_actual_preparation_prefix.
Print Assumptions import_checked_actual_tape_has_preparation_and_exact_export.
Print Assumptions import_checked_actual_tape_cannot_hide_an_unsuccessful_callback.
Print Assumptions import_checked_actual_tape_derives_its_final_checked_overlay.
Print Assumptions import_tape_stack_never_exhausts_path_derived_fuel.
Print Assumptions import_tape_step_never_returns_an_unclassified_read_failure.
Print Assumptions import_tape_slice_never_exhausts_derived_fuel.
Print Assumptions import_history_trace_retains_every_physical_result.
Print Assumptions import_history_trace_derives_observation_origins.
Print Assumptions import_history_trace_records_exact_read_states.
Print Assumptions import_history_trace_reads_each_key_once.
Print Assumptions import_history_trace_records_each_logical_lookup.
Print Assumptions import_prepared_history_rows_have_successful_compatibility_observations.
Print Assumptions import_history_overlay_never_hides_unread_or_failed_received_keys.
Print Assumptions import_checked_history_access_has_observed_byte_origin.
Print Assumptions import_history_cache_growth_preserves_successful_logical_reads.
Print Assumptions import_history_logical_trace_has_exact_successful_final_view.
Print Assumptions import_history_trace_exposes_only_physically_observed_checked_bytes.
Print Assumptions import_history_trace_preserves_all_successfully_observed_bytes.
Print Assumptions import_history_checked_bytes_are_current_or_await_received_absence_comparison.
Print Assumptions import_successful_history_batch_has_both_checked_stages.
Print Assumptions import_history_batch_commit_can_reuse_preflight_authentication.
Print Assumptions import_failed_history_batch_preserves_the_entire_commit_store.
Print Assumptions import_history_batch_preserves_all_existing_bytes.
Print Assumptions import_history_batch_writes_only_authenticated_received_bytes.
Print Assumptions import_history_batch_preserves_every_unreceived_key.
Print Assumptions import_history_batch_rechecks_stale_absence_without_overwriting.
Print Assumptions import_history_batch_requires_successful_prior_observations.
Print Assumptions import_history_batch_rejects_unread_or_failed_received_keys.
Print Assumptions import_history_batch_rejects_conflicting_duplicates_atomically.
Print Assumptions import_history_batch_storage_failure_discards_every_staged_row.
Print Assumptions import_valid_history_batch_accepts_compatible_current_bytes.
Print Assumptions import_history_batch_has_actual_successful_read_witnesses.
Print Assumptions import_history_commit_preserves_every_successful_callback.
Print Assumptions import_physical_history_extension_preserves_the_decoded_projection.
Print Assumptions import_observed_history_batch_preserves_joint_history_and_cold_bindings.
Print Assumptions import_observed_history_batch_extends_the_joint_storage_run.
Print Assumptions import_observed_history_and_cold_batches_refine_a_consuming_scan_write.
Print Assumptions import_observed_history_and_cold_batches_preserve_every_consumable_root.
Print Assumptions import_actual_history_commit_derives_tape_reader_agreement.
Print Assumptions import_accepted_page_after_history_commit_has_the_same_operational_export.
Print Assumptions import_observation_trace_preserves_exact_read_states.
Print Assumptions import_observation_trace_derives_every_observation.
Print Assumptions import_observation_trace_retains_every_read_including_failures.
Print Assumptions import_observation_trace_reads_each_physical_location_once.
Print Assumptions import_accepted_physical_batch_has_read_evidence_for_each_alias.
Print Assumptions import_physical_batch_never_treats_unread_or_failed_aliases_as_absent.
Print Assumptions import_required_failed_record_prevents_later_commit.
Print Assumptions import_recorded_bytes_match_the_commit_state_without_a_common_read_snapshot.
Print Assumptions import_received_rows_with_actual_read_trace_preserve_bytes_provenance_and_typed_consumption.
Print Assumptions import_observed_batches_ignore_untouched_observation_values.
Print Assumptions import_received_row_has_exact_authorization.
Print Assumptions import_accepted_received_occurrence_has_an_original_row.
Print Assumptions import_accepted_received_page_has_exact_cold_key_coverage.
Print Assumptions import_received_rows_cannot_hide_invalid_duplicates.
Print Assumptions import_received_page_acceptance_is_permutation_invariant.
Print Assumptions import_received_permutations_preserve_decoded_maps_not_trailer_bytes.
Print Assumptions import_received_batch_establishes_every_authorized_occurrence.
Print Assumptions import_canonical_cursor_context_reaches_guarded_cold_consumption.
Print Assumptions import_received_history_check_authenticates_bytes.
Print Assumptions import_staged_history_row_preserves_observed_bytes.
Print Assumptions import_staged_history_row_has_authenticated_binding.
Print Assumptions import_history_overlay_preserves_every_observed_binding.
Print Assumptions import_history_overlay_authenticates_every_received_row.
Print Assumptions import_history_overlay_does_not_change_unreceived_keys.
Print Assumptions import_history_overlay_rejects_conflicting_duplicate_rows.
Print Assumptions import_accepted_history_row_order_does_not_change_the_overlay.
Print Assumptions import_history_overlay_preserves_nonabsent_observations.
Print Assumptions import_prepared_history_rows_are_initially_compatible_and_consistent.
Print Assumptions import_valid_compatible_consistent_history_rows_can_be_prepared.
Print Assumptions import_successful_history_order_implies_every_permutation_succeeds.
Print Assumptions import_prepared_interleaved_reply_has_canonical_coverage.
Print Assumptions import_checked_cursor_reply_preserves_exact_occurrences_and_singleton_origin.
Print Assumptions import_accepted_reply_matches_checked_export.
Print Assumptions import_missing_or_extra_received_key_rejects.
Print Assumptions import_forged_continuation_rejects.
Print Assumptions import_wrong_requested_path_rejects.
Print Assumptions import_overlay_traversal_has_checked_byte_evidence.
Print Assumptions import_checked_overlay_reads_survive_compatible_observations.
Print Assumptions import_history_paths_compose.
Print Assumptions import_frame_spine_authenticates_all_frames.
Print Assumptions import_step_annotations_erase_exactly.
Print Assumptions import_history_step_authenticates_next_singleton_origin.
Print Assumptions import_located_step_has_authenticated_occurrences.
Print Assumptions import_located_page_erases_without_changing_budget_or_stack.
Print Assumptions import_every_page_admits_occurrence_annotations.
Print Assumptions import_located_page_authenticates_every_occurrence.
Print Assumptions import_interleaved_page_retains_authenticated_occurrence_annotations.
Print Assumptions import_interleaved_cursor_export_preserves_starting_reads.
Print Assumptions import_located_step_has_complete_occurrences.
Print Assumptions import_located_page_has_complete_occurrences.
Print Assumptions import_skipped_slice_has_complete_occurrence_annotations.
Print Assumptions import_cursor_export_has_complete_occurrence_annotations.
Print Assumptions import_last_occurrence_has_exact_position.
Print Assumptions import_exhausted_cursor_keeps_exact_last_occurrence_origin.
Print Assumptions import_occurrence_checks_cover_every_occurrence.
Print Assumptions import_cold_occurrence_success_is_exact.
Print Assumptions import_accepted_occurrence_has_consumable_payload.
Print Assumptions import_one_payload_cannot_satisfy_conflicting_occurrence_kinds.
Print Assumptions import_missing_or_failed_occurrence_cannot_be_accepted.
Print Assumptions import_encoded_alias_guard_preserves_malformed_presence.
Print Assumptions import_guarded_encoded_insert_preserves_bytes_and_resolves_the_inserted_leaf.
Print Assumptions import_arbitrary_encoded_attempts_preserve_bytes_and_logical_bindings.
Print Assumptions import_interleaved_encoded_alias_reads_preserve_the_decoded_leaf.
Print Assumptions import_authenticated_encoded_commit_establishes_the_consuming_read.
Print Assumptions import_encoded_attempt_histories_preserve_all_readable_roots.
Print Assumptions import_checked_observations_transfer_the_commit_guard.
Print Assumptions import_failed_observed_attempt_preserves_the_commit_store.
Print Assumptions import_changed_alias_observation_prevents_commit.
Print Assumptions import_observed_attempt_preserves_concurrent_unrelated_keys.
Print Assumptions import_arbitrary_observed_attempts_refine_guarded_runs.
Print Assumptions import_stale_alias_preflight_permits_conflicting_target_only_commits.
Print Assumptions import_failed_encoded_batch_preserves_the_entire_commit_store.
Print Assumptions import_checked_batch_observations_transfer_staging.
Print Assumptions import_matched_valid_batch_cannot_fail_its_commit_state_guards.
Print Assumptions import_observed_batches_preserve_definite_rollback_and_guarded_progress.
Print Assumptions import_observed_batch_extends_the_joint_storage_run.
Print Assumptions import_interleaved_history_and_cold_batches_preserve_both_binding_domains.
Print Assumptions import_history_and_cold_commits_preserve_every_consumable_root.
Print Assumptions import_history_and_cold_commits_refine_a_consuming_scan_write.
Print Assumptions import_conflicting_repeated_batch_rows_never_publish_a_staged_prefix.
Print Assumptions import_compatible_repeated_batch_rows_preserve_the_first_encoding.
Print Assumptions import_parsed_leaf_hash_uses_the_exact_payload_frame.
Print Assumptions import_completed_consuming_scan_establishes_consumable_closure.
Print Assumptions import_completion_cannot_hide_a_failed_nested_decoder.
Print Assumptions import_authenticated_guarded_insertion_establishes_consuming_read.
Print Assumptions import_skip_typed_consumption_allows_unsafe_completion.
Print Assumptions import_arbitrary_batches_preserve_all_consumable_roots.
Print Assumptions import_guarded_batches_preserve_typed_split_readers.
Print Assumptions import_completed_interleaved_scan_establishes_closure.
Print Assumptions import_contextual_children_account_for_every_edge.
Print Assumptions import_history_child_retains_occurrence_context.
Print Assumptions import_cold_child_kind_comes_from_occurrence_path.
Print Assumptions import_failed_batch_does_not_commit_its_staged_prefix.
Print Assumptions import_arbitrary_batches_preserve_exact_bindings_without_global_agreement.
Print Assumptions import_arbitrary_batches_preserve_closed_roots_without_global_agreement.
Print Assumptions import_arbitrary_batches_preserve_split_readers_without_global_agreement.
Print Assumptions import_arbitrary_page_composition_preserves_leaves.
Print Assumptions import_arbitrary_page_composition_preserves_history.
Print Assumptions import_arbitrary_pages_preserve_each_history_budget.
Print Assumptions import_leaf_only_page_remains_nonempty.
Print Assumptions import_history_page_split_preserves_every_occurrence.
Print Assumptions import_history_page_split_respects_budget.
Print Assumptions import_positive_history_budget_makes_progress.
Print Assumptions import_history_page_remainder_requires_full_occurrence_budget.
Print Assumptions import_wire_node_acceptance_characterization.
Print Assumptions import_unique_slots_derive_node_capacity.
Print Assumptions import_node_encoded_length_is_bounded.
Print Assumptions import_decoded_record_order_retains_original_input.
Print Assumptions import_decoded_record_order_preserves_any_hash.
Print Assumptions import_wire_projection_ignores_unique_record_order.
Print Assumptions import_wire_projection_has_exactly_256_slots.
Print Assumptions import_wire_projection_retains_every_record.
Print Assumptions import_32_byte_storage_keys_do_not_alias.
Print Assumptions import_closure_mapping_retains_original_input.
Print Assumptions import_raw_hash_factors_through_closure_mapping.
Print Assumptions import_history_mapping_retains_occurrence_context.
Print Assumptions import_leaf_mapping_retains_occurrence_kind.
Print Assumptions import_cursor_acceptance_characterization.
Print Assumptions import_cursor_decode_encode_round_trip.
Print Assumptions import_cursor_encoding_is_injective.
Print Assumptions import_accepted_cursor_has_exact_shape.
Print Assumptions import_accepted_cursor_has_fixed_width_words.
Print Assumptions import_accepted_cursor_preserves_root_and_carrier.
Print Assumptions import_checked_wire_and_closure_history_reads_correspond.
Print Assumptions import_path_resolution_characterization.
Print Assumptions import_history_path_is_deterministic.
Print Assumptions import_cursor_path_validation_characterization.
Print Assumptions import_valid_empty_resume_binds_carrier_to_root.
Print Assumptions import_valid_cursor_target_has_authenticated_bytes.
Print Assumptions import_compatible_wire_writes_extend_checked_reader.
Print Assumptions import_interleaved_path_has_final_view_witness.
Print Assumptions import_concurrent_path_resolution_preserves_selected_target.
Print Assumptions import_resolved_path_survives_writes_after_final_read.
Print Assumptions import_stack_builder_characterization.
Print Assumptions import_history_stack_frames_have_exact_reads.
Print Assumptions import_stack_reconstruction_preserves_carrier.
Print Assumptions import_interleaved_stack_has_final_view_witness.
Print Assumptions import_reconstructed_stack_survives_writes_after_final_read.
Print Assumptions import_parent_frame_retains_exactly_later_siblings.
Print Assumptions import_next_entry_resumes_at_exact_parent_successor.
Print Assumptions import_export_step_preserves_complete_trace.
Print Assumptions import_export_run_preserves_complete_trace.
Print Assumptions import_page_execution_matches_history_occurrence_split.
Print Assumptions import_page_execution_respects_history_budget.
Print Assumptions import_interleaved_export_has_exact_final_view_run.
Print Assumptions import_interleaved_export_and_trailing_writes_preserve_occurrences.
Print Assumptions import_slice_execution_matches_history_skip_and_take.
Print Assumptions import_export_exhaustion_requires_an_empty_stack.
Print Assumptions import_taking_step_strictly_reduces_export_potential.
Print Assumptions import_skipping_step_strictly_reduces_export_potential.
Print Assumptions import_missing_child_is_not_positive_budget_completion.
Print Assumptions import_page_adapter_preserves_operational_leaf_occurrences.
Print Assumptions import_page_adapter_preserves_operational_history_occurrences.
Print Assumptions import_anchored_export_matches_exact_skip_and_take.
Print Assumptions import_cursor_initial_frames_have_matching_reads.
Print Assumptions import_cursor_export_respects_history_budget.
Print Assumptions import_step_evaluation_characterization.
Print Assumptions import_evaluated_read_failure_has_exact_witness.
Print Assumptions import_successful_step_preserves_frame_coherence.
Print Assumptions import_evaluation_never_exhausts_its_derived_fuel.
Print Assumptions import_bounded_slice_returns_success_or_read_failure.
Print Assumptions import_bounded_slice_success_characterization.
Print Assumptions import_successful_slices_are_deterministic.
Print Assumptions import_bounded_evaluation_respects_history_budget.
Print Assumptions import_bounded_evaluation_has_exact_occurrence_split.
Print Assumptions import_slice_error_has_a_reachable_failed_read.
Print Assumptions import_reported_read_failure_is_not_fabricated.
Print Assumptions import_interleaved_slice_has_exact_final_view_page.
Print Assumptions import_interleaved_slice_matches_final_evaluator.
Print Assumptions import_interleaved_slice_and_trailing_writes_preserve_page_result.
Print Assumptions import_interleaved_cursor_export_has_exact_final_view.
Print Assumptions import_interleaved_cursor_export_preserves_its_history_budget.
Print Assumptions import_interleaved_invocation_preserves_existing_reader_bindings.
Print Assumptions import_wire_success_preserves_exact_occurrences.
Print Assumptions import_wire_success_has_canonical_next_cursor.
Print Assumptions import_wire_adapter_never_changes_errors_to_success.
Print Assumptions import_wire_bounded_execution_cannot_report_fuel_exhaustion.
Print Assumptions import_wire_bounded_execution_preserves_history_limit.
Print Assumptions import_wire_budget_metadata_is_independent_of_entries.
Print Assumptions import_wire_rejects_unrepresentable_budget_prefix.
Print Assumptions import_leaf_only_terminal_page_retains_every_leaf.
Print Assumptions import_exhausted_singleton_retains_exact_raw_history_key.
Print Assumptions import_wire_adapter_preserves_interleaved_results.
Print Assumptions import_unavailable_classification_requires_initial_observation.
Print Assumptions import_root_storage_failure_cannot_be_unavailability.
Print Assumptions import_invalid_root_payload_cannot_be_unavailability.
Print Assumptions import_empty_wire_response_does_not_identify_availability.
Print Assumptions import_operational_step_preserves_frame_spine.
Print Assumptions import_frame_spine_with_fresh_top_reconstructs_exactly.
Print Assumptions import_cursor_export_final_position_reconstructs_exactly.
Print Assumptions import_interleaved_cursor_export_next_cursor_has_exact_residual_stack.
Print Assumptions import_every_step_strictly_advances_position.
Print Assumptions import_nonterminal_cursor_export_changes_its_cursor.
Print Assumptions import_nonterminal_interleaved_cursor_export_changes_its_cursor.
Print Assumptions import_available_root_has_captured_authenticated_bytes.
Print Assumptions import_deduplicated_payloads_cover_exact_occurrence_keys.
Print Assumptions import_missing_payload_cannot_be_silently_omitted.
Print Assumptions import_independent_payload_orders_preserve_same_key_set.
Print Assumptions import_interleaved_payload_loading_preserves_observed_bindings.
Print Assumptions import_interleaved_payload_loading_matches_final_view.
Print Assumptions import_interleaved_payload_loading_preserves_exact_coverage.
Print Assumptions import_empty_resume_and_start_have_distinct_export_behavior.
Print Assumptions unmatched_introduction_costs_zero.
Print Assumptions committed_comm_costs_exactly_one.
Print Assumptions trigger_side_does_not_change_cost.
Print Assumptions join_arity_does_not_multiply_cost.
Print Assumptions comm_trace_cost_is_comm_count.
Print Assumptions comm_trace_cost_permutation_invariant.
Print Assumptions replaying_same_comm_trace_has_same_cost.
Print Assumptions rejected_comm_is_atomic.
Print Assumptions funded_comm_debits_before_commit.
Print Assumptions rejected_event_is_state_atomic.
Print Assumptions admitted_event_debits_exactly.
Print Assumptions debit_preserves_unselected_purse.
Print Assumptions explicit_regions_do_not_debit_ambient_purse.
Print Assumptions debit_conserves_each_purse.
Print Assumptions admitted_settlement_conserves.
Print Assumptions plan_permutation_preserves_authority.
Print Assumptions replay_preserves_authority.
Print Assumptions replay_preserves_purse_debit.
Print Assumptions captured_snapshot_is_valid.
Print Assumptions root_mismatch_rejects.
Print Assumptions proposer_mismatch_rejects.
Print Assumptions stale_balance_rejects.
Print Assumptions replay_runtime_snapshot_rejects.
Print Assumptions late_snapshot_rejects.
Print Assumptions replay_capture_refines_play.
Print Assumptions successful_replay_settles_actual_fuel.
Print Assumptions selected_play_prefix_replays.
Print Assumptions replay_consumes_exact_certificate_prefix.
Print Assumptions independent_replay_sessions_do_not_share_cursor.
Print Assumptions exact_depletion_replay_example.
Print Assumptions continuation_requires_outer_event.
Print Assumptions cross_deploy_slot_identity_is_replay_stable.
Print Assumptions full_guilty_confiscation_is_rejected.
Print Assumptions burned_redemption_conserves_canonical_rev.
Print Assumptions burned_redemption_removes_circulating_claims.
Print Assumptions failed_evaluation_publishes_nothing.
Print Assumptions unauthorized_generation_is_effect_free.
Print Assumptions full_guilty_penalty_is_effect_free.
Print Assumptions exact_retry_is_idempotent.
Print Assumptions conflicting_retry_is_effect_free.
Print Assumptions vindication_restores_exact_phase.
Print Assumptions guilty_restores_exact_phase.
Print Assumptions resolution_conserves_canonical_rev.
Print Assumptions resolution_preserves_physical_custody.
Print Assumptions distinct_validator_resolutions_commute.
Print Assumptions redemption_preserves_mint_ledger.
Print Assumptions redemption_preserves_vault_balance.
Print Assumptions redemption_removes_only_the_target_halt.
Print Assumptions redemption_cannot_remint_recorded_epoch.
Print Assumptions redemption_enables_exactly_one_fresh_epoch_credit.
Print Assumptions redemption_fresh_epoch_replay_is_idempotent.
Print Assumptions atomic_join_debits_all_or_none.
Print Assumptions bound_authority_is_excluded_from_static_capacity.
Print Assumptions resolved_authority_is_static.
Print Assumptions runtime_resolution_eliminates_bound_levels.
Print Assumptions physically_admissible_prevents_double_capacity.
Print Assumptions physical_settlement_conserves.
Print Assumptions physical_draw_is_permutation_invariant.
Print Assumptions stack_settlement_preserves_authority.
Print Assumptions physical_alias_does_not_merge_stack_authority.
Print Assumptions per_lane_capacity_can_double_count_one_physical_purse.
Print Assumptions new_bound_slot_becomes_the_persisted_continuation_authority.
Print Assumptions replay_preserves_the_resolved_slot_identity.
Print Assumptions deterministic_parallel_reduction_end_to_end.
Print Assumptions persistent_path_append_projection.
Print Assumptions persistent_child_path_projection.
Print Assumptions persistent_path_append_allocates_one_node.
Print Assumptions persistent_path_order_refines_sequence_order.
Print Assumptions equal_path_projections_preserve_all_comparisons.
Print Assumptions reserve_success_is_conserving.
Print Assumptions settlement_requires_complete_reservation.
Print Assumptions settlement_is_conserving_and_refunds_exactly.
Print Assumptions mint_is_the_only_supply_growth.
Print Assumptions independent_credit_is_unbacked.
Print Assumptions lollipop_reservation_is_all_or_nothing.
Print Assumptions lollipop_insufficient_continuation_payer_rejects_atomically.
Print Assumptions native_apply_refines_reserve_then_settle.
Print Assumptions native_apply_success_is_visible_and_conserving.
Print Assumptions native_apply_insufficient_bound_has_no_result.
Print Assumptions native_apply_rejects_realized_over_bound.
Print Assumptions aggregate_native_apply_is_order_independent.
Print Assumptions aggregate_native_apply_rejects_overdraw.
Print Assumptions complete_funding_implies_protocol_only_funding.
Print Assumptions migrated_recovery_fixture_complete_boundary.
Print Assumptions pre_state_materialized_before_snapshot.
Print Assumptions next_snapshot_pre_state_is_materialized.
Print Assumptions all_snapshots_use_ordinary_runtime.
Print Assumptions accepted_post_state_is_exact.
Print Assumptions independent_validator_replay_agrees.
Print Assumptions eager_second_snapshot_is_not_materialized_by_genesis.
Print Assumptions replay_runtime_is_not_an_ordinary_snapshot_source.
Print Assumptions outer_address_is_canonical.
Print Assumptions slot_address_is_canonical.
Print Assumptions located_addresses_are_injective.
Print Assumptions public_addresses_are_not_draw_capabilities.
Print Assumptions public_address_alone_never_authorizes_draw.
Print Assumptions retained_slot_capability_authorizes_draw.
Print Assumptions funding_success_is_exact.
Print Assumptions funding_success_is_conserving.
Print Assumptions funding_success_is_not_minting.
Print Assumptions insufficient_sponsor_rejects_both_purses_atomically.
Print Assumptions continuation_activation_requires_prior_funding.
Print Assumptions continuation_activation_requires_gateway_authentication.
Print Assumptions continuation_activation_requires_outer_authority.
Print Assumptions fully_authorized_continuation_activates.
Print Assumptions settlement_requires_prior_funding.
Print Assumptions settlement_requires_gateway_authentication.
Print Assumptions settlement_requires_outer_authority.
Print Assumptions settlement_requires_retained_slot_capability.
Print Assumptions insufficient_outer_purse_rejects_atomically.
Print Assumptions insufficient_slot_purse_rejects_atomically.
Print Assumptions outer_realized_over_bound_rejects_atomically.
Print Assumptions slot_realized_over_bound_rejects_atomically.
Print Assumptions insufficient_gateway_fee_rejects_atomically.
Print Assumptions settlement_success_is_component_exact.
Print Assumptions settlement_success_refunds_both_unused_bounds.
Print Assumptions settlement_success_is_conserving.
Print Assumptions wallet_funding_then_lollipop_is_conserving.
Print Assumptions wallet_funding_then_lollipop_is_component_exact.
Print Assumptions replay_uses_identical_staged_settlement.
Print Assumptions unresolved_templates_fail_closed.
Print Assumptions complete_templates_compile.
Print Assumptions authenticated_install_binds_pos_generator.
Print Assumptions unauthorized_transfer_is_effect_free.
Print Assumptions authenticated_transfer_moves_exactly_one.
Print Assumptions transfer_conserves_custody.
Print Assumptions literal_placeholder_denies_the_authenticated_generator.
Print Assumptions candidate_stack_does_not_inflate_creator_preflight_capacity.
Print Assumptions certification_execution_replay_share_authenticated_environment.
Print Assumptions empty_certification_environment_diverges_on_deployer_identity.
Print Assumptions worklist_solutions_refine_recursive.
Print Assumptions worklist_first_preserves_canonical_candidate_order.
Print Assumptions worklist_success_is_recursive_success.
Print Assumptions worklist_failure_is_recursive_failure.
Print Assumptions storage_preserves_complete_payload.
Print Assumptions free_capture_preserves_complete_payload.
Print Assumptions execution_preserves_complete_payload.
Print Assumptions replay_preserves_complete_payload.
Print Assumptions free_capture_preserves_authority.
Print Assumptions free_capture_preserves_stack_order.
Print Assumptions free_capture_preserves_conditionals.
Print Assumptions settlement_pop_is_event_visible.
Print Assumptions replay_reproduces_settlement_removal.
Print Assumptions same_linear_instance_conflicts.
Print Assumptions distinct_linear_instances_do_not_conflict.
Print Assumptions soft_checkpoint_returns_current_segment.
Print Assumptions soft_checkpoint_clears_active_segment.
Print Assumptions consecutive_soft_checkpoints_are_disjoint.
Print Assumptions checkpoint_segments_reconstruct_execution_trace.
Print Assumptions settlement_extends_trace_prefix.
Print Assumptions realized_authority_never_exceeds_structural_demand.
Print Assumptions runtime_unit_has_zero_demand.
Print Assumptions runtime_unit_is_left_neutral.
Print Assumptions runtime_unit_is_right_neutral.
Print Assumptions concurrent_scope_entry_is_order_independent.
Print Assumptions first_scope_exit_preserves_other_owner_a.
Print Assumptions first_scope_exit_preserves_other_owner_b.
Print Assumptions final_scope_exit_deactivates_accounting.
Print Assumptions duplicate_stack_transfer_is_rejected_atomically.
Print Assumptions underfunded_stack_transfer_is_rejected_atomically.
Print Assumptions funded_fresh_stack_transfer_is_exact.
Print Assumptions funded_stack_transfer_conserves.
Print Assumptions funded_stack_transfer_produces_every_debited_cell.
Print Assumptions funded_stack_transfer_records_one_fresh_event.
Print Assumptions stack_transfer_is_all_or_none.
Print Assumptions replay_stack_transfer_is_identical.
Print Assumptions authorized_mint_is_the_only_supply_increase.
Print Assumptions initial_credit_iff_genesis_allocation.
Print Assumptions fresh_bond_no_protocol_credit.
Print Assumptions rebond_no_protocol_credit.
Print Assumptions successful_fresh_bond_starts_generation_zero.
Print Assumptions successful_rebond_increments_generation_once.
Print Assumptions bond_transition_has_no_issuance_arbitrage.
Print Assumptions activation_does_not_credit.
Print Assumptions epoch_credit_requires_boundary.
Print Assumptions epoch_credit_requires_active.
Print Assumptions epoch_credit_requires_not_halted.
Print Assumptions epoch_credit_exactly_epoch_phlogiston.
Print Assumptions ordinary_epoch_preserves_generation.
Print Assumptions duplicate_epoch_issuance_is_effect_free.
Print Assumptions withdrawal_does_not_credit.
Print Assumptions withdrawal_settlement_conserves_custody.
Print Assumptions slash_does_not_credit.
Print Assumptions genesis_plus_epoch_issuance_is_exact.
Print Assumptions play_replay_issuance_deterministic.
Print Assumptions failed_epoch_close_is_identity.
Print Assumptions failed_close_preserves_balances.
Print Assumptions failed_close_preserves_receipts.
Print Assumptions failed_close_preserves_rewards.
Print Assumptions failed_close_preserves_withdrawals.
Print Assumptions failed_close_preserves_active_set.
Print Assumptions stage_one_success.
Print Assumptions stage_batch_all_success.
Print Assumptions credit_success_balance.
Print Assumptions all_success_total_balance.
Print Assumptions credit_success_completes.
Print Assumptions all_success_completes.
Print Assumptions successful_close_credits_each_eligible_exactly_once.
Print Assumptions commit_requires_all_eligible_mints.
Print Assumptions authorized_supply_delta_is_exact.
Print Assumptions zero_epoch_issuance_is_completed_noop.
Print Assumptions ineligible_validator_is_unchanged.
Print Assumptions at_most_one_credit_per_validator_epoch.
Print Assumptions disjoint_validator_mints_commute.
Print Assumptions failed_retry_from_same_prestate_is_deterministic.
Print Assumptions play_replay_epoch_close_agree.
Print Assumptions epoch_zero_bootstrap_advances.
Print Assumptions epoch_one_bootstrap_advances.
Print Assumptions later_unminted_epoch_is_a_gap.
Print Assumptions completed_epoch_is_a_noop_decision.
Print Assumptions immediate_successor_advances.
Print Assumptions skipped_successor_is_a_gap.
Print Assumptions accepted_advance_is_monotonic.
Print Assumptions accepted_advance_has_no_gap.
Print Assumptions frontier_gap_rejects_without_state_change.
Print Assumptions failed_batch_preserves_frontier_and_state.
Print Assumptions successful_batch_advances_exactly_once.
Print Assumptions zero_issuance_advances_after_complete_batch.
Print Assumptions completed_epoch_preserves_frontier.
Print Assumptions restart_preserves_frontier.
Print Assumptions lifecycle_update_preserves_frontier.
Print Assumptions sibling_selection_keeps_one_complete_state.
Print Assumptions sibling_selection_never_composes_frontiers.
Print Assumptions frontier_storage_is_constant.
Print Assumptions play_replay_frontier_agreement.
Print Assumptions certified_partition_is_complete.
Print Assumptions certified_partition_is_pairwise_disjoint.
Print Assumptions certified_classes_preserve_canonical_order.
Print Assumptions certified_root_chain_matches_admitted_order.
Print Assumptions canonical_window_uses_raw_user_prefix.
Print Assumptions publication_uses_one_certified_generation.
Print Assumptions failed_checkpoint_publishes_nothing.
Print Assumptions failed_checkpoint_settles_nothing.
Print Assumptions failed_checkpoint_drains_nothing.
Print Assumptions deferred_candidates_are_not_terminal.
Print Assumptions retry_step_strictly_decreases.
Print Assumptions retry_relation_is_well_founded.
Print Assumptions preparation_is_capacity_conserving_and_invisible.
Print Assumptions byte_rejection_after_preparation_restores_exact_state.
Print Assumptions commit_after_visible_produce_is_complete_and_conserving.
Print Assumptions preparation_cannot_oversubscribe_capacity.
Print Assumptions abort_preserves_unrelated_commit.
Print Assumptions enclosing_deploy_failure_restores_linear_capacity.
Print Assumptions enclosing_deploy_failure_preserves_attempted_byte_cost.
Print Assumptions every_matched_produce_is_causally_extracted.
Print Assumptions matched_produces_precede_their_comm.
Print Assumptions parser_failure_cannot_reuse_prior_witness.
Print Assumptions reducer_failure_retains_exact_attempted_work.
Print Assumptions rejected_play_restores_its_base_state.
Print Assumptions rejected_replay_restores_its_base_state.
Print Assumptions rejected_replay_discards_its_prevalidation_checkpoint.
Print Assumptions rollback_preserves_attempted_work.
Print Assumptions rejected_replay_publishes_no_mergeable_evidence.
Print Assumptions accepted_replay_publishes_mergeable_evidence.
Print Assumptions published_mergeable_evidence_requires_final_state_match.
Print Assumptions complete_key_is_injective.
Print Assumptions distinct_pre_states_have_distinct_keys.
Print Assumptions distinct_post_states_have_distinct_keys.
Print Assumptions distinct_creators_have_distinct_keys.
Print Assumptions distinct_sequences_have_distinct_keys.
Print Assumptions distinct_payloads_have_distinct_keys.
Print Assumptions legacy_key_alias_witness.
Print Assumptions local_replay_publishes_exact_evidence.
Print Assumptions peer_response_cannot_publish_evidence.
Print Assumptions peer_response_cannot_overwrite_local_replay.
Print Assumptions distinct_replays_preserve_both_entries.
Print Assumptions distinct_insertions_commute_pointwise.
Print Assumptions opposite_arrival_orders_agree_on_every_lookup.
Print Assumptions complete_key_deletion_removes_exact_execution.
Print Assumptions complete_key_deletion_preserves_distinct_execution.
Print Assumptions deletion_after_distinct_replays_preserves_survivor.
Print Assumptions deletion_is_idempotent.
Print Assumptions deletion_commutes_with_distinct_insertion_pointwise.
Print Assumptions retirement_requires_concrete_latest_witness.
Print Assumptions retirement_requires_every_safety_guard.
Print Assumptions vacuous_latest_guard_is_unsafe.
Print Assumptions full_dag_retirement_accepts_every_parent_path.
Print Assumptions main_spine_only_retirement_is_incomplete.
Print Assumptions initial_materialization_conserves.
Print Assumptions parent_reduction_requires_materialized_initial_purse.
Print Assumptions parent_reduction_conserves.
Print Assumptions nested_materialization_requires_parent_commit.
Print Assumptions nested_materialization_conserves.
Print Assumptions premature_parent_reduction_is_rejected.
Print Assumptions premature_nested_materialization_is_rejected.
Print Assumptions phased_evaluation_reaches_exact_state.
Print Assumptions reducer_scheduling_preference_is_irrelevant.
Print Assumptions phased_evaluation_conserves.
Print Assumptions replay_reproduces_materialization_and_reduction.
Print Assumptions authenticated_capacity_append_monotone.
Print Assumptions positive_backing_strictly_expands_capacity.
Print Assumptions authenticated_prefix_is_bounded_by_total.
Print Assumptions frontier_retry_count_is_finite.
Print Assumptions speculative_exhaustion_does_not_publish_state.
Print Assumptions discovered_backing_conserves_total_supply.
Print Assumptions candidate_created_supply_cannot_expand_prestate_capacity.
Print Assumptions replay_uses_the_same_authenticated_capacity.
Print Assumptions admitted_trace_fits_budget.
Print Assumptions introduction_consumes_no_comm_execution_unit.
Print Assumptions communication_consumes_one_execution_unit.
Print Assumptions communication_execution_unit_is_independent_of_join_arity.
Print Assumptions trigger_side_does_not_change_byte_debit.
Print Assumptions trigger_arrival_order_does_not_change_total_debit.
Print Assumptions join_transfer_includes_every_participant.
Print Assumptions adding_join_participant_adds_exact_transfer_cost.
Print Assumptions stable_persistent_identity_is_charged_once_across_retries.
Print Assumptions nonpersistent_identity_preserves_attempt_multiplicity.
Print Assumptions v1_debit_is_canonical_encoded_footprint.
Print Assumptions trace_debit_is_product_sum.
Print Assumptions trace_debit_permutation_invariant.
Print Assumptions persistent_introduction_is_charged_once_and_each_delivery_is_charged.
Print Assumptions peek_neither_charges_nor_refunds.
Print Assumptions rejected_byte_event_is_atomic.
Print Assumptions run_byte_trace_acceptance_is_exact.
Print Assumptions run_byte_trace_preserves_hard_ceiling.
Print Assumptions accepted_permutations_have_identical_settlement.
Print Assumptions replay_byte_trace_accepts_iff_exact.
Print Assumptions replay_acceptance_binds_event_kind_and_amount.
Print Assumptions replay_rejects_changed_event_kind.
Print Assumptions top_up_is_a_conserving_transfer.
Print Assumptions top_up_commutes_with_running_settlement.
Print Assumptions top_up_does_not_expand_inflight_reservation.
Print Assumptions empty_registry_resolves_to_deploy_payer.
Print Assumptions fallback_resolution_is_atomically_pinned.
Print Assumptions registered_resolution_returns_the_committed_payer.
Print Assumptions fallback_pin_rejects_a_late_conflicting_registration.
Print Assumptions inserted_introduction_authority_is_stable.
Print Assumptions same_payer_registration_is_idempotent.
Print Assumptions conflicting_registration_is_rejected_without_overwrite.
Print Assumptions deploy_reset_discards_every_registered_introduction_authority.
Print Assumptions authority_neutral_stack_keeps_storage_neutral_and_charges_sponsor.
Print Assumptions lollipop_receiver_introduction_charges_outer_not_continuation.
Print Assumptions continuation_created_introduction_charges_continuation.
Print Assumptions stored_interaction_authority_cannot_redirect_introduction_charge.
Print Assumptions unmetered_introduction_has_no_authority_debit.
Print Assumptions candidate_created_stack_cannot_supply_prestate_byte_capacity.
Print Assumptions single_cell_authority_settlement_matches_processed_trace.
Print Assumptions byte_trace_settlement_conserves_rev.
Print Assumptions byte_trace_refines_single_comm_execution.
Print Assumptions admitted_witness_is_funded.
Print Assumptions left_branch_fits_reservation.
Print Assumptions pointwise_funded_realized_is_funded.
Print Assumptions left_branch_fits_pointwise_max.
Print Assumptions pointwise_settlement_conserves.
Print Assumptions pointwise_refund_is_unused_reservation.
Print Assumptions exact_settlement_conserves.
Print Assumptions local_fault_never_slashes.
Print Assumptions validation_origin_independent.
Print Assumptions every_origin_replays_checkpoint_and_checks_bonds.
Print Assumptions finality_parent_permutation_invariant.
Print Assumptions genesis_allocation_total_permutation.
Print Assumptions permutation_genesis_replay_agrees.
Print Assumptions genesis_replay_agreement_preserves_admission.
Print Assumptions duplicate_genesis_allocations_combine.
Print Assumptions genesis_system_vault_funding_is_exact.
Print Assumptions committed_genesis_system_vault_funding_is_idempotent.
Print Assumptions genesis_system_vault_replay_agrees.
Print Assumptions admission_requires_verified_genesis.
Print Assumptions genesis_unit_execution_replay_agrees.
Print Assumptions genesis_unit_execution_rejects_funder_replay.
Print Assumptions capacity_exactly_characterizes_funding.
Print Assumptions exhausted_execution_cannot_be_certified.
Print Assumptions state_bound_certificate_funds_committed_cost.
Print Assumptions state_bound_chain_preserves_adjacent_roots.
Print Assumptions admitted_costs_are_funded.
Print Assumptions state_bound_exact_settlement_conserves.
Print Assumptions cost_accounted_calculus_is_gslt_with_oslf_logic.
Print Assumptions oslf_spatial_modal_logic_sound.
Print Assumptions sig_monoid_comm.
Print Assumptions sig_monoid_assoc.
Print Assumptions sig_monoid_unit_l.
Print Assumptions sig_monoid_unit_r.
Print Assumptions tok_concat_assoc.
Print Assumptions tok_concat_unit_r.
Print Assumptions token_size_concat.
Print Assumptions tok_concat_not_commutative.
Print Assumptions continuation_seal_is_cost_irrelevant.
Print Assumptions rule45_result_cost_independent_of_seal.
Print Assumptions subject_reduction_wrapping.
Print Assumptions no_leak_requires_token.
Print Assumptions admission_sig_algebra_valid_sound.
Print Assumptions admission_sig_algebra_scalar_policy_sound.
Print Assumptions admission_sig_algebra_quorum_sound.
(* DR-25: untyped-lambda R1-only cost instance (CAUntypedLambda + CAUntypedLambdaCI) *)
Print Assumptions lca_only_beta_r1.
Print Assumptions lca_contact_requires_token.
Print Assumptions lca_stack_inert.
Print Assumptions lca_funded_nonredex_stuck.
Print Assumptions lca_step_needs_fuel.
Print Assumptions lca_step_decreases.
Print Assumptions lca_funded_run_bounded.
Print Assumptions lca_well_founded.
Print Assumptions lca_SN_funded.
Print Assumptions omega_pure_diverges.
Print Assumptions lca_omega_funded_one_step.
Print Assumptions lca_omega_funded_halts.
Print Assumptions lca_beta_r1_erasure.
Print Assumptions lca_graded_step_sound.
Print Assumptions lca_step_gradable.
Print Assumptions Lambda_ciGSLT_nonvacuous.
Print Assumptions no_leak_stack_inert.
Print Assumptions gap2_split_combined_keeps_own_seal.
Print Assumptions gap2_split_split_keeps_own_seal.
Print Assumptions st_token_count_subst_invariant.
Print Assumptions ca_step_needs_fuel.
Print Assumptions funded_step_decreases.
Print Assumptions closed_deref_zero_ca.
Print Assumptions deref_subst_closed_ca.
Print Assumptions linear_subst_many_fuel_le.
Print Assumptions extract_sends_join_sends.
Print Assumptions signed_sends_injective.
Print Assumptions signed_sends_fuel.
Print Assumptions ca_step_join2_det.
Print Assumptions ca_SN_funded.
Print Assumptions st_total_fuel_can_increase_off_funded.
Print Assumptions ca_local_confluence.
Print Assumptions ca_step_rule1_det.
Print Assumptions ca_step_deterministic.
Print Assumptions single_token_path_unique.
Print Assumptions newman_funded.
Print Assumptions ca_cost_deterministic_funded.
Print Assumptions funded_run_bounded.
Print Assumptions continued_gslt_cost_capstone.
Print Assumptions graded_step_sound.
Print Assumptions graded_step_complete.
Print Assumptions graded_iff_step.
Print Assumptions gdia_complete.
Print Assumptions N_tr_closed.
Print Assumptions T_tr_closed.
Print Assumptions cost_map_id.
Print Assumptions cost_map_compose.
Print Assumptions cost_left_unit.
Print Assumptions cost_right_unit.
Print Assumptions cost_assoc.
Print Assumptions cost_eta_natural.
Print Assumptions cost_mu_natural.
Print Assumptions cost_monad_not_idempotent.
Print Assumptions lift_st_to_proc.
Print Assumptions subst_st_to_proc.
Print Assumptions lift_lift_comm.
Print Assumptions lift_subst_ca.
Print Assumptions lift_lift_compose_proc.
Print Assumptions lift_proc_S_compose.
Print Assumptions lift_lift_comm_proc.
Print Assumptions Nt_lift_inv.
Print Assumptions Nt_subst_inv.
Print Assumptions Tt_lift_inv.
Print Assumptions Tt_subst_inv.
Print Assumptions trd_bridge.
Print Assumptions st_trd_zero.
Print Assumptions rule1_reachable.
Print Assumptions rule2_reachable.
Print Assumptions rule5_reachable.
Print Assumptions Split_closed.
Print Assumptions Split_fires.
Print Assumptions rho_reachable_par_l.
Print Assumptions rule3_reachable.
Print Assumptions rule4_reachable.
Print Assumptions ca_translation_progresses.
Print Assumptions ca_single_gate_bisimilar.
Print Assumptions ca_funded_reachable_monotone.
Print Assumptions ca_post_evaluation_settlement_no_mint.
Print Assumptions mint_inject_st_not_ca_step.
Print Assumptions ca_admin_fuel_classified.
Print Assumptions exchange_preserves_stack_identity_and_order.
Print Assumptions exchange_preserves_resource_multiset.
Print Assumptions exchange_preserves_resource_cell_count.
Print Assumptions exchange_resource_join_requires_both.
Print Assumptions exchange_resource_join_one_sided_is_inert.
Print Assumptions ca_exchange_total_conserved.
Print Assumptions ca_exchange_preserves_stack_identity_and_order.
Print Assumptions ca_exchange_preserves_resource_cell_count.
Print Assumptions ca_exchange_is_step_not_mint.
Print Assumptions ca_economic_conservation.
Print Assumptions local_sufficiency_composes.
Print Assumptions draw_disjoint.
Print Assumptions graded_adequacy_sound.
Print Assumptions cost_forget_install.
Print Assumptions cost_install_forget_alters.
Print Assumptions ca_linear_no_contraction.
Print Assumptions ca_lolly_consumes_input.
Print Assumptions graded_image_finite.
Print Assumptions graded_image_finite_pairs.
Print Assumptions graded_dichotomy.
Print Assumptions graded_finitary_adequacy.
Print Assumptions ca_internalisation_retraction.
Print Assumptions ca_eta_is_weak_bisim_section.
Print Assumptions graded_limit_adequacy.
Print Assumptions graded_bisim_refines_approximants.
Print Assumptions graded_bisim_implies_hml.
Print Assumptions graded_bisim_n_monotone.
Print Assumptions graded_coinductive_completeness_modulo.
Print Assumptions graded_coinductive_hml_completeness_modulo.
Print Assumptions gated_translation_stuck.
Print Assumptions ca_force_overgating_separation.
Print Assumptions ca_force_overgating_nonvacuous.
Print Assumptions join_authority_conserved.
Print Assumptions join_key_atoms_perm.
Print Assumptions join_authority_conserved_operational.
Print Assumptions reverse_curry_iso.
Print Assumptions join_demand_partition_invariant.
Print Assumptions join_no_weakening.
Print Assumptions rho_object_nonvacuous.
Print Assumptions graded_bisim_trans.
Print Assumptions cost_is_endofunctor.
Print Assumptions cost_obj_closure.
Print Assumptions CostCI.
Print Assumptions cost_ci_preserves_bisim.
Print Assumptions cost_ci_preserves_step.
Print Assumptions cost_ci_preserves_quote_faithful.
Print Assumptions cost_is_monad.
Print Assumptions cost_monad_instance.
Print Assumptions free_forget_adjunction.
Print Assumptions cost_kleisli_adjunction.
Print Assumptions proper_subcategory.
Print Assumptions U_not_eso.
Print Assumptions sim_2cells_form_setoid.
Print Assumptions internalisation_adjoint_retraction.
Print Assumptions internalisation_retraction_param.
Print Assumptions rho_internalisable.
Print Assumptions rho_internalises_by_interpreter.
Print Assumptions continued_gslt_cost_abstract_capstone.
Print Assumptions consumed_fuel_count_eq_token_drop.
Print Assumptions consumed_comm_count_determined_by_endpoints.
Print Assumptions mint_inject_not_ca_step.
Print Assumptions user_ca_step_does_not_mint.
Print Assumptions admin_trans_mint_adds_exactly.
Print Assumptions system_vault_credit_injective_in_pk.
Print Assumptions system_vault_credit_names_distinct.
Print Assumptions epoch_mint_idempotent_on_balance.
Print Assumptions user_ca_step_does_not_increase_balance.
Print Assumptions halted_validator_supply_not_increased.
Print Assumptions halted_validator_not_minted.
Print Assumptions credit_implies_not_halted.
Print Assumptions translation_faithful.
Print Assumptions translation_strong_bisimilar_generic.
Print Assumptions compound_gate_per_step_reverse.
Print Assumptions backward_reflection_phased_gate.
Print Assumptions well_reflected_backward_reflection.
Print Assumptions recursively_metered_backward_reflection.
Print Assumptions preplicate_bang_encoding_body_barbs_sound.
Print Assumptions replication_encoding_forward_barb_sound.
Print Assumptions debit_plus_refund_eq_reservation.
Print Assumptions post_evaluation_settlement_no_mint.
Print Assumptions slash_preserves_fee_settlement_inputs.
Print Assumptions slash_preserves_settled_amount.
Print Assumptions slash_after_evaluation_cannot_add_fuel.
Print Assumptions cost_invalid_block_evidence_does_not_change_user_cost.
Print Assumptions slash_system_effect_is_unmetered_for_user_budget.
Print Assumptions current_cost_evidence_epoch_sound.
Print Assumptions parent_pre_state_authorizes_current_cost_evidence.
Print Assumptions parent_pre_state_authorization_requires_parent_bond.
Print Assumptions ambient_bond_does_not_authorize_without_parent_pre_state.
Print Assumptions canonical_slash_candidate_requires_current_cost_evidence.
Print Assumptions stale_canonical_slash_candidate_not_authorized.
Print Assumptions missing_evidence_cannot_select_canonical_slash_candidate.
Print Assumptions parent_pre_state_authorized_slash_preserves_cost_boundary.
Print Assumptions zero_bond_slash_noop_preserves_cost_boundary.
Print Assumptions slash_two_effect_is_unmetered_for_user_budget.
Print Assumptions redeem_system_effect_is_unmetered_for_user_budget.
Print Assumptions redeem_preserves_fee_settlement_inputs.
Print Assumptions redeem_conserving_effect_preserves_tracked_funds.
Print Assumptions slash_two_effect_preserves_user_cost_observables.
Print Assumptions bitmask_diff_merge_round_trip.
Print Assumptions mergeable_channel_bitmask_fold_permutation.
Print Assumptions integer_add_diff_merge_round_trip.
Print Assumptions mergeable_channel_delta_preserves_type.
Print Assumptions non_numeric_channel_not_mergeable_payload_match.
Print Assumptions mergeable_channel_accounting_preserves_user_budget.
Print Assumptions mergeable_channel_accounting_preserves_fee_settlement_inputs.
Print Assumptions integer_diff_total_permutation.
Print Assumptions integer_total_result_permutation.
Print Assumptions integer_selection_application_agree.
Print Assumptions widened_total_ignores_invalid_prefix_when_final_result_fits.
Print Assumptions rb_total_remaining_conservation.
Print Assumptions rb_reserve_oop_commits_limit.
Print Assumptions rb_reserve_first_oop_commits_boundary.
Print Assumptions rb_reserve_many_conservation.
Print Assumptions rb_reserve_many_oop_count_le_one.
Print Assumptions rb_reserve_many_unmetered_no_cost.
Print Assumptions rb_replay_payload_user_trace_change_detected.
Print Assumptions rb_replay_payload_system_trace_change_detected.
Print Assumptions rb_replay_payload_canonical_user_trace_permutation.
Print Assumptions rb_full_replay_payload_signature_change_detected.
Print Assumptions rb_full_replay_payload_system_kind_change_detected.
Print Assumptions rb_full_replay_payload_genesis_change_detected.
Print Assumptions rb_diagnostic_cap_preserves_budget_observables.
Print Assumptions rb_finalize_trace_window_preserves_budget_observables.
Print Assumptions rb_cost_trace_change_detected.
Print Assumptions rb_cost_trace_event_count_success_and_oop.
Print Assumptions rb_post_activation_cost_trace_present_matches_count.
Print Assumptions rb_post_activation_cost_trace_commitment_valid.
Print Assumptions rb_empty_cost_trace_commitment_can_be_valid.
Print Assumptions rb_diagnostic_refinement_requires_commitment.
Print Assumptions rb_legacy_replay_accepts_absent_commitment.
Print Assumptions rb_oop_trace_survives_boundary.
Print Assumptions rb_oversized_weight_rejection_preserves_trace.
Print Assumptions rb_zero_weight_admission_rejection_preserves_trace.
Print Assumptions rb_oversized_weight_admission_rejection_preserves_trace.
Print Assumptions rb_oversized_source_path_admission_rejection_preserves_trace.
Print Assumptions rb_oversized_primitive_descriptor_admission_rejection_preserves_trace.
Print Assumptions rb_admitted_success_has_admissible_event.
Print Assumptions rb_admitted_success_has_positive_bounded_weight.
Print Assumptions rb_trace_cap_rejection_preserves_trace.
Print Assumptions rb_repeated_oop_boundary_frontier.
Print Assumptions rb_repeated_oop_preserves_first_boundary.
Print Assumptions rb_trace_cap_frontier_preserves_budget_and_trace.
Print Assumptions rb_multi_deploy_settlement_frontier.
Print Assumptions rb_nonbillable_frame_preserves_trace.
Print Assumptions rb_block_auth_payload_replay_payload_change_detected.
Print Assumptions rb_replay_cache_key_payload_change_detected.
Print Assumptions rb_replay_cache_key_binds_runtime_context.
Print Assumptions rb_replay_cache_context_substitution_rejected.
Print Assumptions rb_digest_cache_key_refines_complete_key.
Print Assumptions validation_step_preserves_invariant.
Print Assumptions retained_execution_has_no_second_user_evaluation.
Print Assumptions discovery_attempts_can_exceed_retained_results.
Print Assumptions parallel_validation_preserves_each_worker_invariant.
Print Assumptions parallel_validation_retains_one_successful_result.
Print Assumptions cancellation_preserves_other_validation_workers.
Print Assumptions rb_full_replay_payload_user_cost_change_detected.
Print Assumptions rb_full_replay_payload_user_cost_trace_change_detected.
Print Assumptions rb_full_replay_payload_user_cost_trace_event_count_change_detected.
Print Assumptions rb_full_replay_payload_user_cost_trace_present_change_detected.
Print Assumptions rb_full_replay_payload_missing_cost_trace_change_detected.
Print Assumptions rb_full_replay_payload_user_failed_change_detected.
Print Assumptions rb_full_replay_payload_user_error_change_detected.
Print Assumptions rb_full_replay_payload_system_error_change_detected.
Print Assumptions rb_full_replay_payload_slash_fields_change_detected.
Print Assumptions rb_full_replay_payload_slash_target_epoch_change_detected.
Print Assumptions rb_sum_settlement_app.
Print Assumptions low_deploy_price_violation_sound.
Print Assumptions low_deploy_price_violation_complete.
Print Assumptions unauthorized_fee_settlement_sound.
Print Assumptions unauthorized_budget_mutation_sound.
Print Assumptions stale_cost_evidence_sound.
Print Assumptions stale_cost_evidence_complete.
Print Assumptions rb_trace_entry_kind_domain_separated.
Print Assumptions rb_trace_entry_deploy_change_detected.
Print Assumptions rb_trace_entry_source_path_change_detected.
Print Assumptions rb_trace_entry_redex_change_detected.
Print Assumptions rb_trace_entry_local_index_change_detected.
Print Assumptions rb_trace_entry_billable_kind_change_detected.
Print Assumptions rb_trace_entry_primitive_descriptor_change_detected.
Print Assumptions rb_trace_entry_weight_change_detected.
Print Assumptions rb_trace_duplicate_multiplicity_detected.
Print Assumptions rb_diagnostic_refinement_rejects_absent_commitment.
Print Assumptions rb_reset_from_token_retention_bound_zero.
Print Assumptions rb_unmetered_reserve_preserves_trace.
Print Assumptions rb_meter_identity_unmetered_reserve_many_preserves_state.
Print Assumptions rb_meter_identity_unmetered_child_many_preserves_state.
Print Assumptions rb_meter_identity_metered_reserve_uses_next_identity.
Print Assumptions rb_meter_identity_scoped_unmetered_work_preserves_next_metered_identity.
Print Assumptions rb_meter_identity_scoped_unmetered_children_preserve_next_metered_identity.
Print Assumptions uc_ca_001_budget_conservation.
Print Assumptions uc_ca_002_weighted_event_refines_unit_token_expansion.
Print Assumptions uc_ca_004_parallel_terminal_cost_determinism.
Print Assumptions uc_ca_005_well_reflected_replay_step_sound.
Print Assumptions uc_ca_009_debit_plus_refund_equals_reservation.
Print Assumptions uc_ca_010_replay_cost_mismatch_sound.
Print Assumptions uc_ca_012_slashing_preserves_settlement_accounting.
Print Assumptions uc_ca_013_runtime_budget_conserves_consumed_remaining.
Print Assumptions uc_ca_014_weighted_runtime_event_refines_unit_count.
Print Assumptions uc_ca_018_replay_payload_user_trace_change_detected.
Print Assumptions uc_ca_019_replay_payload_system_trace_change_detected.
Print Assumptions uc_ca_020_replay_payload_user_trace_permutation_equiv.
Print Assumptions uc_ca_021_replay_payload_system_trace_permutation_equiv.
Print Assumptions uc_ca_022_replay_payload_signature_change_detected.
Print Assumptions uc_ca_023_replay_payload_system_kind_change_detected.
Print Assumptions uc_ca_024_reservation_batch_preserves_budget_conservation.
Print Assumptions uc_ca_025_reservation_batch_has_at_most_one_oop.
Print Assumptions uc_ca_026_unmetered_batch_no_cost.
Print Assumptions uc_ca_027_settlement_exhaustion_and_fee_only.
Print Assumptions uc_ca_028_slashing_after_evaluation_cannot_add_fuel.
Print Assumptions uc_ca_029_diagnostic_log_cap_preserves_budget_observables.
Print Assumptions uc_ca_030_replay_payload_genesis_change_detected.
Print Assumptions uc_ca_031_finalization_reads_completed_cost_trace.
Print Assumptions uc_ca_032_cost_trace_canonicalization_and_sensitivity.
Print Assumptions uc_ca_033_replay_payload_full_field_sensitivity.
Print Assumptions uc_ca_034_multi_deploy_budget_isolation_and_settlement_sum.
Print Assumptions uc_ca_035_unmetered_system_mode_restoration.
Print Assumptions uc_ca_036_diagnostic_retention_is_non_consensus.
Print Assumptions uc_ca_037_trace_mismatch_preserves_settlement_accounting.
Print Assumptions uc_ca_038_legacy_metering_quarantine.
Print Assumptions uc_ca_039_post_activation_cost_trace_required.
Print Assumptions uc_ca_040_full_replay_payload_authenticates_cost_trace_fields.
Print Assumptions uc_ca_041_concurrent_finalization_trace_completeness.
Print Assumptions uc_ca_042_oop_trace_survives_failed_deploy_boundary.
Print Assumptions uc_ca_043_matched_unmatched_deploy_trace_and_settlement_isolation.
Print Assumptions uc_ca_044_oversized_weight_rejection_preserves_trace.
Print Assumptions uc_ca_045_nonbillable_frames_do_not_enter_cost_trace.
Print Assumptions uc_ca_046_zero_event_post_activation_trace_commitment.
Print Assumptions uc_ca_047_block_authenticates_cost_trace_payload.
Print Assumptions uc_ca_048_replay_cache_key_authenticates_cost_trace_payload.
Print Assumptions uc_ca_049_legacy_replay_quarantines_absent_cost_trace.
Print Assumptions uc_ca_050_billable_reservation_enters_cost_trace.
Print Assumptions uc_ca_051_parallel_trace_and_cost_determinism.
Print Assumptions uc_ca_052_cost_trace_mismatch_slashing_boundary.
Print Assumptions uc_ca_053_cost_trace_domain_separation_and_multiplicity.
Print Assumptions uc_ca_054_activation_replay_rejects_absent_commitment.
Print Assumptions uc_ca_055_unauthorized_settlement_and_budget_mutation_are_cost_invalid.
Print Assumptions uc_ca_056_low_deploy_price_is_cost_invalid_evidence.
Print Assumptions uc_ca_057_stale_cost_invalid_evidence_is_rejected.
Print Assumptions uc_ca_058_refund_cannot_replenish_runtime_fuel.
Print Assumptions uc_ca_059_deterministic_billable_descriptor_sensitivity.
Print Assumptions uc_ca_060_reset_clears_retained_trace_after_finalization.
Print Assumptions uc_ca_061_system_mode_cannot_leak_into_user_metering.
Print Assumptions uc_ca_062_block_validation_authenticates_cost_fields.
Print Assumptions uc_ca_063_threaded_oop_boundary_ownership.
Print Assumptions uc_ca_064_external_nondeterminism_requires_replay_evidence.
Print Assumptions uc_ca_065_zero_weight_billable_event_rejected.
Print Assumptions uc_ca_066_oversized_billable_event_rejected.
Print Assumptions uc_ca_067_trace_cap_rejection_preserves_budget.
Print Assumptions uc_ca_068_admitted_success_has_positive_bounded_weight.
Print Assumptions uc_ca_069_producer_routing_search_frontier.
Print Assumptions uc_ca_070_trace_slot_linearizability_frontier.
Print Assumptions uc_ca_071_replay_mutation_frontier.
Print Assumptions uc_ca_072_multi_deploy_settlement_frontier.
Print Assumptions uc_ca_073_slashing_composition_frontier.
Print Assumptions uc_ca_074_resource_exhaustion_frontier.
Print Assumptions uc_ca_141_typed_mergeable_channel_type_preservation.
Print Assumptions uc_ca_142_bitmask_or_diff_merge_round_trip.
Print Assumptions uc_ca_143_bitmask_or_fold_order_independent.
Print Assumptions uc_ca_144_integer_add_diff_merge_round_trip.
Print Assumptions uc_ca_145_mergeable_channel_accounting_preserves_cost_boundary.
Print Assumptions uc_ca_146_canonical_slash_candidate_requires_current_evidence.
Print Assumptions uc_ca_147_parent_pre_state_slash_authorization_preserves_cost_boundary.
Print Assumptions uc_ca_148_slash_target_epoch_is_replay_authenticated.
Print Assumptions uc_ca_149_zero_bond_slash_noop_preserves_cost_boundary.
Print Assumptions pos_map_currentdeploys_invariant.
Print Assumptions pos_refund_no_cross_attribution.
Print Assumptions pos_precharge_failure_atomic.
Print Assumptions fifo_drain_conservation.
Print Assumptions ll_tensor_min_required_matches_runtime.
Print Assumptions ll_threshold_min_required_matches_runtime.
Print Assumptions ll_plus_left_min_required_matches_runtime.
Print Assumptions ll_plus_right_min_required_matches_runtime.
Print Assumptions ll_with_min_required_matches_runtime.
Print Assumptions ll_bang_min_required_matches_runtime.
Print Assumptions ll_whynot_min_required_matches_runtime.
Print Assumptions ll_lolly_min_required_matches_runtime.
Print Assumptions ll_all_required_uses_all_atoms.
Print Assumptions ll_threshold_validity_bounds_runtime_quorum.
Print Assumptions ll_sig_algebra_required_complete.
Print Assumptions ll_sig_algebra_consumed_matches_presented.
Print Assumptions ll_sig_algebra_threshold_valid_bounds_bridge.
Print Assumptions dill_linear_identity.
Print Assumptions dill_tensor_combines_linear_contexts.
Print Assumptions dill_unrestricted_claim_uses_no_linear_witness.
Print Assumptions dill_lolly_modus_ponens_consumes_input_context.
Print Assumptions dill_whynot_intro_uses_no_linear_witness.
Print Assumptions ll_plus_left_consumes_chosen_branch.
Print Assumptions ll_plus_right_consumes_chosen_branch.
Print Assumptions ll_with_requires_both_branches_available.
Print Assumptions ll_bang_reuse_no_extra_linear_cost.
Print Assumptions ll_whynot_consumes_no_linear_witness.
Print Assumptions ll_lolly_resource_flow_conservative.
Print Assumptions ll_threshold_quorum_sound.
Print Assumptions ll_linear_no_contraction.
Print Assumptions ll_linear_no_weakening.
Print Assumptions ll_linear_atom_contraction_changes_count.
Print Assumptions ll_consume_linear_once_atom_exhausts.
Print Assumptions ll_no_double_spend_single_witness.
Print Assumptions ll_double_spend_requires_duplicate_witness.
Print Assumptions ll_unrestricted_reuse_preserves_context.
Print Assumptions ll_unrestricted_can_be_reused.
Print Assumptions ll_linear_cut_consumes_cut_witness.
Print Assumptions ll_unrestricted_cut_preserves_linear_zone.
Print Assumptions exact_spend_check_sound_complete.
Print Assumptions exact_linear_check_sound.
Print Assumptions exact_linear_check_complete.
Print Assumptions linear_forbids_contraction.
Print Assumptions linear_forbids_weakening.
Print Assumptions modal_poststate_is_exact.
Print Assumptions modal_spend_preserves_other_surface.
Print Assumptions located_observation_isolates_other_surface.
Print Assumptions spatial_is_commutative.
Print Assumptions spatial_local_sufficiency_composes.
Print Assumptions conservative_sufficiency_is_sound.
Print Assumptions upper_bound_cannot_assert_modal_spend.
Print Assumptions upper_bound_insufficient_supply_rejects.
Print Assumptions authenticated_supply_excludes_candidate_credit.
Print Assumptions core_demand_invariant_under_extension.
Print Assumptions extension_demand_ge_core.
Print Assumptions delta_s_tensor_additive.
Print Assumptions compound_demand_splits_to_components.
Print Assumptions funding_decidable.
Print Assumptions sigma_s_balance_eq_stack_count.
Print Assumptions funding_check_balance_sound.
Print Assumptions funding_check_balance_sound_against_stack.
Print Assumptions strict_reject_when_underfunded.
Print Assumptions strict_absent_pool_rejects_positive_demand.
Print Assumptions competing_funding_at_most_one_succeeds.
Print Assumptions admit_prefix_maximal.
Print Assumptions reject_both_sound.
Print Assumptions reject_both_from_first_overshoot.
Print Assumptions settlement_conserves.
Print Assumptions accept_commit_conserves.
Print Assumptions compound_split_debit_conserves.
Print Assumptions compound_split_debit_no_underflow.
Print Assumptions multi_settlement_conserves.
Print Assumptions compound_debit_is_block_settlement_instance.
Print Assumptions fee_transfer_conserves.
Print Assumptions fee_recipient_credit_eq_client_debit.
Print Assumptions fee_transfer_zero_is_noop.
Print Assumptions native_fee_credit_is_backed.
Print Assumptions native_fee_transfer_conserves_holding.
Print Assumptions native_fee_transfer_zero_is_noop.
Print Assumptions exchange_conserves_per_channel.
Print Assumptions exchange_total_conserved.
Print Assumptions exchange_requires_both_inputs.
Print Assumptions exchange_is_ca_step_not_amint.
Print Assumptions exchange_mints_nothing.
Print Assumptions sig_free_names_quote.
Print Assumptions sse_par_unit.
Print Assumptions token_decomp.
Print Assumptions uniform_sugar_translation_equiv.
Print Assumptions lollipop_sugar_translation_equiv.
Print Assumptions system_vault_name_injective.
Print Assumptions domain_name_injective.
Print Assumptions system_vault_quarantine_domain_disjoint.
Print Assumptions system_vault_funding_slot_domain_disjoint.
Print Assumptions quarantine_funding_slot_domain_disjoint.
Print Assumptions lane_pool_disjoint.
Print Assumptions lane_key_not_app_channel.
Print Assumptions rb_pool_total_cost_eq_sum.
Print Assumptions rb_lane_reconcile_preserves_valid.
Print Assumptions rb_pool_reconcile_preserves_valid.
Print Assumptions rb_pool_total_cost_permutation_invariant.
Print Assumptions rb_pool_reconciled_total_cost_permutation_invariant.
Print Assumptions rb_pool_singleton_eq_scalar.
Print Assumptions rb_pool_total_cost_metered_eq_consumed_sum.
(* item 2494 / 2505 — the i64-bounded ledger: over/underflow are MODELED
   (conserved OR deterministically rejected), the nat model is the in-range
   restriction, no existing guarantee weakened. *)
Print Assumptions checked_add_i64_conserved_or_rejected.
Print Assumptions checked_add_i64_never_wraps.
Print Assumptions checked_add_i64_none_iff_overflow.
Print Assumptions checked_add_i64_some_in_range.
Print Assumptions checked_sub_nonneg_conserved_or_rejected.
Print Assumptions checked_add_i64_matches_nat.
Print Assumptions vault_credit_conserved_or_rejected.
Print Assumptions bounded_settlement_conserved_or_rejected.
Print Assumptions bounded_fee_transfer_conserved_or_rejected.
(* item 2509 — consensus-core vs diagnostic-only split of the full replay payload. *)
Print Assumptions rb_full_replay_payload_equiv_split.
Print Assumptions rb_full_replay_payload_equiv_implies_consensus.
Print Assumptions rb_full_replay_payload_consensus_coarser_than_full.
From CostAccountedRho Require Import BlockHeapLifecycle.
Print Assumptions positive_interval_counter_is_bounded.
Print Assumptions trim_is_requested_exactly_at_the_boundary.
Print Assumptions every_block_default_reclaims_retained_heap.
Print Assumptions block_reclamation_is_semantically_invisible.
Print Assumptions reclamation_choice_does_not_change_semantic_commits.
Print Assumptions safe_finish_preserves_retained_counter_bound.
Print Assumptions default_boundary_bounds_resident_heap.
Print Assumptions missing_boundary_reclamation_exceeds_two_slot_envelope.
From CostAccountedRho Require Import MultiShardConcurrency.
Print Assumptions foreign_action_trace_preserves_protected_shard.
Print Assumptions action_trace_preserves_per_shard_conservation.
Print Assumptions action_trace_preserves_per_shard_root_alignment.
Print Assumptions distinct_shard_actions_commute_pointwise.
Print Assumptions admitted_serial_commits_have_no_lost_updates.
Print Assumptions admitted_serial_commits_preserve_conservation.
Print Assumptions shared_worker_capstone.
From CostAccountedRho Require Import FundingSlotBootstrap.
Print Assumptions scaffold_install_is_conserving.
Print Assumptions eager_located_install_rejects_new_zero_purses.
Print Assumptions staged_scaffold_install_needs_no_candidate_purse_supply.
Print Assumptions dual_purse_funding_is_exact_and_conserving.
Print Assumptions insufficient_dual_purse_funding_is_atomic.
Print Assumptions rejected_dual_purse_funding_preserves_registry.
Print Assumptions accepted_dual_purse_funding_creates_both_vaults.
Print Assumptions eager_target_creation_breaks_rejection_atomicity.
Print Assumptions slot_only_funding_cannot_satisfy_positive_outer_bound.
Print Assumptions dual_funding_establishes_local_sufficiency.
Print Assumptions activation_requires_gateway_authentication.
Print Assumptions activation_requires_both_located_purses.
Print Assumptions activated_lollipop_settlement_is_exact_and_conserving.
Print Assumptions witnesses_are_exactly_selected.
Print Assumptions every_witness_is_a_policy_member.
Print Assumptions funding_is_exact_selected_projection.
Print Assumptions unsigned_policy_member_is_not_funded.
Print Assumptions native_and_ethereum_schemes_share_ground_authority.
Print Assumptions policy_rejects_duplicate_ground_owner.
Print Assumptions different_presence_changes_commitment_preimage.
Print Assumptions equal_commitment_preimage_has_equal_authority_projection.
Print Assumptions accepted_threshold_meets_quorum.
Print Assumptions verified_partition_covers_every_candidate.
Print Assumptions verified_partition_has_no_dual_disposition.
Print Assumptions processed_evidence_is_exactly_admitted.
Print Assumptions count_equality_does_not_establish_identity_equality.
Print Assumptions primary_signature_identity_is_not_injective.
Print Assumptions absent_publication_inserts_complete_evidence.
Print Assumptions identical_publication_is_idempotent.
Print Assumptions conflicting_publication_preserves_existing_store.
Print Assumptions peer_bytes_leave_store_unchanged.
Print Assumptions durable_proof_precedes_cache_entry.
Print Assumptions crash_exposes_before_or_after_transaction.
Print Assumptions validators_with_equal_artifacts_publish_equal_evidence.
Quit.
EOF
then
  echo "error: failed to query headline theorem assumptions" >&2
  sed -n '1,160p' "$assumptions" >&2
  exit 1
fi

# Validator behavioral contract (Workstream E, stage E5): assert every
# validator_contract_* clause is axiom-free. Each clause is a re-export of an
# already-axiom-free obligation (S1-S4 from CostAccountedRho, P1/P2 from
# Slashing), so it inherits "Closed under the global context". Append to the
# SAME assumptions file so the closed-count invariant below covers these
# Print Assumptions lines too (the $0 grep counts them).
if ! rocq repl -Q "$THEORIES" CostAccountedRho \
               -Q "$SLASHING_ROOT/theories" Slashing \
               -Q "$VALIDATOR_THEORIES" Validator >> "$assumptions" 2>&1 <<'EOF'
From Validator Require Import Contract.
Print Assumptions validator_contract_S1.
Print Assumptions validator_contract_S2.
Print Assumptions validator_contract_S3.
Print Assumptions validator_contract_S4.
Print Assumptions validator_contract_P1.
Print Assumptions validator_contract_P1_epoch_advance.
Print Assumptions validator_contract_P1_effect.
Print Assumptions validator_contract_P2.
Print Assumptions validator_contract_P3.
Quit.
EOF
then
  echo "error: failed to query validator contract assumptions" >&2
  sed -n '1,160p' "$assumptions" >&2
  exit 1
fi

# Slashing development headline theorems (#14 StageC formal hardening). The
# slashing tree was compiled above (validator-contract dependency) but not
# axiom-gated. Print Assumptions its headline results — the MainTheorem.v
# composition (T-1..T-12 + T-9.x, incl. the top-level
# main_slashing_algorithm_correct), the ValidatorRedemption.v redemption set
# (incl. redeem_burned_stays_halted, the spec's TERMINAL-Burned anchor: a burned
# validator stays halted, faithful to "minting contingent on good behaviour",
# cost-accounted-rho.tex l.2368-2369 / l.3108-3109), and the un-composed
# BugFixAtomicBufferDagTransition.v T-9.20. Appended to the SAME $assumptions
# file so the closed-count invariant below counts them. The in-tree hygiene scan
# above rejects Admitted/Axiom in the slashing sources; these Print Assumptions
# additionally reject any IMPORTED (library) axiom the regex cannot see.
if ! rocq repl -Q "$SLASHING_ROOT/theories" Slashing >> "$assumptions" 2>&1 <<'EOF'
From Slashing Require Import MainTheorem ValidatorRedemption BugFixAtomicBufferDagTransition.
Print Assumptions main_T1_detection_sound.
Print Assumptions main_T2_detection_complete.
Print Assumptions main_T3_slashable_taxonomy.
Print Assumptions main_T4_record_monotone.
Print Assumptions main_T5_record_unique.
Print Assumptions main_T7_slash_zeros_bond.
Print Assumptions main_T9_slash_idempotent.
Print Assumptions main_TIdem_zero_bond_noop.
Print Assumptions main_T10_fork_choice_exclusion.
Print Assumptions main_T9_1_ignorable.
Print Assumptions main_T9_2_atomic.
Print Assumptions main_T9_3_dispatch.
Print Assumptions main_T9_3_block_exception_is_local_fault.
Print Assumptions main_T9_4_transfer.
Print Assumptions main_T9_5_stake_zero.
Print Assumptions main_T9_6_self_regression.
Print Assumptions main_T9_7_seqnum_density.
Print Assumptions main_T9_7_seqnum_density_dense_subsumption.
Print Assumptions main_T9_7_seqnum_density_same_branch_stability.
Print Assumptions main_T9_7_seqnum_density_memoized_equivalent.
Print Assumptions main_T9_8_unbonded.
Print Assumptions main_T9_9_self_correcting.
Print Assumptions main_T9_10_withdraw_transfer_failure.
Print Assumptions main_T9_10_failure_preserves_total_funds.
Print Assumptions main_T9_10_withdraw_independence.
Print Assumptions main_T9_12_stale_generation_evidence_not_authorized.
Print Assumptions main_T9_12_epoch_advance_preserves_lifetime.
Print Assumptions main_T9_13_unknown_slash_evidence_noop.
Print Assumptions main_T9_13_zero_canonical_bond_not_authorized.
Print Assumptions main_T9_13_matching_lifetime_current_window_authorized.
Print Assumptions main_T9_13_canonical_pre_state_authorizes_when_ambient_differs.
Print Assumptions main_T9_13_canonical_zero_rejects_even_if_ambient_positive.
Print Assumptions main_T9_13_proposer_receiver_authorization_parity.
Print Assumptions main_T9_13_same_pre_state_root_same_authorization.
Print Assumptions main_T9_13_merge_rejected_hint_subsumed_by_authorized_scan.
Print Assumptions main_T9_13_zero_bond_candidate_not_selected.
Print Assumptions main_T9_13_selected_target_keys_nodup.
Print Assumptions main_TAuth_invalid_token_noop.
Print Assumptions main_TAuth_valid_token_equiv.
Print Assumptions main_TSlash_seed_input_hash_injective.
Print Assumptions main_TSlash_deploy_seed_uses_invalid_block_hash.
Print Assumptions main_T9_14_checked_pred_positive.
Print Assumptions main_T9_15_duplicate_justifications_rejected.
Print Assumptions main_T12_bft_quorum.
Print Assumptions main_T12_closure_depth_bound.
Print Assumptions main_T12_evidence_monotone.
Print Assumptions main_T12_no_seed_empty_closure.
Print Assumptions main_T12_reports_do_not_suppress_direct.
Print Assumptions main_T12_unreported_visible_edge_remains_active.
Print Assumptions main_T12_report_growth_antitone.
Print Assumptions main_T12_view_merge_overapproximates_left.
Print Assumptions main_T12_view_merge_overapproximates_right.
Print Assumptions main_T12_view_merge_commutative.
Print Assumptions main_T12_validator_renaming_equiv.
Print Assumptions main_T9_11_detector_traversal_fuel_bound.
Print Assumptions main_T9_11_detector_branch_traversal_fixed_bound.
Print Assumptions main_T12_temporal_retention_boundary.
Print Assumptions main_T12_temporal_retention_under_window.
Print Assumptions main_T9_2_n_threads.
Print Assumptions main_T4_record_lifecycle_retains_hash.
Print Assumptions main_T9_6_dag.
Print Assumptions main_T6_detect_neglected_sound.
Print Assumptions main_T6_detect_neglected_complete.
Print Assumptions main_slashing_algorithm_correct.
Print Assumptions redeem_vindicated_restores.
Print Assumptions redeem_guilty_redistributes.
Print Assumptions redeem_full_guilty_rejected.
Print Assumptions redeem_burned_conserves.
Print Assumptions redeem_burned_stays_halted.
Print Assumptions redeem_requires_quarantine.
Print Assumptions redeem_authorized_only.
Print Assumptions slash_then_redeem_conserves_total.
Print Assumptions slash_then_redeem_burned_reduces_total_by_bond.
Print Assumptions redeem_other_unchanged.
Print Assumptions t_9_20_recon.
Print Assumptions t_9_20_reconcile_idempotent.
Print Assumptions t_9_20_step_idempotent_on_projection.
Quit.
EOF
then
  echo "error: failed to query slashing development assumptions" >&2
  sed -n '1,200p' "$assumptions" >&2
  exit 1
fi

closed_count="$( (rg -o 'Closed under the global context' "$assumptions" || true) | wc -l | tr -d ' ')"
expected_closed_count="$(rg -c '^[[:space:]]*Print Assumptions ' "$0")"
if [ "$closed_count" -ne "$expected_closed_count" ]; then
  echo "error: headline theorems have unexpected assumptions" >&2
  sed -n '/Print Assumptions/,$p' "$assumptions" >&2
  exit 1
fi

echo "Proof hygiene check passed."
