#!/usr/bin/env bash
# scripts/check-cost-accounted-rho-tla-invariants.sh
#
# Local-only TLA+ invariant runner for the cost_accounted_rho specs.
# Per team policy (memory `feedback_formal_verification_is_local_only_not_ci`),
# formal verification stays local — this script is NOT a CI step.
#
# Runs TLC against every safe .cfg under formal/tlaplus/cost_accounted_rho/
# whose paired .tla module exists, then checks each registered unsafe control
# for its exact expected invariant violation. Every TLC run goes through the shared
# scripts/lib/tlc-run.sh launcher, which enforces a strict memory envelope
# (on-disk metadir — NOT tmpfs; bounded -Xmx heap; bounded workers; and a
# hard systemd-run MemoryMax / MemorySwapMax=0 ceiling) so a single large
# model can't exhaust RAM. Tune via TLC_HEAP / TLC_WORKERS / TLC_RSS /
# TLC_METADIR_ROOT (see the helper header).
#
# Each run is reported as PASS / FAIL based on the TLC output. Exit code 0 iff
# every safe spec reports no errors and every unsafe control reports its named
# counterexample.
#
# Usage:
#   bash scripts/check-cost-accounted-rho-tla-invariants.sh
#   bash scripts/check-cost-accounted-rho-tla-invariants.sh --filter MC

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TLA_DIR="$REPO_ROOT/formal/tlaplus/cost_accounted_rho"

FILTER="${1:-}"
if [[ "$FILTER" == "--filter" ]]; then
    shift
    FILTER="${1:-}"
    shift || true
fi

if [[ ! -d "$TLA_DIR" ]]; then
    echo "ERROR: TLA+ cost_accounted_rho directory not found at $TLA_DIR" >&2
    exit 2
fi

if ! command -v tlc >/dev/null 2>&1; then
    echo "ERROR: tlc binary not on PATH; install tlaplus tooling" >&2
    exit 2
fi

# Shared memory-bounded TLC launcher: on-disk metadir, capped -Xmx heap,
# capped workers, hard systemd MemoryMax ceiling. See scripts/lib/tlc-run.sh.
export TLC_REPO_ROOT="$REPO_ROOT"
source "$REPO_ROOT/scripts/lib/tlc-run.sh"

cd "$TLA_DIR"

# Some protocol .cfg files were authored for use ONLY through their
# MC wrapper module (they reference MC_-prefixed identifiers that
# only resolve when the MC*.tla module is the spec root). The MC
# wrappers have non-trivial naming (e.g., CompoundProtocol.cfg is
# wrapped by MCCompound.tla, NOT MCCompoundProtocol.tla). This
# explicit map records which protocol .cfgs depend on which wrapper.
# The mapping is used to invoke TLC as:
#   tlc -config <base>.cfg <wrapper>.tla
declare -A WRAPPED_BY
WRAPPED_BY[NativeReplayExport]=NativeReplayExport
WRAPPED_BY[NativeReplayAuthority]=MCNativeReplayAuthority
WRAPPED_BY[NativeOperationBudgetOrderForged]=NativeOperationBudgetOrder
WRAPPED_BY[FundedPrepaidSettlementZero]=FundedPrepaidSettlement
WRAPPED_BY[JointFundingSettlementZeroResource]=JointFundingSettlement
WRAPPED_BY[FamilyCursorSettlementUnrestricted]=FamilyCursorSettlement
WRAPPED_BY[AtomicTrieUpsertNil]=AtomicTrieUpsert
WRAPPED_BY[CompoundProtocol]=MCCompound
WRAPPED_BY[CompoundSettlement]=MCCompoundSettlement
WRAPPED_BY[CostAccountedRho]=MC
WRAPPED_BY[CostAccountingSearchFrontier]=MCCostAccountingSearchFrontier
WRAPPED_BY[CostAccountingThreats]=MCCostAccountingThreats
WRAPPED_BY[EvalScheduling]=MCEval
# #13b: focused strict reject-when-absent instance (PoolSupply = 0).
WRAPPED_BY[EvalStrictAbsent]=MCEvalStrictAbsent
WRAPPED_BY[FullProtocol]=MCFull
WRAPPED_BY[MergeableChannelAccounting]=MCMergeableChannelAccounting
WRAPPED_BY[RuntimeBudgetReplay]=MCRuntimeBudgetReplay
WRAPPED_BY[EndToEndCostConsensus]=MCEndToEndCostConsensus
WRAPPED_BY[DeployTraceSegmentation]=MCDeployTraceSegmentation
WRAPPED_BY[ReplaySupplySnapshot]=MCReplaySupplySnapshot
WRAPPED_BY[MergeAggregateAgreement]=MCMergeAggregateAgreement
WRAPPED_BY[StateBoundAdmission]=MCStateBoundAdmission
WRAPPED_BY[StateBoundValidatorConvergence]=MCStateBoundValidatorConvergence
WRAPPED_BY[LocatedAuthoritySettlement]=MCLocatedAuthoritySettlement
WRAPPED_BY[CapacityBoundedTrace]=MCCapacityBoundedTrace
WRAPPED_BY[LocatedStackConservationCollision]=LocatedStackConservation
WRAPPED_BY[StateBoundFrontierExpansion]=MCStateBoundFrontierExpansion
WRAPPED_BY[VaultBackedCostLifecycle]=MCVaultBackedCostLifecycle
WRAPPED_BY[AtomicVaultSettlementRefinement]=MCAtomicVaultSettlementRefinement
WRAPPED_BY[FeeObligationBoundaryConservationOnly]=FeeObligationBoundary
WRAPPED_BY[WalletFundedLollipop]=MCWalletFundedLollipop
WRAPPED_BY[FundingSlotBootstrap]=MCFundingSlotBootstrap
WRAPPED_BY[IntroductionAuthorityRegistry]=MCIntroductionAuthorityRegistry
WRAPPED_BY[MultiShardResourceIsolationCrash]=MultiShardResourceIsolation
WRAPPED_BY[CanonicalCustodyAliasing]=MCCanonicalCustodyAliasing
WRAPPED_BY[BondIssuanceLifecycle]=MC_BondIssuanceLifecycle
WRAPPED_BY[EpochMintAtomicity]=MC_EpochMintAtomicity
WRAPPED_BY[EpochMintAtomicityZero]=MC_EpochMintAtomicity
WRAPPED_BY[ValidatorEconomicsLifecycle]=MC_ValidatorEconomicsLifecycle
# MAJOR-5: the token-gated-join sequential-fuel griefing / atomicity obligation.
# TokenGatedJoin.cfg is the NATIVE-model safety suite (must HOLD). The companion
# TokenGatedJoinM2Grief.cfg is an EXPECTED-REFUTATION run (it confirms the griefing
# vector for the TRANSPILER runtime-gate model by producing a counterexample), so
# it is deliberately NOT registered here — a counterexample is its intended result,
# not a pass. Run it explicitly: tlc -config TokenGatedJoinM2Grief.cfg MCTokenGatedJoin.tla
WRAPPED_BY[TokenGatedJoin]=MCTokenGatedJoin

declare -A EXPECTED_REFUTATION_WRAPPER
declare -A EXPECTED_REFUTATION_INVARIANT
EXPECTED_REFUTATION_WRAPPER[NativeReplayAuthorityDebitUnsafe]=MCNativeReplayAuthority
EXPECTED_REFUTATION_INVARIANT[NativeReplayAuthorityDebitUnsafe]=ExactAuthority
EXPECTED_REFUTATION_WRAPPER[NativeReplayAuthorityRestoreUnsafe]=MCNativeReplayAuthority
EXPECTED_REFUTATION_INVARIANT[NativeReplayAuthorityRestoreUnsafe]=ExactAuthority
EXPECTED_REFUTATION_WRAPPER[NativeReplayAuthorityPendingUnsafe]=MCNativeReplayAuthority
EXPECTED_REFUTATION_INVARIANT[NativeReplayAuthorityPendingUnsafe]=NoOverdraw
EXPECTED_REFUTATION_WRAPPER[NativeReplayExportIncompleteUnsafe]=NativeReplayExport
EXPECTED_REFUTATION_WRAPPER[CheckpointLocalHandoffPublishUnsafe]=CheckpointLocalHandoff
EXPECTED_REFUTATION_INVARIANT[CheckpointLocalHandoffPublishUnsafe]=FailedSnapshotPreserved
EXPECTED_REFUTATION_WRAPPER[CheckpointLocalHandoffDrainUnsafe]=CheckpointLocalHandoff
EXPECTED_REFUTATION_INVARIANT[CheckpointLocalHandoffDrainUnsafe]=FailedSnapshotPreserved
EXPECTED_REFUTATION_WRAPPER[NativeSettlementRootsOriginalUnsafe]=NativeSettlementRoots
EXPECTED_REFUTATION_INVARIANT[NativeSettlementRootsOriginalUnsafe]=IndependentSettlementEnabled
EXPECTED_REFUTATION_WRAPPER[NativeSettlementRootsRecaptureUnsafe]=NativeSettlementRoots
EXPECTED_REFUTATION_INVARIANT[NativeSettlementRootsRecaptureUnsafe]=OriginalFundingPreserved
EXPECTED_REFUTATION_WRAPPER[NativeSettlementRootsForeignRuntimeUnsafe]=NativeSettlementRoots
EXPECTED_REFUTATION_INVARIANT[NativeSettlementRootsForeignRuntimeUnsafe]=ExactAcceptedRuntime
EXPECTED_REFUTATION_WRAPPER[NativeSettlementRootsForeignFundingUnsafe]=NativeSettlementRoots
EXPECTED_REFUTATION_INVARIANT[NativeSettlementRootsForeignFundingUnsafe]=ExactAcceptedFunding
EXPECTED_REFUTATION_INVARIANT[NativeReplayExportIncompleteUnsafe]=CompleteEvidence
EXPECTED_REFUTATION_WRAPPER[NativeReplayExportReleaseUnsafe]=NativeReplayExport
EXPECTED_REFUTATION_INVARIANT[NativeReplayExportReleaseUnsafe]=CapturedAgreement
EXPECTED_REFUTATION_WRAPPER[NativeReplayExportDurabilityUnsafe]=NativeReplayExport
EXPECTED_REFUTATION_INVARIANT[NativeReplayExportDurabilityUnsafe]=DurableExport
EXPECTED_REFUTATION_WRAPPER[NativeReplayExportReuseUnsafe]=NativeReplayExport
EXPECTED_REFUTATION_INVARIANT[NativeReplayExportReuseUnsafe]=ExactlyOnce
EXPECTED_REFUTATION_WRAPPER[NativeReplayAccountingStageUnsafe]=NativeReplayAccounting
EXPECTED_REFUTATION_INVARIANT[NativeReplayAccountingStageUnsafe]=StageCoverage
EXPECTED_REFUTATION_WRAPPER[NativeReplayAccountingRepeatUnsafe]=NativeReplayAccounting
EXPECTED_REFUTATION_INVARIANT[NativeReplayAccountingRepeatUnsafe]=StageCoverage
EXPECTED_REFUTATION_WRAPPER[NativeReplayAccountingRetryUnsafe]=NativeReplayAccounting
EXPECTED_REFUTATION_INVARIANT[NativeReplayAccountingRetryUnsafe]=ExactUsage
EXPECTED_REFUTATION_WRAPPER[NativeReplayAccountingUndoUnsafe]=NativeReplayAccounting
EXPECTED_REFUTATION_INVARIANT[NativeReplayAccountingUndoUnsafe]=UndoUsage
EXPECTED_REFUTATION_WRAPPER[NativeReplayAuthenticationFootprintUnsafe]=NativeReplayAuthentication
EXPECTED_REFUTATION_INVARIANT[NativeReplayAuthenticationFootprintUnsafe]=AuthenticatedFootprint
EXPECTED_REFUTATION_WRAPPER[NativeReplayAuthenticationSourceUnsafe]=NativeReplayAuthentication
EXPECTED_REFUTATION_INVARIANT[NativeReplayAuthenticationSourceUnsafe]=AuthenticatedComm
EXPECTED_REFUTATION_WRAPPER[NativeReplayReadinessLeaseUnsafe]=NativeReplayReadiness
EXPECTED_REFUTATION_INVARIANT[NativeReplayReadinessLeaseUnsafe]=QuiescentCaptureEnabled
EXPECTED_REFUTATION_WRAPPER[NativeReplayReadinessRestoreUnsafe]=NativeReplayReadiness
EXPECTED_REFUTATION_INVARIANT[NativeReplayReadinessRestoreUnsafe]=DependencySafety
EXPECTED_REFUTATION_WRAPPER[NativeReplayReadinessDirectUnsafe]=NativeReplayReadiness
EXPECTED_REFUTATION_INVARIANT[NativeReplayReadinessDirectUnsafe]=DependencySafety
EXPECTED_REFUTATION_WRAPPER[GenesisResourcePolicyLatestUnsafe]=GenesisResourcePolicy
EXPECTED_REFUTATION_INVARIANT[GenesisResourcePolicyLatestUnsafe]=GenesisAuthority
EXPECTED_REFUTATION_WRAPPER[GenesisResourcePolicyMixedMinimumUnsafe]=GenesisResourcePolicy
EXPECTED_REFUTATION_INVARIANT[GenesisResourcePolicyMixedMinimumUnsafe]=GenesisAuthority
EXPECTED_REFUTATION_WRAPPER[GenesisResourcePolicyRulesUnsafe]=GenesisResourcePolicy
EXPECTED_REFUTATION_INVARIANT[GenesisResourcePolicyRulesUnsafe]=SupportedInterpretation
EXPECTED_REFUTATION_WRAPPER[PrepaidStackMigrationEarlyUnsafe]=PrepaidStackMigration
EXPECTED_REFUTATION_INVARIANT[PrepaidStackMigrationEarlyUnsafe]=PublishedPhysicalBinding
EXPECTED_REFUTATION_WRAPPER[PrepaidStackMigrationTailUnsafe]=PrepaidStackMigration
EXPECTED_REFUTATION_INVARIANT[PrepaidStackMigrationTailUnsafe]=CommittedCellConservation
EXPECTED_REFUTATION_WRAPPER[PrepaidStackMigrationRollbackUnsafe]=PrepaidStackMigration
EXPECTED_REFUTATION_INVARIANT[PrepaidStackMigrationRollbackUnsafe]=FailedCandidateRestored
EXPECTED_REFUTATION_WRAPPER[FundedCandidateCheckpointEarlyUnsafe]=FundedCandidateCheckpoint
EXPECTED_REFUTATION_INVARIANT[FundedCandidateCheckpointEarlyUnsafe]=AtomicPublication
EXPECTED_REFUTATION_WRAPPER[FundedCandidateCheckpointRollbackUnsafe]=FundedCandidateCheckpoint
EXPECTED_REFUTATION_INVARIANT[FundedCandidateCheckpointRollbackUnsafe]=FailedCandidateRestored
EXPECTED_REFUTATION_WRAPPER[FundedCandidateCheckpointCancelUnsafe]=FundedCandidateCheckpoint
EXPECTED_REFUTATION_INVARIANT[FundedCandidateCheckpointCancelUnsafe]=ReadyCandidateClean
EXPECTED_REFUTATION_WRAPPER[FundedCandidateCheckpointReplayUnsafe]=FundedCandidateCheckpoint
EXPECTED_REFUTATION_INVARIANT[FundedCandidateCheckpointReplayUnsafe]=FreshReplayAttempt
EXPECTED_REFUTATION_WRAPPER[FundedPrepaidSettlementSkipUnsafe]=FundedPrepaidSettlement
EXPECTED_REFUTATION_INVARIANT[FundedPrepaidSettlementSkipUnsafe]=PublishedPrepaidBacking
EXPECTED_REFUTATION_WRAPPER[FundedPrepaidSettlementRollbackUnsafe]=FundedPrepaidSettlement
EXPECTED_REFUTATION_INVARIANT[FundedPrepaidSettlementRollbackUnsafe]=CompleteFailureRollback
EXPECTED_REFUTATION_WRAPPER[FundedPrepaidSettlementPlatformUnsafe]=FundedPrepaidSettlement
EXPECTED_REFUTATION_INVARIANT[FundedPrepaidSettlementPlatformUnsafe]=PlatformPreservesFunding
EXPECTED_REFUTATION_WRAPPER[NativePhloExecutionCeilingStaleUnsafe]=NativePhloExecutionCeiling
EXPECTED_REFUTATION_INVARIANT[NativePhloExecutionCeilingStaleUnsafe]=ExactAcceptedUsage
EXPECTED_REFUTATION_WRAPPER[NativePhloExecutionCeilingResetUnsafe]=NativePhloExecutionCeiling
EXPECTED_REFUTATION_INVARIANT[NativePhloExecutionCeilingResetUnsafe]=NoCrossGenerationWorker
EXPECTED_REFUTATION_WRAPPER[NativeAttemptReplayOmissionUnsafe]=NativeAttemptReplay
EXPECTED_REFUTATION_INVARIANT[NativeAttemptReplayOmissionUnsafe]=RecordedAttemptCoverage
EXPECTED_REFUTATION_WRAPPER[NativeAttemptReplayReorderUnsafe]=NativeAttemptReplay
EXPECTED_REFUTATION_INVARIANT[NativeAttemptReplayReorderUnsafe]=ReplayDecisionAgreement
EXPECTED_REFUTATION_WRAPPER[NativeAttemptConflictsReorderUnsafe]=NativeAttemptConflicts
EXPECTED_REFUTATION_INVARIANT[NativeAttemptConflictsReorderUnsafe]=ReplaySourcesAvailable
EXPECTED_REFUTATION_WRAPPER[NativeOperationLifecycleObserverUnsafe]=NativeOperationLifecycle
EXPECTED_REFUTATION_INVARIANT[NativeOperationLifecycleObserverUnsafe]=SingleObserver
EXPECTED_REFUTATION_WRAPPER[NativeOperationLifecycleCompletionUnsafe]=NativeOperationLifecycle
EXPECTED_REFUTATION_INVARIANT[NativeOperationLifecycleCompletionUnsafe]=CompletionPreservesResult
EXPECTED_REFUTATION_WRAPPER[NativeOperationEvidenceUnsafe]=NativeOperationEvidence
EXPECTED_REFUTATION_INVARIANT[NativeOperationEvidenceUnsafe]=RejectionHasDenial
EXPECTED_REFUTATION_WRAPPER[NativeIndexPublicationEarlyUnsafe]=NativeIndexPublication
EXPECTED_REFUTATION_INVARIANT[NativeIndexPublicationEarlyUnsafe]=PreparedBeforePublication
EXPECTED_REFUTATION_WRAPPER[NativeIndexPublicationFailureUnsafe]=NativeIndexPublication
EXPECTED_REFUTATION_INVARIANT[NativeIndexPublicationFailureUnsafe]=FailureStopsPublication
EXPECTED_REFUTATION_WRAPPER[NativeReplayDirectiveEarlyUnsafe]=NativeReplayDirective
EXPECTED_REFUTATION_INVARIANT[NativeReplayDirectiveEarlyUnsafe]=AuthenticatedPublication
EXPECTED_REFUTATION_WRAPPER[NativeReplayDirectiveMissingUnsafe]=NativeReplayDirective
EXPECTED_REFUTATION_INVARIANT[NativeReplayDirectiveMissingUnsafe]=ExactDenial
EXPECTED_REFUTATION_WRAPPER[NativeReplayLedgerCursorUnsafe]=NativeReplayLedger
EXPECTED_REFUTATION_INVARIANT[NativeReplayLedgerCursorUnsafe]=ExactRestore
EXPECTED_REFUTATION_WRAPPER[NativeReplayLedgerBusyUnsafe]=NativeReplayLedger
EXPECTED_REFUTATION_INVARIANT[NativeReplayLedgerBusyUnsafe]=LiveSnapshot
EXPECTED_REFUTATION_WRAPPER[NativeReplayLedgerOutcomeUnsafe]=NativeReplayLedger
EXPECTED_REFUTATION_INVARIANT[NativeReplayLedgerOutcomeUnsafe]=ExactOutcome
EXPECTED_REFUTATION_WRAPPER[NativeReplayCheckpointCaptureUnsafe]=NativeReplayCheckpoint
EXPECTED_REFUTATION_INVARIANT[NativeReplayCheckpointCaptureUnsafe]=StableSnapshots
EXPECTED_REFUTATION_WRAPPER[NativeReplayCheckpointStoreOnlyUnsafe]=NativeReplayCheckpoint
EXPECTED_REFUTATION_INVARIANT[NativeReplayCheckpointStoreOnlyUnsafe]=TupleLedgerAgreement
EXPECTED_REFUTATION_WRAPPER[NativeReplayCheckpointReleaseUnsafe]=NativeReplayCheckpoint
EXPECTED_REFUTATION_INVARIANT[NativeReplayCheckpointReleaseUnsafe]=TupleLedgerAgreement
EXPECTED_REFUTATION_WRAPPER[NativeReplayCheckpointPrepareUnsafe]=NativeReplayCheckpoint
EXPECTED_REFUTATION_INVARIANT[NativeReplayCheckpointPrepareUnsafe]=FailedPreparationPreservesState
EXPECTED_REFUTATION_WRAPPER[NativeReplayCheckpointCountersUnsafe]=NativeReplayCheckpoint
EXPECTED_REFUTATION_INVARIANT[NativeReplayCheckpointCountersUnsafe]=CounterAgreement
EXPECTED_REFUTATION_WRAPPER[NativeBudgetPublicationGenerationUnsafe]=NativeBudgetPublication
EXPECTED_REFUTATION_INVARIANT[NativeBudgetPublicationGenerationUnsafe]=CurrentGenerationOnly
EXPECTED_REFUTATION_WRAPPER[NativeBudgetPublicationRetryUnsafe]=NativeBudgetPublication
EXPECTED_REFUTATION_INVARIANT[NativeBudgetPublicationRetryUnsafe]=ReceiptUsage
EXPECTED_REFUTATION_WRAPPER[NativeBudgetPublicationCutUnsafe]=NativeBudgetPublication
EXPECTED_REFUTATION_INVARIANT[NativeBudgetPublicationCutUnsafe]=RetryCutFollowsAcceptance
EXPECTED_REFUTATION_WRAPPER[NativeBudgetCaptureUnsafe]=NativeBudgetCapture
EXPECTED_REFUTATION_INVARIANT[NativeBudgetCaptureUnsafe]=NoAbandonedExport
EXPECTED_REFUTATION_WRAPPER[NativeOperationBudgetOrderUnsafe]=NativeOperationBudgetOrder
EXPECTED_REFUTATION_INVARIANT[NativeOperationBudgetOrderUnsafe]=CausalBudgetOrder
EXPECTED_REFUTATION_WRAPPER[NativeOperationBudgetOrderForgedUnsafe]=NativeOperationBudgetOrder
EXPECTED_REFUTATION_INVARIANT[NativeOperationBudgetOrderForgedUnsafe]=CausalBudgetOrder
EXPECTED_REFUTATION_WRAPPER[NativeOperationBudgetOrderIndependentReachable]=NativeOperationBudgetOrder
EXPECTED_REFUTATION_INVARIANT[NativeOperationBudgetOrderIndependentReachable]=NoFixedRootOrder
EXPECTED_REFUTATION_WRAPPER[FundingSourceSnapshotLatestUnsafe]=FundingSourceSnapshot
EXPECTED_REFUTATION_INVARIANT[FundingSourceSnapshotLatestUnsafe]=FrozenReads
EXPECTED_REFUTATION_WRAPPER[FundingSourceSnapshotPartialUnsafe]=FundingSourceSnapshot
EXPECTED_REFUTATION_INVARIANT[FundingSourceSnapshotPartialUnsafe]=CompletePublished
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceStaleWalletUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceStaleWalletUnsafe]=NoWalletOverdraw
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceIgnoreCustodyUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceIgnoreCustodyUnsafe]=NoWalletOverdraw
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceHighestCeilingUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceHighestCeilingUnsafe]=ReservedPriceAuthorized
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceCurrentOwnerUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceCurrentOwnerUnsafe]=SettlementUsesCapturedConsent
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceConsentOnlyUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceConsentOnlyUnsafe]=Conservation
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceQuantityOnlyUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceQuantityOnlyUnsafe]=Conservation
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceStaleCapacityUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceStaleCapacityUnsafe]=NoOverdraw
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceResetConsumedUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceResetConsumedUnsafe]=ConsumptionMatchesReceipts
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceRepeatedSettlementUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceRepeatedSettlementUnsafe]=AtMostOneClose
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceLostRefundUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceLostRefundUnsafe]=Conservation
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceTopUpExpansionUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceTopUpExpansionUnsafe]=NoImplicitExpansion
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceAbortSnapshotUnsafe]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceAbortSnapshotUnsafe]=Conservation
EXPECTED_REFUTATION_WRAPPER[PersistentFundingAllowanceTransferredSettlementReachable]=PersistentFundingAllowance
EXPECTED_REFUTATION_INVARIANT[PersistentFundingAllowanceTransferredSettlementReachable]=NoSettlementAfterTransfer
EXPECTED_REFUTATION_WRAPPER[NumericMergeRngBoundaryPanicUnsafe]=NumericMergeRngBoundary
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceNewerRootUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceNewerRootUnsafe]=CertifiedRootBinding
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceInventedUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceInventedUnsafe]=AuthenticatedFrontierOnly
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceScalarUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceScalarUnsafe]=PerPurseSufficiency
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondencePartialUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondencePartialUnsafe]=NoRejectedCandidateEffects
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceReplayRootUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceReplayRootUnsafe]=ReplayCorrespondence
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceDoubleConsumeUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceDoubleConsumeUnsafe]=NoDoubleConsumption
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceRejectedMoneyUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceRejectedMoneyUnsafe]=WholeEffectRetention
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceUnauthorizedDepositUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceUnauthorizedDepositUnsafe]=DepositConservation
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceGlobalGuardUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceGlobalGuardUnsafe]=IndependentEffectPreservation
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceMissingFrontierUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceMissingFrontierUnsafe]=CompleteDiscoveredFrontier
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceIndependentMoneyUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceIndependentMoneyUnsafe]=MergedPerPurseConservation
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceAggregateOverdrawUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceAggregateOverdrawUnsafe]=MergedPerPurseSufficiency
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceRecoveryReachable]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceRecoveryReachable]=NoRecoveredReplay
EXPECTED_REFUTATION_WRAPPER[NumericMergeFundingCorrespondenceIndependentRootUnsafe]=NumericMergeFundingCorrespondence
EXPECTED_REFUTATION_INVARIANT[NumericMergeFundingCorrespondenceIndependentRootUnsafe]=IndependentPrestateBinding
EXPECTED_REFUTATION_INVARIANT[NumericMergeRngBoundaryPanicUnsafe]=NoBoundaryPanic
EXPECTED_REFUTATION_WRAPPER[NumericMergeAuthorityErasureUnsafe]=NumericMergeAuthority
EXPECTED_REFUTATION_INVARIANT[NumericMergeAuthorityErasureUnsafe]=RetainedProvenance
EXPECTED_REFUTATION_WRAPPER[NumericMergeAuthorityBaseUnsafe]=NumericMergeAuthority
EXPECTED_REFUTATION_INVARIANT[NumericMergeAuthorityBaseUnsafe]=NoConsumedBaseResurrection
EXPECTED_REFUTATION_WRAPPER[NumericMergeAuthorityRejectedUnsafe]=NumericMergeAuthority
EXPECTED_REFUTATION_INVARIANT[NumericMergeAuthorityRejectedUnsafe]=RetainedProvenance
EXPECTED_REFUTATION_WRAPPER[NumericMergeAuthorityMultiplicityUnsafe]=NumericMergeAuthority
EXPECTED_REFUTATION_INVARIANT[NumericMergeAuthorityMultiplicityUnsafe]=ExactFundingMultiplicity
EXPECTED_REFUTATION_WRAPPER[AtomicTrieUpsertRecheckUnsafe]=AtomicTrieUpsert
EXPECTED_REFUTATION_INVARIANT[AtomicTrieUpsertRecheckUnsafe]=UniqueNodeCreation
EXPECTED_REFUTATION_WRAPPER[AtomicTrieUpsertCallbackUnsafe]=AtomicTrieUpsert
EXPECTED_REFUTATION_INVARIANT[AtomicTrieUpsertCallbackUnsafe]=NoLostUpdates
EXPECTED_REFUTATION_WRAPPER[AtomicTrieUpsertBucketUnsafe]=AtomicTrieUpsert
EXPECTED_REFUTATION_INVARIANT[AtomicTrieUpsertBucketUnsafe]=NoLostUpdates
EXPECTED_REFUTATION_WRAPPER[AtomicTrieUpsertNilBucketUnsafe]=AtomicTrieUpsert
EXPECTED_REFUTATION_INVARIANT[AtomicTrieUpsertNilBucketUnsafe]=NoLostPresence
EXPECTED_REFUTATION_WRAPPER[FeeCursorTransitionRevisionUnsafe]=FeeCursorTransition
EXPECTED_REFUTATION_WRAPPER[ContributionCursorSnapshotUnsafe]=ContributionCursor
EXPECTED_REFUTATION_INVARIANT[ContributionCursorSnapshotUnsafe]=ZeroHasNoWrite
EXPECTED_REFUTATION_WRAPPER[ContributionCursorSuccessorUnsafe]=ContributionCursor
EXPECTED_REFUTATION_INVARIANT[ContributionCursorSuccessorUnsafe]=ZeroHasNoWrite
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationStaleGenerationUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationOwnerReturnReachable]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationOwnerReturnReachable]=NoOwnerReturnWithStaleReservation
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationTransferredSettlementReachable]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationTransferredSettlementReachable]=NoSettlementAcrossOwnershipTransfer
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationStaleGenerationUnsafe]=TransfersUseFreshAuthorization
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationCurrentOwnerUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationCurrentOwnerUnsafe]=SettlementUsesCapturedConsent
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationTransferSnapshotUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationTransferSnapshotUnsafe]=CapturedReservationsRemainImmutable
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationTransferFlagsUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationTransferFlagsUnsafe]=SettledFlagsMatchReceipts
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationOverwriteUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationOverwriteUnsafe]=CapturedReservationsRemainImmutable
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationDoubleSettlementUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationDoubleSettlementUnsafe]=AtMostOneSettlement
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationAbortSnapshotUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationAbortSnapshotUnsafe]=AbortPreservesCommittedState
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationOtherRightUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationOtherRightUnsafe]=RightChangesStayInScope
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationGlobalGuardUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationGlobalGuardUnsafe]=IndependentReservationRemainsEnabled
EXPECTED_REFUTATION_WRAPPER[FundingConsentPublicationHighestCeilingUnsafe]=FundingConsentPublication
EXPECTED_REFUTATION_INVARIANT[FundingConsentPublicationHighestCeilingUnsafe]=ReservationsUseRequiredConsent
EXPECTED_REFUTATION_INVARIANT[FeeCursorTransitionRevisionUnsafe]=ReceiptUsesExpectedRevision
EXPECTED_REFUTATION_WRAPPER[FeeCursorTransitionPositionUnsafe]=FeeCursorTransition
EXPECTED_REFUTATION_INVARIANT[FeeCursorTransitionPositionUnsafe]=ReceiptUsesExpectedPosition
EXPECTED_REFUTATION_WRAPPER[FeeCursorTransitionScopeUnsafe]=FeeCursorTransition
EXPECTED_REFUTATION_INVARIANT[FeeCursorTransitionScopeUnsafe]=ReceiptUsesExpectedScope
EXPECTED_REFUTATION_WRAPPER[FeeCursorTransitionOverflowUnsafe]=FeeCursorTransition
EXPECTED_REFUTATION_INVARIANT[FeeCursorTransitionOverflowUnsafe]=CursorWithinRepresentation
EXPECTED_REFUTATION_WRAPPER[FeeCursorTransitionAbortUnsafe]=FeeCursorTransition
EXPECTED_REFUTATION_INVARIANT[FeeCursorTransitionAbortUnsafe]=RevisionCountsCommits
EXPECTED_REFUTATION_WRAPPER[FeeCursorCellsInitializeUnsafe]=FeeCursorCells
EXPECTED_REFUTATION_INVARIANT[FeeCursorCellsInitializeUnsafe]=ExactlyOnePairPerInitializedScope
EXPECTED_REFUTATION_WRAPPER[FeeCursorCellsRestoreUnsafe]=FeeCursorCells
EXPECTED_REFUTATION_INVARIANT[FeeCursorCellsRestoreUnsafe]=PublishedCellsMatchLogicalCursor
EXPECTED_REFUTATION_WRAPPER[FeeCursorCellsPositionUnsafe]=FeeCursorCells
EXPECTED_REFUTATION_INVARIANT[FeeCursorCellsPositionUnsafe]=ExactlyOnePairPerInitializedScope
EXPECTED_REFUTATION_WRAPPER[FeeCursorCellsRevisionUnsafe]=FeeCursorCells
EXPECTED_REFUTATION_INVARIANT[FeeCursorCellsRevisionUnsafe]=EveryFeeHasOneRevision
EXPECTED_REFUTATION_WRAPPER[FundingCursorCellsSequentialUnsafe]=FundingCursorCells
EXPECTED_REFUTATION_INVARIANT[FundingCursorCellsSequentialUnsafe]=NoPartialAcquisition
EXPECTED_REFUTATION_WRAPPER[FundingCursorCellsRevisionUnsafe]=FundingCursorCells
EXPECTED_REFUTATION_INVARIANT[FundingCursorCellsRevisionUnsafe]=CapturedRevisionUsedOnce
EXPECTED_REFUTATION_WRAPPER[FundingCursorCellsPublishUnsafe]=FundingCursorCells
EXPECTED_REFUTATION_INVARIANT[FundingCursorCellsPublishUnsafe]=BothContributionsHaveSuccessors
EXPECTED_REFUTATION_WRAPPER[FundingCursorCellsRestoreUnsafe]=FundingCursorCells
EXPECTED_REFUTATION_INVARIANT[FundingCursorCellsRestoreUnsafe]=BothContributionsHaveSuccessors
EXPECTED_REFUTATION_WRAPPER[FeeCursorReadBoundaryExtraUnsafe]=FeeCursorReadBoundary
EXPECTED_REFUTATION_INVARIANT[FeeCursorReadBoundaryExtraUnsafe]=AcceptedContainsExactlyOneTypedReply
EXPECTED_REFUTATION_WRAPPER[RedemptionCustodyAtomicityCheckpointStakeUnsafe]=RedemptionCustodyAtomicity
EXPECTED_REFUTATION_INVARIANT[RedemptionCustodyAtomicityCheckpointStakeUnsafe]=AbortedExecutionPublishesNothing
EXPECTED_REFUTATION_WRAPPER[RedemptionCustodyAtomicityCheckpointFuelUnsafe]=RedemptionCustodyAtomicity
EXPECTED_REFUTATION_INVARIANT[RedemptionCustodyAtomicityCheckpointFuelUnsafe]=AbortedExecutionPublishesNothing
EXPECTED_REFUTATION_WRAPPER[RedemptionCustodyAtomicityEarlyReceiptUnsafe]=RedemptionCustodyAtomicity
EXPECTED_REFUTATION_INVARIANT[RedemptionCustodyAtomicityEarlyReceiptUnsafe]=AbortedExecutionPublishesNothing
EXPECTED_REFUTATION_WRAPPER[RedemptionCustodyAtomicityLostReceiptUnsafe]=RedemptionCustodyAtomicity
EXPECTED_REFUTATION_INVARIANT[RedemptionCustodyAtomicityLostReceiptUnsafe]=GuiltyPenaltyAppliedExactlyOnce
EXPECTED_REFUTATION_WRAPPER[ConcurrentRedemptionCustodyNoTargetLockUnsafe]=ConcurrentRedemptionCustody
EXPECTED_REFUTATION_INVARIANT[ConcurrentRedemptionCustodyNoTargetLockUnsafe]=AtMostOneResolutionPerIncarnation
EXPECTED_REFUTATION_WRAPPER[ConcurrentRedemptionCustodyIgnoreGenerationUnsafe]=ConcurrentRedemptionCustody
EXPECTED_REFUTATION_INVARIANT[ConcurrentRedemptionCustodyIgnoreGenerationUnsafe]=ReceiptsUseAuthorizedGeneration
EXPECTED_REFUTATION_WRAPPER[ConcurrentRedemptionCustodyFullGuiltyUnsafe]=ConcurrentRedemptionCustody
EXPECTED_REFUTATION_INVARIANT[ConcurrentRedemptionCustodyFullGuiltyUnsafe]=GuiltyIsStrictlyPartial
EXPECTED_REFUTATION_WRAPPER[ConcurrentRedemptionCustodyRestoreBondedUnsafe]=ConcurrentRedemptionCustody
EXPECTED_REFUTATION_INVARIANT[ConcurrentRedemptionCustodyRestoreBondedUnsafe]=RestoresExactLifecycle
EXPECTED_REFUTATION_WRAPPER[ConcurrentRedemptionCustodyCheckpointStakeUnsafe]=ConcurrentRedemptionCustody
EXPECTED_REFUTATION_INVARIANT[ConcurrentRedemptionCustodyCheckpointStakeUnsafe]=RejectedTransactionsPublishNothing
EXPECTED_REFUTATION_WRAPPER[ConcurrentRedemptionCustodyCheckpointFuelUnsafe]=ConcurrentRedemptionCustody
EXPECTED_REFUTATION_INVARIANT[ConcurrentRedemptionCustodyCheckpointFuelUnsafe]=RejectedTransactionsPublishNothing
EXPECTED_REFUTATION_WRAPPER[ConcurrentRedemptionCustodyLostReceiptUnsafe]=ConcurrentRedemptionCustody
EXPECTED_REFUTATION_INVARIANT[ConcurrentRedemptionCustodyLostReceiptUnsafe]=ExactRetriesAreEffectFree
EXPECTED_REFUTATION_WRAPPER[ConcurrentRedemptionCustodyOverwriteConflictUnsafe]=ConcurrentRedemptionCustody
EXPECTED_REFUTATION_INVARIANT[ConcurrentRedemptionCustodyOverwriteConflictUnsafe]=ConflictingRetriesAreEffectFree
EXPECTED_REFUTATION_WRAPPER[AccountingScopeLifetimeBooleanUnsafe]=AccountingScopeLifetime
EXPECTED_REFUTATION_INVARIANT[AccountingScopeLifetimeBooleanUnsafe]=AccountingScopeReflectsOwners
EXPECTED_REFUTATION_WRAPPER[AtomicCommAccountingIntroductionUnsafe]=MCAtomicCommAccountingIntroductionUnsafe
EXPECTED_REFUTATION_INVARIANT[AtomicCommAccountingIntroductionUnsafe]=ExactCommCost
EXPECTED_REFUTATION_WRAPPER[VaultBackedByteAccountingChargeAfterMutationUnsafe]=VaultBackedByteAccounting
EXPECTED_REFUTATION_INVARIANT[VaultBackedByteAccountingChargeAfterMutationUnsafe]=RejectedAttemptIsAtomic
EXPECTED_REFUTATION_WRAPPER[VaultBackedByteAccountingTriggerDependentUnsafe]=VaultBackedByteAccounting
EXPECTED_REFUTATION_INVARIANT[VaultBackedByteAccountingTriggerDependentUnsafe]=ExactCanonicalDebit
EXPECTED_REFUTATION_WRAPPER[VaultBackedByteAccountingOmitJoinParticipantUnsafe]=VaultBackedByteAccounting
EXPECTED_REFUTATION_INVARIANT[VaultBackedByteAccountingOmitJoinParticipantUnsafe]=ExactCanonicalDebit
EXPECTED_REFUTATION_WRAPPER[VaultBackedByteAccountingRechargePersistentUnsafe]=VaultBackedByteAccounting
EXPECTED_REFUTATION_INVARIANT[VaultBackedByteAccountingRechargePersistentUnsafe]=ExactCanonicalDebit
EXPECTED_REFUTATION_WRAPPER[VaultBackedByteAccountingPeekCreditUnsafe]=VaultBackedByteAccounting
EXPECTED_REFUTATION_INVARIANT[VaultBackedByteAccountingPeekCreditUnsafe]=NoRemovalCredit
EXPECTED_REFUTATION_WRAPPER[VaultBackedByteAccountingReplayOmissionUnsafe]=VaultBackedByteAccounting
EXPECTED_REFUTATION_INVARIANT[VaultBackedByteAccountingReplayOmissionUnsafe]=ReplayPrefixExact
EXPECTED_REFUTATION_WRAPPER[VaultBackedByteAccountingTopUpExpandsBoundUnsafe]=VaultBackedByteAccounting
EXPECTED_REFUTATION_INVARIANT[VaultBackedByteAccountingTopUpExpandsBoundUnsafe]=ReservationSnapshotImmutable
EXPECTED_REFUTATION_WRAPPER[VaultBackedByteAccountingOverflowWrapUnsafe]=VaultBackedByteAccounting
EXPECTED_REFUTATION_INVARIANT[VaultBackedByteAccountingOverflowWrapUnsafe]=ExactCanonicalDebit
EXPECTED_REFUTATION_WRAPPER[LocatedVaultByteSettlementEnvelopeCollapseUnsafe]=LocatedVaultByteSettlement
EXPECTED_REFUTATION_INVARIANT[LocatedVaultByteSettlementEnvelopeCollapseUnsafe]=ExactLocatedDebit
EXPECTED_REFUTATION_WRAPPER[LocatedVaultByteSettlementCrossPurseRescueUnsafe]=LocatedVaultByteSettlement
EXPECTED_REFUTATION_INVARIANT[LocatedVaultByteSettlementCrossPurseRescueUnsafe]=UnderfundedContinuationCannotUseAnotherPurse
EXPECTED_REFUTATION_WRAPPER[LocatedVaultByteSettlementTopUpExpandsReservationUnsafe]=LocatedVaultByteSettlement
EXPECTED_REFUTATION_INVARIANT[LocatedVaultByteSettlementTopUpExpandsReservationUnsafe]=ReservationSnapshotImmutable
EXPECTED_REFUTATION_WRAPPER[LocatedVaultByteSettlementReplayUsesEnvelopeUnsafe]=LocatedVaultByteSettlement
EXPECTED_REFUTATION_INVARIANT[LocatedVaultByteSettlementReplayUsesEnvelopeUnsafe]=ReplayAllocationIsExact
EXPECTED_REFUTATION_WRAPPER[AuthenticatedSupplySnapshotLiveUnsafe]=AuthenticatedSupplySnapshot
EXPECTED_REFUTATION_INVARIANT[AuthenticatedSupplySnapshotLiveUnsafe]=CandidateMintCannotFundItself
EXPECTED_REFUTATION_WRAPPER[ReplaySupplySnapshotLiveQueryUnsafe]=MCReplaySupplySnapshot
EXPECTED_REFUTATION_INVARIANT[ReplaySupplySnapshotLiveQueryUnsafe]=ExactRecordedReplayTrace
EXPECTED_REFUTATION_WRAPPER[ReplaySupplySnapshotReplayRuntimeUnsafe]=MCReplaySupplySnapshot
EXPECTED_REFUTATION_INVARIANT[ReplaySupplySnapshotReplayRuntimeUnsafe]=SnapshotsUseOrdinaryRuntime
EXPECTED_REFUTATION_WRAPPER[ReplaySupplySnapshotLateCaptureUnsafe]=MCReplaySupplySnapshot
EXPECTED_REFUTATION_INVARIANT[ReplaySupplySnapshotLateCaptureUnsafe]=SnapshotsPrecedeRigging
EXPECTED_REFUTATION_WRAPPER[ReplaySupplySnapshotWrongRootUnsafe]=MCReplaySupplySnapshot
EXPECTED_REFUTATION_INVARIANT[ReplaySupplySnapshotWrongRootUnsafe]=SnapshotsUseCurrentRoot
EXPECTED_REFUTATION_WRAPPER[ReplaySupplySnapshotWrongProposerUnsafe]=MCReplaySupplySnapshot
EXPECTED_REFUTATION_INVARIANT[ReplaySupplySnapshotWrongProposerUnsafe]=SnapshotsUseCertifiedProposer
EXPECTED_REFUTATION_WRAPPER[ReplaySupplySnapshotRecordedBalanceUnsafe]=MCReplaySupplySnapshot
EXPECTED_REFUTATION_INVARIANT[ReplaySupplySnapshotRecordedBalanceUnsafe]=SnapshotsMatchActualFuel
EXPECTED_REFUTATION_WRAPPER[ReplaySupplySnapshotNoSettlementUnsafe]=MCReplaySupplySnapshot
EXPECTED_REFUTATION_INVARIANT[ReplaySupplySnapshotNoSettlementUnsafe]=ActualSettlementRequired
EXPECTED_REFUTATION_WRAPPER[ReplaySupplySnapshotDeferredBurnUnsafe]=MCReplaySupplySnapshot
EXPECTED_REFUTATION_INVARIANT[ReplaySupplySnapshotDeferredBurnUnsafe]=DeferredCandidatesDoNotBurn
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitDeployIdentityUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_WRAPPER[ReplayCacheContextOmitTimestampUnsafe]=ReplayCacheContext
EXPECTED_REFUTATION_INVARIANT[ReplayCacheContextOmitTimestampUnsafe]=ReplayUsesExactContext
EXPECTED_REFUTATION_WRAPPER[ReplayCacheContextOmitHeightUnsafe]=ReplayCacheContext
EXPECTED_REFUTATION_INVARIANT[ReplayCacheContextOmitHeightUnsafe]=ReplayUsesExactContext
EXPECTED_REFUTATION_WRAPPER[ReplayCacheContextOmitInvalidBlocksUnsafe]=ReplayCacheContext
EXPECTED_REFUTATION_INVARIANT[ReplayCacheContextOmitInvalidBlocksUnsafe]=ReplayUsesExactContext
EXPECTED_REFUTATION_WRAPPER[ReplayCacheContextIgnoreHostLimitUnsafe]=ReplayCacheContext
EXPECTED_REFUTATION_INVARIANT[ReplayCacheContextIgnoreHostLimitUnsafe]=BoundedWorkCannotHitCache
EXPECTED_REFUTATION_WRAPPER[ReplayCacheContextIgnoreMetadataUnsafe]=ReplayCacheContext
EXPECTED_REFUTATION_INVARIANT[ReplayCacheContextIgnoreMetadataUnsafe]=HitHadMetadata
EXPECTED_REFUTATION_WRAPPER[ReplayCacheContextPublishUnvalidatedUnsafe]=ReplayCacheContext
EXPECTED_REFUTATION_INVARIANT[ReplayCacheContextPublishUnvalidatedUnsafe]=NoUnvalidatedPublication
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitDeployIdentityUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitPreStateUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitPreStateUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitScheduleUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitScheduleUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitWitnessUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitWitnessUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitCostSurfaceUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitCostSurfaceUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitGradeUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitGradeUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitContextUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitContextUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitUserPostStateUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitUserPostStateUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseOmitMergeableUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseOmitMergeableUnsafe]=ValidatedReuseIsExact
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseCacheBeforeValidationUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseCacheBeforeValidationUnsafe]=CacheFollowsExactDurability
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseDuplicateUserReplayUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseDuplicateUserReplayUnsafe]=UserExecutionOccursOnce
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseRechargePersistentIntroductionUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseRechargePersistentIntroductionUnsafe]=PersistentIntroductionChargedOnce
EXPECTED_REFUTATION_WRAPPER[ExecutionResultReuseCollapsePersistentFiringsUnsafe]=ExecutionResultReuse
EXPECTED_REFUTATION_INVARIANT[ExecutionResultReuseCollapsePersistentFiringsUnsafe]=PersistentFiringsChargedSeparately
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationReuseOldCertificateUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationReuseOldCertificateUnsafe]=CertificateUsesCurrentGeneration
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationPreserveOldRejectionsUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationPreserveOldRejectionsUnsafe]=CertifiedPartitionIsCompleteAndDisjoint
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationDropFinalRejectionsUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationDropFinalRejectionsUnsafe]=PublishedPartitionIsCompleteAndDisjoint
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationRecertifyAcceptedOnlyUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationRecertifyAcceptedOnlyUnsafe]=CertifiedPartitionIsCompleteAndDisjoint
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationContextDriftUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationContextDriftUnsafe]=CertificateUsesFrozenContext
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationShrinkInitiallyAdmittedUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationShrinkInitiallyAdmittedUnsafe]=CertifiedWindowIsCanonicalRawPrefix
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationDrainOriginalCandidatesUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationDrainOriginalCandidatesUnsafe]=StorageDrainsOnlyFinalTerminalUsers
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationPublishBeforeSuccessUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationPublishBeforeSuccessUnsafe]=FailedAttemptsPublishNothing
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationTreatDeferredAsRejectedUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationTreatDeferredAsRejectedUnsafe]=PeerRecomputationMatchesPublication
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationArrivalOrderUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationArrivalOrderUnsafe]=CertifiedWindowIsCanonicalRawPrefix
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationSharedMutableAttemptUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationSharedMutableAttemptUnsafe]=ValidatorAttemptStateIsIndependent
EXPECTED_REFUTATION_WRAPPER[CheckpointAdmissionRecertificationNonDecreasingRetryUnsafe]=CheckpointAdmissionRecertification
EXPECTED_REFUTATION_INVARIANT[CheckpointAdmissionRecertificationNonDecreasingRetryUnsafe]=RetryLimitsStrictlyDecrease
EXPECTED_REFUTATION_WRAPPER[ReplayRootMaterializationEagerUnsafe]=ReplayRootMaterialization
EXPECTED_REFUTATION_INVARIANT[ReplayRootMaterializationEagerUnsafe]=SnapshotReadsMaterializedRoot
EXPECTED_REFUTATION_WRAPPER[ReplayRootMaterializationHistoryUnsafe]=ReplayRootMaterialization
EXPECTED_REFUTATION_INVARIANT[ReplayRootMaterializationHistoryUnsafe]=CompletedValidatorsAgree
EXPECTED_REFUTATION_WRAPPER[ReplayRootMaterializationQueryUnsafe]=ReplayRootMaterialization
EXPECTED_REFUTATION_INVARIANT[ReplayRootMaterializationQueryUnsafe]=SnapshotsUseOrdinaryRuntime
EXPECTED_REFUTATION_WRAPPER[StateBoundAdmissionDriftUnsafe]=MCStateBoundAdmission
EXPECTED_REFUTATION_INVARIANT[StateBoundAdmissionDriftUnsafe]=EvidenceMatchesCommit
EXPECTED_REFUTATION_WRAPPER[StateBoundAdmissionExhaustionUnsafe]=MCStateBoundAdmission
EXPECTED_REFUTATION_INVARIANT[StateBoundAdmissionExhaustionUnsafe]=AdmissionRequiresCompletedProof
EXPECTED_REFUTATION_WRAPPER[StateBoundAdmissionStructuralUnsafe]=MCStateBoundAdmission
EXPECTED_REFUTATION_INVARIANT[StateBoundAdmissionStructuralUnsafe]=EvidenceMatchesCommit
EXPECTED_REFUTATION_WRAPPER[StateBoundAdmissionReplayUnsafe]=MCStateBoundAdmission
EXPECTED_REFUTATION_INVARIANT[StateBoundAdmissionReplayUnsafe]=CommitMatchesReplay
EXPECTED_REFUTATION_WRAPPER[StateBoundAdmissionCheckpointUnsafe]=MCStateBoundAdmission
EXPECTED_REFUTATION_INVARIANT[StateBoundAdmissionCheckpointUnsafe]=PhysicalRejectionCreatesNoCheckpoint
EXPECTED_REFUTATION_WRAPPER[StateBoundValidatorConvergenceContextUnsafe]=MCStateBoundValidatorConvergence
EXPECTED_REFUTATION_INVARIANT[StateBoundValidatorConvergenceContextUnsafe]=AcceptedUsesAuthenticatedContext
EXPECTED_REFUTATION_WRAPPER[StateBoundValidatorConvergenceOrderUnsafe]=MCStateBoundValidatorConvergence
EXPECTED_REFUTATION_INVARIANT[StateBoundValidatorConvergenceOrderUnsafe]=AcceptedUsesCanonicalDeployOrder
EXPECTED_REFUTATION_WRAPPER[StateBoundValidatorConvergenceScheduleUnsafe]=MCStateBoundValidatorConvergence
EXPECTED_REFUTATION_INVARIANT[StateBoundValidatorConvergenceScheduleUnsafe]=AcceptedReproducesCertificate
EXPECTED_REFUTATION_WRAPPER[EndToEndCostConsensusDoubleCreditUnsafe]=MCEndToEndCostConsensus
EXPECTED_REFUTATION_INVARIANT[EndToEndCostConsensusDoubleCreditUnsafe]=SettlementDoesNotReapplyGenesisFunding
EXPECTED_REFUTATION_WRAPPER[EndToEndCostConsensusFundingBypassUnsafe]=MCEndToEndCostConsensus
EXPECTED_REFUTATION_INVARIANT[EndToEndCostConsensusFundingBypassUnsafe]=EveryExecutedDeploymentWasFunded
EXPECTED_REFUTATION_WRAPPER[EndToEndCostConsensusGenesisMismatchUnsafe]=MCEndToEndCostConsensus
EXPECTED_REFUTATION_INVARIANT[EndToEndCostConsensusGenesisMismatchUnsafe]=AdmissionRequiresGenesisAgreement
EXPECTED_REFUTATION_WRAPPER[EndToEndCostConsensusGenesisAuthorityMismatchUnsafe]=MCEndToEndCostConsensus
EXPECTED_REFUTATION_INVARIANT[EndToEndCostConsensusGenesisAuthorityMismatchUnsafe]=GenesisExecutionReplayAuthorityAgree
EXPECTED_REFUTATION_WRAPPER[EndToEndCostConsensusUnsafe]=MCEndToEndCostConsensus
EXPECTED_REFUTATION_INVARIANT[EndToEndCostConsensusUnsafe]=LocalFaultNeverCreatesSlashEvidence
EXPECTED_REFUTATION_WRAPPER[EndToEndCostConsensusOriginBypassUnsafe]=MCEndToEndCostConsensus
EXPECTED_REFUTATION_INVARIANT[EndToEndCostConsensusOriginBypassUnsafe]=ValidationOriginParity
EXPECTED_REFUTATION_WRAPPER[DeployTraceSegmentationRetentionUnsafe]=MCDeployTraceSegmentation
EXPECTED_REFUTATION_INVARIANT[DeployTraceSegmentationRetentionUnsafe]=CheckpointContainsOnlyItsDeploy
EXPECTED_REFUTATION_WRAPPER[MergeAggregateAgreementPrefixUnsafe]=MCMergeAggregateAgreement
EXPECTED_REFUTATION_INVARIANT[MergeAggregateAgreementPrefixUnsafe]=AcceptanceIsPermutationInvariant
EXPECTED_REFUTATION_WRAPPER[LocatedAuthoritySettlementMetadataErasureUnsafe]=MCLocatedAuthoritySettlement
EXPECTED_REFUTATION_INVARIANT[LocatedAuthoritySettlementMetadataErasureUnsafe]=RealizedBackedByReservation
EXPECTED_REFUTATION_WRAPPER[LocatedAuthoritySettlementAmbientPurseUnsafe]=MCLocatedAuthoritySettlement
EXPECTED_REFUTATION_INVARIANT[LocatedAuthoritySettlementAmbientPurseUnsafe]=NoAmbientAuthority
EXPECTED_REFUTATION_WRAPPER[LocatedAuthoritySettlementContinuationRewrapUnsafe]=MCLocatedAuthoritySettlement
EXPECTED_REFUTATION_INVARIANT[LocatedAuthoritySettlementContinuationRewrapUnsafe]=RealizedBackedByReservation
EXPECTED_REFUTATION_WRAPPER[LocatedAuthoritySettlementNonAtomicDebitUnsafe]=MCLocatedAuthoritySettlement
EXPECTED_REFUTATION_INVARIANT[LocatedAuthoritySettlementNonAtomicDebitUnsafe]=NoPartialEventDebit
EXPECTED_REFUTATION_WRAPPER[LocatedAuthoritySettlementReplayOmissionUnsafe]=MCLocatedAuthoritySettlement
EXPECTED_REFUTATION_INVARIANT[LocatedAuthoritySettlementReplayOmissionUnsafe]=ReplayPreservesAuthority
EXPECTED_REFUTATION_WRAPPER[LocatedAuthoritySettlementSlotIdentityUnsafe]=MCLocatedAuthoritySettlement
EXPECTED_REFUTATION_INVARIANT[LocatedAuthoritySettlementSlotIdentityUnsafe]=CrossDeploySlotIdentityStable
EXPECTED_REFUTATION_WRAPPER[AuthorityPresentationMissingUnsafe]=AuthorityPresentation
EXPECTED_REFUTATION_INVARIANT[AuthorityPresentationMissingUnsafe]=IntermediatePartitionAdmitted
EXPECTED_REFUTATION_WRAPPER[AuthorityPresentationWeakeningUnsafe]=AuthorityPresentation
EXPECTED_REFUTATION_INVARIANT[AuthorityPresentationWeakeningUnsafe]=NoWeakening
EXPECTED_REFUTATION_WRAPPER[AuthorityPresentationNonAtomicUnsafe]=AuthorityPresentation
EXPECTED_REFUTATION_INVARIANT[AuthorityPresentationNonAtomicUnsafe]=NoPartialEventDebit
EXPECTED_REFUTATION_WRAPPER[AuthorityPresentationReplayUnsafe]=AuthorityPresentation
EXPECTED_REFUTATION_INVARIANT[AuthorityPresentationReplayUnsafe]=ReplayUsesCertifiedPresentation
EXPECTED_REFUTATION_WRAPPER[AuthorityPresentationCertificateUnsafe]=AuthorityPresentation
EXPECTED_REFUTATION_INVARIANT[AuthorityPresentationCertificateUnsafe]=CertificateBindsPhysicalReservation
EXPECTED_REFUTATION_WRAPPER[ForcedRedexAccountingDedupUnsafe]=ForcedRedexAccounting
EXPECTED_REFUTATION_INVARIANT[ForcedRedexAccountingDedupUnsafe]=EveryForcedRedexConsumesOne
EXPECTED_REFUTATION_WRAPPER[ForcedRedexAccountingReplayUnsafe]=ForcedRedexAccounting
EXPECTED_REFUTATION_INVARIANT[ForcedRedexAccountingReplayUnsafe]=ReplayStaysWithinCertificate
EXPECTED_REFUTATION_WRAPPER[StructuralAuthorityBoundReuseUnsafe]=StructuralAuthorityBound
EXPECTED_REFUTATION_INVARIANT[StructuralAuthorityBoundReuseUnsafe]=RealizedNeverExceedsStructuralDemand
EXPECTED_REFUTATION_WRAPPER[CausalStackOrderHashUnsafe]=CausalStackOrder
EXPECTED_REFUTATION_INVARIANT[CausalStackOrderHashUnsafe]=CausallyFundedTraceIsAccepted
EXPECTED_REFUTATION_WRAPPER[ParallelStackMaterializationUnsafe]=ParallelStackMaterialization
EXPECTED_REFUTATION_INVARIANT[ParallelStackMaterializationUnsafe]=CausallyFundedProgramIsAccepted
EXPECTED_REFUTATION_WRAPPER[CapacityBoundedTraceFixedCapUnsafe]=MCCapacityBoundedTrace
EXPECTED_REFUTATION_INVARIANT[CapacityBoundedTraceFixedCapUnsafe]=AcceptedTraceIsExact
EXPECTED_REFUTATION_WRAPPER[RuntimeBoundAuthorityPrematureRejectUnsafe]=RuntimeBoundAuthority
EXPECTED_REFUTATION_INVARIANT[RuntimeBoundAuthorityPrematureRejectUnsafe]=BoundAuthorityDeferred
EXPECTED_REFUTATION_WRAPPER[RuntimeBoundAuthorityCandidateMintUnsafe]=RuntimeBoundAuthority
EXPECTED_REFUTATION_INVARIANT[RuntimeBoundAuthorityCandidateMintUnsafe]=CandidateStackCannotFundCreator
EXPECTED_REFUTATION_WRAPPER[RuntimeBoundAuthorityReplayUnsafe]=RuntimeBoundAuthority
EXPECTED_REFUTATION_INVARIANT[RuntimeBoundAuthorityReplayUnsafe]=ReplayPreservesResolvedSlot
EXPECTED_REFUTATION_WRAPPER[PayloadSortPersistenceStorageErasureUnsafe]=PayloadSortPersistence
EXPECTED_REFUTATION_INVARIANT[PayloadSortPersistenceStorageErasureUnsafe]=StoragePreservesCompletePayload
EXPECTED_REFUTATION_WRAPPER[PayloadSortPersistenceMatcherErasureUnsafe]=PayloadSortPersistence
EXPECTED_REFUTATION_INVARIANT[PayloadSortPersistenceMatcherErasureUnsafe]=MatcherCaptureIsExact
EXPECTED_REFUTATION_WRAPPER[PayloadSortPersistenceReplayErasureUnsafe]=PayloadSortPersistence
EXPECTED_REFUTATION_INVARIANT[PayloadSortPersistenceReplayErasureUnsafe]=ReplayPreservesCompletePayload
EXPECTED_REFUTATION_WRAPPER[SettlementMergeVisibilityEventOmissionUnsafe]=SettlementMergeVisibility
EXPECTED_REFUTATION_INVARIANT[SettlementMergeVisibilityEventOmissionUnsafe]=SettlementStateChangeIsIndexed
EXPECTED_REFUTATION_WRAPPER[SettlementMergeVisibilityIdentityCollapseUnsafe]=SettlementMergeVisibility
EXPECTED_REFUTATION_INVARIANT[SettlementMergeVisibilityIdentityCollapseUnsafe]=DistinctInstancesRemainMergeable
EXPECTED_REFUTATION_WRAPPER[SettlementMergeVisibilityReplayOmissionUnsafe]=SettlementMergeVisibility
EXPECTED_REFUTATION_INVARIANT[SettlementMergeVisibilityReplayOmissionUnsafe]=ReplayReproducesRemoval
EXPECTED_REFUTATION_WRAPPER[SettlementMergeVisibilityTraceLossUnsafe]=SettlementMergeVisibility
EXPECTED_REFUTATION_INVARIANT[SettlementMergeVisibilityTraceLossUnsafe]=SoftCheckpointPreservesTracePrefix
EXPECTED_REFUTATION_WRAPPER[LocatedStackConservationDuplicateUnsafe]=LocatedStackConservation
EXPECTED_REFUTATION_INVARIANT[LocatedStackConservationDuplicateUnsafe]=UserStackProductionConserves
EXPECTED_REFUTATION_WRAPPER[LocatedStackConservationPartialUnsafe]=LocatedStackConservation
EXPECTED_REFUTATION_INVARIANT[LocatedStackConservationPartialUnsafe]=UserStackProductionConserves
EXPECTED_REFUTATION_WRAPPER[LocatedStackConservationReplayUnsafe]=LocatedStackConservation
EXPECTED_REFUTATION_INVARIANT[LocatedStackConservationReplayUnsafe]=ReplayMatchesCommittedTransfer
EXPECTED_REFUTATION_WRAPPER[StackIntroductionAtomicityExposePreparedUnsafe]=StackIntroductionAtomicity
EXPECTED_REFUTATION_INVARIANT[StackIntroductionAtomicityExposePreparedUnsafe]=PreparedAuthorityIsNotWitnessVisible
EXPECTED_REFUTATION_WRAPPER[StackIntroductionAtomicityOmitAbortUnsafe]=StackIntroductionAtomicity
EXPECTED_REFUTATION_INVARIANT[StackIntroductionAtomicityOmitAbortUnsafe]=RejectedOperationIsEffectFree
EXPECTED_REFUTATION_WRAPPER[StackIntroductionAtomicityFallibleBirthUnsafe]=StackIntroductionAtomicity
EXPECTED_REFUTATION_INVARIANT[StackIntroductionAtomicityFallibleBirthUnsafe]=EveryCommittedStackHasOneBirth
EXPECTED_REFUTATION_WRAPPER[StackIntroductionAtomicityOmitNestedProduceUnsafe]=StackIntroductionAtomicity
EXPECTED_REFUTATION_INVARIANT[StackIntroductionAtomicityOmitNestedProduceUnsafe]=EveryCommittedStackIsCausallyExtracted
EXPECTED_REFUTATION_WRAPPER[StackIntroductionAtomicityOmitDeployRollbackUnsafe]=StackIntroductionAtomicity
EXPECTED_REFUTATION_INVARIANT[StackIntroductionAtomicityOmitDeployRollbackUnsafe]=FailedDeployHasNoLinearEffects
EXPECTED_REFUTATION_WRAPPER[StackIntroductionAtomicityReplayOmissionUnsafe]=StackIntroductionAtomicity
EXPECTED_REFUTATION_INVARIANT[StackIntroductionAtomicityReplayOmissionUnsafe]=ReplayMatchesCommit
EXPECTED_REFUTATION_WRAPPER[EvaluationTransactionIsolationParserReuseUnsafe]=EvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[EvaluationTransactionIsolationParserReuseUnsafe]=ParserFailureHasNoWitness
EXPECTED_REFUTATION_WRAPPER[EvaluationTransactionIsolationReducerEraseUnsafe]=EvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[EvaluationTransactionIsolationReducerEraseUnsafe]=ReducerFailureRetainsAttemptedWork
EXPECTED_REFUTATION_WRAPPER[EvaluationTransactionIsolationPlayRollbackUnsafe]=EvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[EvaluationTransactionIsolationPlayRollbackUnsafe]=RejectedPlayIsStateAtomic
EXPECTED_REFUTATION_WRAPPER[EvaluationTransactionIsolationReplayRollbackUnsafe]=EvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[EvaluationTransactionIsolationReplayRollbackUnsafe]=RejectedReplayIsStateAtomic
EXPECTED_REFUTATION_WRAPPER[EvaluationTransactionIsolationEarlyEvidenceUnsafe]=EvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[EvaluationTransactionIsolationEarlyEvidenceUnsafe]=RejectedReplayPublishesNoEvidence
EXPECTED_REFUTATION_WRAPPER[ConcurrentEvaluationParserReuseUnsafe]=ConcurrentEvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[ConcurrentEvaluationParserReuseUnsafe]=ParserFailureHasNoWitness
EXPECTED_REFUTATION_WRAPPER[ConcurrentEvaluationReducerEraseUnsafe]=ConcurrentEvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[ConcurrentEvaluationReducerEraseUnsafe]=ReducerFailureRetainsAttemptedWork
EXPECTED_REFUTATION_WRAPPER[ConcurrentEvaluationPlayRollbackUnsafe]=ConcurrentEvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[ConcurrentEvaluationPlayRollbackUnsafe]=RejectedTransactionsAreStateAtomic
EXPECTED_REFUTATION_WRAPPER[ConcurrentEvaluationReplayRollbackUnsafe]=ConcurrentEvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[ConcurrentEvaluationReplayRollbackUnsafe]=RejectedTransactionsAreStateAtomic
EXPECTED_REFUTATION_WRAPPER[ConcurrentEvaluationEarlyEvidenceUnsafe]=ConcurrentEvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[ConcurrentEvaluationEarlyEvidenceUnsafe]=EvidenceRequiresAcceptance
EXPECTED_REFUTATION_WRAPPER[ConcurrentEvaluationSharedRootAuthorityUnsafe]=ConcurrentEvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[ConcurrentEvaluationSharedRootAuthorityUnsafe]=ExplicitBaseAuthority
EXPECTED_REFUTATION_WRAPPER[ConcurrentEvaluationSharedRootPublicationUnsafe]=ConcurrentEvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[ConcurrentEvaluationSharedRootPublicationUnsafe]=AcceptedRootsAreOwnedAndRecorded
EXPECTED_REFUTATION_WRAPPER[ConcurrentEvaluationForeignRootDeletionUnsafe]=ConcurrentEvaluationTransactionIsolation
EXPECTED_REFUTATION_INVARIANT[ConcurrentEvaluationForeignRootDeletionUnsafe]=CheckpointedRootsRemainRecorded
EXPECTED_REFUTATION_WRAPPER[MultiShardBlindCommitUnsafe]=MultiShardResourceIsolation
EXPECTED_REFUTATION_INVARIANT[MultiShardBlindCommitUnsafe]=LedgerMatchesOwnedCommits
EXPECTED_REFUTATION_WRAPPER[MultiShardStateWriteUnsafe]=MultiShardResourceIsolation
EXPECTED_REFUTATION_INVARIANT[MultiShardStateWriteUnsafe]=LedgerMatchesOwnedCommits
EXPECTED_REFUTATION_WRAPPER[MultiShardRootPublicationUnsafe]=MultiShardResourceIsolation
EXPECTED_REFUTATION_INVARIANT[MultiShardRootPublicationUnsafe]=RecordedRootsMatchLedger
EXPECTED_REFUTATION_WRAPPER[MultiShardDebitUnsafe]=MultiShardResourceIsolation
EXPECTED_REFUTATION_INVARIANT[MultiShardDebitUnsafe]=ChargesMatchOwnedCommits
EXPECTED_REFUTATION_WRAPPER[MultiShardResourceLeakUnsafe]=MultiShardResourceIsolation
EXPECTED_REFUTATION_INVARIANT[MultiShardResourceLeakUnsafe]=ResourceOwnershipExact
EXPECTED_REFUTATION_WRAPPER[MergeableEvidenceAuthenticationLegacyKeyUnsafe]=MergeableEvidenceAuthentication
EXPECTED_REFUTATION_INVARIANT[MergeableEvidenceAuthenticationLegacyKeyUnsafe]=OppositeArrivalOrdersConverge
EXPECTED_REFUTATION_WRAPPER[MergeableEvidenceAuthenticationLegacyDeleteUnsafe]=MergeableEvidenceAuthentication
EXPECTED_REFUTATION_INVARIANT[MergeableEvidenceAuthenticationLegacyDeleteUnsafe]=DeletionCommutesWithDistinctReplay
EXPECTED_REFUTATION_WRAPPER[MergeableEvidenceAuthenticationPeerTrustUnsafe]=MergeableEvidenceAuthentication
EXPECTED_REFUTATION_INVARIANT[MergeableEvidenceAuthenticationPeerTrustUnsafe]=LocallyDerivedEvidenceOnly
EXPECTED_REFUTATION_WRAPPER[MergeableEvidenceAuthenticationVacuousLatestUnsafe]=MergeableEvidenceAuthentication
EXPECTED_REFUTATION_INVARIANT[MergeableEvidenceAuthenticationVacuousLatestUnsafe]=RetirementRequiresEverySafetyGuard
EXPECTED_REFUTATION_WRAPPER[MergeableEvidenceAuthenticationMainSpineUnsafe]=MergeableEvidenceAuthentication
EXPECTED_REFUTATION_INVARIANT[MergeableEvidenceAuthenticationMainSpineUnsafe]=SecondaryParentRetirementComplete
EXPECTED_REFUTATION_WRAPPER[BlockHeapLifecycleMissingBoundaryUnsafe]=BlockHeapLifecycle
EXPECTED_REFUTATION_INVARIANT[BlockHeapLifecycleMissingBoundaryUnsafe]=ResidentWithinIntervalEnvelope
EXPECTED_REFUTATION_WRAPPER[StateBoundFrontierExpansionFixedUnsafe]=MCStateBoundFrontierExpansion
EXPECTED_REFUTATION_INVARIANT[StateBoundFrontierExpansionFixedUnsafe]=CompleteBackedTraceIsAccepted
EXPECTED_REFUTATION_WRAPPER[StateBoundFrontierExpansionUnbackedUnsafe]=MCStateBoundFrontierExpansion
EXPECTED_REFUTATION_INVARIANT[StateBoundFrontierExpansionUnbackedUnsafe]=CapacityUsesOnlyAuthenticatedBacking
EXPECTED_REFUTATION_WRAPPER[StateBoundFrontierExpansionLeakUnsafe]=MCStateBoundFrontierExpansion
EXPECTED_REFUTATION_INVARIANT[StateBoundFrontierExpansionLeakUnsafe]=SpeculativeAttemptsAreEffectFree
EXPECTED_REFUTATION_WRAPPER[StateBoundFrontierExpansionReplayUnsafe]=MCStateBoundFrontierExpansion
EXPECTED_REFUTATION_INVARIANT[StateBoundFrontierExpansionReplayUnsafe]=ReplayUsesTheExpandedBound
EXPECTED_REFUTATION_WRAPPER[ExchangeFlowOneSidedUnsafe]=ExchangeFlow
EXPECTED_REFUTATION_INVARIANT[ExchangeFlowOneSidedUnsafe]=Inv_RequiresBothInputs
EXPECTED_REFUTATION_WRAPPER[VaultBackedCostLifecycleExecuteFirstUnsafe]=MCVaultBackedCostLifecycle
EXPECTED_REFUTATION_INVARIANT[VaultBackedCostLifecycleExecuteFirstUnsafe]=ExecutionRequiresCompleteReservation
EXPECTED_REFUTATION_WRAPPER[VaultBackedCostLifecyclePartialReserveUnsafe]=MCVaultBackedCostLifecycle
EXPECTED_REFUTATION_INVARIANT[VaultBackedCostLifecyclePartialReserveUnsafe]=ReservationMatchesCertificate
EXPECTED_REFUTATION_WRAPPER[VaultBackedCostLifecycleUnauthorizedUnsafe]=MCVaultBackedCostLifecycle
EXPECTED_REFUTATION_INVARIANT[VaultBackedCostLifecycleUnauthorizedUnsafe]=ReservationUsesAuthorizedPayers
EXPECTED_REFUTATION_WRAPPER[VaultBackedCostLifecycleRefundLossUnsafe]=MCVaultBackedCostLifecycle
EXPECTED_REFUTATION_INVARIANT[VaultBackedCostLifecycleRefundLossUnsafe]=CanonicalValueConserved
EXPECTED_REFUTATION_WRAPPER[VaultBackedCostLifecycleReplayOmissionUnsafe]=MCVaultBackedCostLifecycle
EXPECTED_REFUTATION_INVARIANT[VaultBackedCostLifecycleReplayOmissionUnsafe]=ReplayMatchesCommit
EXPECTED_REFUTATION_WRAPPER[VaultBackedCostLifecycleDoubleMintUnsafe]=MCVaultBackedCostLifecycle
EXPECTED_REFUTATION_INVARIANT[VaultBackedCostLifecycleDoubleMintUnsafe]=MintOccursAtMostOnce
EXPECTED_REFUTATION_WRAPPER[VaultBackedCostLifecycleIndependentCreditUnsafe]=MCVaultBackedCostLifecycle
EXPECTED_REFUTATION_INVARIANT[VaultBackedCostLifecycleIndependentCreditUnsafe]=SingleCanonicalLedger
EXPECTED_REFUTATION_WRAPPER[AtomicVaultSettlementRefinementGlobalCellUnsafe]=MCAtomicVaultSettlementRefinement
EXPECTED_REFUTATION_INVARIANT[AtomicVaultSettlementRefinementGlobalCellUnsafe]=NoPersistentReservationState
EXPECTED_REFUTATION_WRAPPER[AtomicVaultSettlementRefinementApplicationDebitOmissionUnsafe]=MCAtomicVaultSettlementRefinement
EXPECTED_REFUTATION_INVARIANT[AtomicVaultSettlementRefinementApplicationDebitOmissionUnsafe]=FinalizedAggregateIsFunded
EXPECTED_REFUTATION_WRAPPER[AtomicVaultSettlementRefinementPhysicalBurnOmissionUnsafe]=MCAtomicVaultSettlementRefinement
EXPECTED_REFUTATION_INVARIANT[AtomicVaultSettlementRefinementPhysicalBurnOmissionUnsafe]=FinalizedAggregateIsFunded
EXPECTED_REFUTATION_WRAPPER[AtomicVaultSettlementRefinementByteBurnOmissionUnsafe]=MCAtomicVaultSettlementRefinement
EXPECTED_REFUTATION_INVARIANT[AtomicVaultSettlementRefinementByteBurnOmissionUnsafe]=FinalizedAggregateIsFunded
EXPECTED_REFUTATION_WRAPPER[AtomicVaultSettlementRefinementFeeOmissionUnsafe]=MCAtomicVaultSettlementRefinement
EXPECTED_REFUTATION_INVARIANT[AtomicVaultSettlementRefinementFeeOmissionUnsafe]=FinalizedAggregateIsFunded
EXPECTED_REFUTATION_WRAPPER[FeeObligationBoundaryMultipliedUnsafe]=FeeObligationBoundary
EXPECTED_REFUTATION_WRAPPER[FeeCursorTransportNilUnsafe]=FeeCursorTransport
EXPECTED_REFUTATION_INVARIANT[FeeCursorTransportNilUnsafe]=ValidInputCanReachVault
EXPECTED_REFUTATION_WRAPPER[FeeCursorBranchMergeEmptyUnsafe]=FeeCursorBranchMerge
EXPECTED_REFUTATION_INVARIANT[FeeCursorBranchMergeEmptyUnsafe]=CursorCellUnique
EXPECTED_REFUTATION_WRAPPER[FeeCursorBranchMergeMoneyUnsafe]=FeeCursorBranchMerge
EXPECTED_REFUTATION_INVARIANT[FeeCursorBranchMergeMoneyUnsafe]=WholeEffectAccounting
EXPECTED_REFUTATION_WRAPPER[FeeCursorBranchMergeOrderUnsafe]=FeeCursorBranchMerge
EXPECTED_REFUTATION_INVARIANT[FeeCursorBranchMergeOrderUnsafe]=ValidatorAgreement
EXPECTED_REFUTATION_INVARIANT[FeeObligationBoundaryMultipliedUnsafe]=FeeMatchesIndependentObligation
EXPECTED_REFUTATION_WRAPPER[InitialFundingDiscoveryOmittedUnsafe]=InitialFundingDiscovery
EXPECTED_REFUTATION_INVARIANT[InitialFundingDiscoveryOmittedUnsafe]=SelectedLeavesArePresent
EXPECTED_REFUTATION_WRAPPER[InitialFundingDiscoveryAbsentUnsafe]=InitialFundingDiscovery
EXPECTED_REFUTATION_INVARIANT[InitialFundingDiscoveryAbsentUnsafe]=AbsentLeavesAreExcluded
EXPECTED_REFUTATION_WRAPPER[InitialFundingDiscoveryAliasUnsafe]=InitialFundingDiscovery
EXPECTED_REFUTATION_INVARIANT[InitialFundingDiscoveryAliasUnsafe]=CapacityUsesDistinctPrestateCustody
EXPECTED_REFUTATION_WRAPPER[RotatingFeeSettlementStaleUnsafe]=RotatingFeeSettlement
EXPECTED_REFUTATION_WRAPPER[JointFundingSettlementStaleUnsafe]=JointFundingSettlement
EXPECTED_REFUTATION_INVARIANT[JointFundingSettlementStaleUnsafe]=EveryReceiptUsesCurrentPlan
EXPECTED_REFUTATION_WRAPPER[JointFundingSettlementResourceCursorUnsafe]=JointFundingSettlement
EXPECTED_REFUTATION_INVARIANT[JointFundingSettlementResourceCursorUnsafe]=EveryReceiptUsesCurrentPlan
EXPECTED_REFUTATION_WRAPPER[JointFundingSettlementFeeCursorUnsafe]=JointFundingSettlement
EXPECTED_REFUTATION_INVARIANT[JointFundingSettlementFeeCursorUnsafe]=EveryReceiptUsesCurrentPlan
EXPECTED_REFUTATION_WRAPPER[FamilyCursorSettlementStaleUnsafe]=FamilyCursorSettlement
EXPECTED_REFUTATION_INVARIANT[FamilyCursorSettlementStaleUnsafe]=EveryReceiptUsesCapturedCertificate
EXPECTED_REFUTATION_WRAPPER[FamilyCursorSettlementReceiptUnsafe]=FamilyCursorSettlement
EXPECTED_REFUTATION_INVARIANT[FamilyCursorSettlementReceiptUnsafe]=OnceOnlyReceipts
EXPECTED_REFUTATION_WRAPPER[FamilyCursorSettlementUnrealizedUnsafe]=FamilyCursorSettlement
EXPECTED_REFUTATION_INVARIANT[FamilyCursorSettlementUnrealizedUnsafe]=ReceiptAccounting
EXPECTED_REFUTATION_WRAPPER[FamilyCursorSettlementResourceCursorUnsafe]=FamilyCursorSettlement
EXPECTED_REFUTATION_INVARIANT[FamilyCursorSettlementResourceCursorUnsafe]=OnlyRealizedGroupPublishes
EXPECTED_REFUTATION_WRAPPER[FamilyCursorSettlementFeeCursorUnsafe]=FamilyCursorSettlement
EXPECTED_REFUTATION_INVARIANT[FamilyCursorSettlementFeeCursorUnsafe]=OnlyRealizedGroupPublishes
EXPECTED_REFUTATION_WRAPPER[FamilyCursorSettlementAbortUnsafe]=FamilyCursorSettlement
EXPECTED_REFUTATION_INVARIANT[FamilyCursorSettlementAbortUnsafe]=CursorsChangeOnlyWithSettlement
EXPECTED_REFUTATION_WRAPPER[FamilyCursorSettlementScopeSerializationUnsafe]=FamilyCursorSettlement
EXPECTED_REFUTATION_INVARIANT[FamilyCursorSettlementScopeSerializationUnsafe]=DisjointPreparationRemainsEnabled
EXPECTED_REFUTATION_WRAPPER[FamilyCursorSettlementAliasUnsafe]=FamilyCursorSettlement
EXPECTED_REFUTATION_INVARIANT[FamilyCursorSettlementAliasUnsafe]=DuplicateAliasesShareTransitions
EXPECTED_REFUTATION_WRAPPER[PinnedFundingSnapshotUnsafeCurrent]=PinnedFundingSnapshot
EXPECTED_REFUTATION_INVARIANT[PinnedFundingSnapshotUnsafeCurrent]=SnapshotAtCapturedRoot
EXPECTED_REFUTATION_WRAPPER[PinnedFundingSnapshotUnsafeABA]=PinnedFundingSnapshot
EXPECTED_REFUTATION_INVARIANT[PinnedFundingSnapshotUnsafeABA]=ABAAssembly
EXPECTED_REFUTATION_INVARIANT[RotatingFeeSettlementStaleUnsafe]=EveryReceiptUsesCurrentPlan
EXPECTED_REFUTATION_WRAPPER[RotatingFeeSettlementLostCursorUnsafe]=RotatingFeeSettlement
EXPECTED_REFUTATION_INVARIANT[RotatingFeeSettlementLostCursorUnsafe]=EveryReceiptUsesCurrentPlan
EXPECTED_REFUTATION_WRAPPER[RotatingFeeSettlementAbortCursorUnsafe]=RotatingFeeSettlement
EXPECTED_REFUTATION_INVARIANT[RotatingFeeSettlementAbortCursorUnsafe]=CursorChangesOnlyWithSettlement
EXPECTED_REFUTATION_WRAPPER[FeeCohortEligibilityUnrelatedUnsafe]=FeeCohortEligibility
EXPECTED_REFUTATION_INVARIANT[FeeCohortEligibilityUnrelatedUnsafe]=OnlyAuthenticatedAtoms
EXPECTED_REFUTATION_WRAPPER[FeeCohortEligibilityMultiplicityUnsafe]=FeeCohortEligibility
EXPECTED_REFUTATION_INVARIANT[FeeCohortEligibilityMultiplicityUnsafe]=AuthorityMultiplicityIsPreserved
EXPECTED_REFUTATION_WRAPPER[FeeCandidateSettlementRepriceUnsafe]=FeeCandidateSettlement
EXPECTED_REFUTATION_INVARIANT[FeeCandidateSettlementRepriceUnsafe]=CertifiedPrestateDeterminesFee
EXPECTED_REFUTATION_WRAPPER[FeeCandidateSettlementPostBalanceGuardUnsafe]=FeeCandidateSettlement
EXPECTED_REFUTATION_INVARIANT[FeeCandidateSettlementPostBalanceGuardUnsafe]=FundedTopUpCannotDisableCommit
EXPECTED_REFUTATION_WRAPPER[WalletFundedLollipopFundingCopyUnsafe]=MCWalletFundedLollipop
EXPECTED_REFUTATION_INVARIANT[WalletFundedLollipopFundingCopyUnsafe]=CanonicalCustodyConserved
EXPECTED_REFUTATION_WRAPPER[WalletFundedLollipopCapabilityLeakUnsafe]=MCWalletFundedLollipop
EXPECTED_REFUTATION_INVARIANT[WalletFundedLollipopCapabilityLeakUnsafe]=FundingUsesAddressesWithoutDelegatingDraw
EXPECTED_REFUTATION_WRAPPER[WalletFundedLollipopPayerCollapseUnsafe]=MCWalletFundedLollipop
EXPECTED_REFUTATION_INVARIANT[WalletFundedLollipopPayerCollapseUnsafe]=CertifiedPayersAreLocatedPurses
EXPECTED_REFUTATION_WRAPPER[WalletFundedLollipopReplayOmissionUnsafe]=MCWalletFundedLollipop
EXPECTED_REFUTATION_INVARIANT[WalletFundedLollipopReplayOmissionUnsafe]=ReplayMatchesCommit
EXPECTED_REFUTATION_WRAPPER[WalletFundedLollipopMissingOuterUnsafe]=MCWalletFundedLollipop
EXPECTED_REFUTATION_INVARIANT[WalletFundedLollipopMissingOuterUnsafe]=ContinuationRequiresOuter
EXPECTED_REFUTATION_WRAPPER[WalletFundedLollipopBoundChargeUnsafe]=MCWalletFundedLollipop
EXPECTED_REFUTATION_INVARIANT[WalletFundedLollipopBoundChargeUnsafe]=UnusedCertifiedBoundsAreRefunded
EXPECTED_REFUTATION_WRAPPER[WalletFundedLollipopGatewayAuthBypassUnsafe]=MCWalletFundedLollipop
EXPECTED_REFUTATION_INVARIANT[WalletFundedLollipopGatewayAuthBypassUnsafe]=OnlyGatewayAuthorizesContinuation
EXPECTED_REFUTATION_WRAPPER[WalletFundedLollipopActivationBeforeFundingUnsafe]=MCWalletFundedLollipop
EXPECTED_REFUTATION_INVARIANT[WalletFundedLollipopActivationBeforeFundingUnsafe]=ContinuationActivationRequiresFunding
EXPECTED_REFUTATION_WRAPPER[FundingSlotBootstrapEagerInstallUnsafe]=MCFundingSlotBootstrap
EXPECTED_REFUTATION_INVARIANT[FundingSlotBootstrapEagerInstallUnsafe]=InstallWorkflowIsAdmissible
EXPECTED_REFUTATION_WRAPPER[FundingSlotBootstrapCandidateSelfFundingUnsafe]=MCFundingSlotBootstrap
EXPECTED_REFUTATION_INVARIANT[FundingSlotBootstrapCandidateSelfFundingUnsafe]=CandidateCreatedSupplyNeverFundsItsCreator
EXPECTED_REFUTATION_WRAPPER[FundingSlotBootstrapSlotOnlyFundingUnsafe]=MCFundingSlotBootstrap
EXPECTED_REFUTATION_INVARIANT[FundingSlotBootstrapSlotOnlyFundingUnsafe]=FundingCommitCoversEveryLocatedPurse
EXPECTED_REFUTATION_WRAPPER[FundingSlotBootstrapPartialFundingUnsafe]=MCFundingSlotBootstrap
EXPECTED_REFUTATION_INVARIANT[FundingSlotBootstrapPartialFundingUnsafe]=RejectedFundingIsEffectFree
EXPECTED_REFUTATION_WRAPPER[FundingSlotBootstrapRejectedTargetCreationUnsafe]=MCFundingSlotBootstrap
EXPECTED_REFUTATION_INVARIANT[FundingSlotBootstrapRejectedTargetCreationUnsafe]=RejectedFundingIsEffectFree
EXPECTED_REFUTATION_WRAPPER[PoSVaultAuthorityLiteralControlUnsafe]=PoSVaultAuthority
EXPECTED_REFUTATION_INVARIANT[PoSVaultAuthorityLiteralControlUnsafe]=InstalledBindsAuthenticatedKey
EXPECTED_REFUTATION_WRAPPER[PoSVaultAuthorityUnresolvedTemplateUnsafe]=PoSVaultAuthority
EXPECTED_REFUTATION_INVARIANT[PoSVaultAuthorityUnresolvedTemplateUnsafe]=NoCompiledPlaceholder
EXPECTED_REFUTATION_WRAPPER[IntroductionAuthorityRegistrySplitFallbackUnsafe]=MCIntroductionAuthorityRegistry
EXPECTED_REFUTATION_INVARIANT[IntroductionAuthorityRegistrySplitFallbackUnsafe]=ResolvedMatchesCommittedRegistry
EXPECTED_REFUTATION_WRAPPER[NormalizerEnvironmentRefinementEmptyUnsafe]=NormalizerEnvironmentRefinement
EXPECTED_REFUTATION_INVARIANT[NormalizerEnvironmentRefinementEmptyUnsafe]=CertificationExecutionReplayUseSameEnvironment
EXPECTED_REFUTATION_WRAPPER[PhysicalSettlementWorklistRecursiveUnsafe]=PhysicalSettlementWorklist
EXPECTED_REFUTATION_INVARIANT[PhysicalSettlementWorklistRecursiveUnsafe]=NativeStackBound
EXPECTED_REFUTATION_WRAPPER[OslfLocatedTypingContractionUnsafe]=OslfLocatedTyping
EXPECTED_REFUTATION_INVARIANT[OslfLocatedTypingContractionUnsafe]=LinearNoContraction
EXPECTED_REFUTATION_WRAPPER[OslfLocatedTypingWeakeningUnsafe]=OslfLocatedTyping
EXPECTED_REFUTATION_INVARIANT[OslfLocatedTypingWeakeningUnsafe]=LinearNoWeakening
EXPECTED_REFUTATION_WRAPPER[OslfLocatedTypingAliasUnsafe]=OslfLocatedTyping
EXPECTED_REFUTATION_INVARIANT[OslfLocatedTypingAliasUnsafe]=LocationIsolation
EXPECTED_REFUTATION_WRAPPER[OslfLocatedTypingUpperModalUnsafe]=OslfLocatedTyping
EXPECTED_REFUTATION_INVARIANT[OslfLocatedTypingUpperModalUnsafe]=ModalEvidenceSound
EXPECTED_REFUTATION_WRAPPER[OslfLocatedTypingCandidateCreditUnsafe]=OslfLocatedTyping
EXPECTED_REFUTATION_INVARIANT[OslfLocatedTypingCandidateCreditUnsafe]=AuthenticatedFundingOnly
EXPECTED_REFUTATION_WRAPPER[ThresholdEnvelopeAuthorityUnboundSubsetUnsafe]=ThresholdEnvelopeAuthority
EXPECTED_REFUTATION_INVARIANT[ThresholdEnvelopeAuthorityUnboundSubsetUnsafe]=DeployIdentityBindsStateTransition
EXPECTED_REFUTATION_WRAPPER[ThresholdEnvelopeAuthorityPolicyAuthorityUnsafe]=ThresholdEnvelopeAuthority
EXPECTED_REFUTATION_INVARIANT[ThresholdEnvelopeAuthorityPolicyAuthorityUnsafe]=UnsignedMembersHaveNoAuthority
EXPECTED_REFUTATION_WRAPPER[ThresholdEnvelopeAuthorityMemberZeroUnsafe]=ThresholdEnvelopeAuthority
EXPECTED_REFUTATION_INVARIANT[ThresholdEnvelopeAuthorityMemberZeroUnsafe]=UnsignedMembersHaveNoAuthority
EXPECTED_REFUTATION_WRAPPER[ThresholdEnvelopeAuthorityPolicyDebitUnsafe]=ThresholdEnvelopeAuthority
EXPECTED_REFUTATION_INVARIANT[ThresholdEnvelopeAuthorityPolicyDebitUnsafe]=UnsignedMembersAreNeverDebited
EXPECTED_REFUTATION_WRAPPER[ThresholdEnvelopeAuthorityWitnessUnsafe]=ThresholdEnvelopeAuthority
EXPECTED_REFUTATION_INVARIANT[ThresholdEnvelopeAuthorityWitnessUnsafe]=WitnessesSelectExactlyTheFunders
EXPECTED_REFUTATION_WRAPPER[ThresholdEnvelopeAuthorityGroundAliasUnsafe]=ThresholdEnvelopeAuthority
EXPECTED_REFUTATION_INVARIANT[ThresholdEnvelopeAuthorityGroundAliasUnsafe]=PolicyGroundOwnersAreUnique
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationAllAdmittedUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationAllAdmittedUnsafe]=ValidatedReplayUsesExactPartition
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationCountOnlyUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationCountOnlyUnsafe]=ValidatedReplayUsesExactPartition
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationPrimaryIdentityUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationPrimaryIdentityUnsafe]=DeployIdentityIsTypedAndInjective
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationLegacyWireFieldUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationLegacyWireFieldUnsafe]=StoredIdentityMatchesProtocolIdentity
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationRawEvidenceIdentityUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationRawEvidenceIdentityUnsafe]=EvidenceIdentityIsTypedAndInjective
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationRawReservationIdentityUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationRawReservationIdentityUnsafe]=ReservationIdentityIsTypedAndInjective
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationRawFeeIdentityUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationRawFeeIdentityUnsafe]=FeeIdentityIsTypedAndInjective
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationRawRngIdentityUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationRawRngIdentityUnsafe]=RngIdentityIsTypedAndInjective
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationUnconsumedEvidenceUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationUnconsumedEvidenceUnsafe]=EvidenceConsumptionIsExact
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationCallerContextUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationCallerContextUnsafe]=ValidatedReplayUsesAuthenticatedContext
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationEarlyPublishUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationEarlyPublishUnsafe]=PersistentEvidenceRequiresValidatedReplay
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationBareRowUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationBareRowUnsafe]=PersistentEvidenceRequiresValidatedReplay
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationPeerBytesUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationPeerBytesUnsafe]=PersistentEvidenceRequiresValidatedReplay
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationConflictOverwriteUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationConflictOverwriteUnsafe]=ConflictingWritesNeverOverwrite
EXPECTED_REFUTATION_WRAPPER[ReplayAdmissionPublicationCacheFirstUnsafe]=ReplayAdmissionPublication
EXPECTED_REFUTATION_INVARIANT[ReplayAdmissionPublicationCacheFirstUnsafe]=CacheFollowsDurablePublication
EXPECTED_REFUTATION_WRAPPER[MergeTagBindingEnvelopeDerivedUnsafe]=MergeTagBinding
EXPECTED_REFUTATION_INVARIANT[MergeTagBindingEnvelopeDerivedUnsafe]=Inv_UriRegistryAgreement
EXPECTED_REFUTATION_WRAPPER[CanonicalCustodyAliasingDuplicateLaneCapacityUnsafe]=MCCanonicalCustodyAliasing
EXPECTED_REFUTATION_INVARIANT[CanonicalCustodyAliasingDuplicateLaneCapacityUnsafe]=NoDoubleCapacity
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecycleFreshBondSubsidyUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecycleFreshBondSubsidyUnsafe]=InitialIssuanceOccursOnlyAtGenesis
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecycleRebondSubsidyUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecycleRebondSubsidyUnsafe]=InitialIssuanceOccursOnlyAtGenesis
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecycleInactiveValidatorIssuanceUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecycleInactiveValidatorIssuanceUnsafe]=EpochIssuanceRequiresActiveMembership
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecycleOffBoundaryIssuanceUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecycleOffBoundaryIssuanceUnsafe]=EpochIssuanceRequiresBoundary
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecycleHaltedValidatorIssuanceUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecycleHaltedValidatorIssuanceUnsafe]=HaltedValidatorsReceiveNoIssuance
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecycleDuplicateEpochIssuanceUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecycleDuplicateEpochIssuanceUnsafe]=AtMostOneCreditPerValidatorEpoch
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecycleGenerationDuringEpochUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecycleGenerationDuringEpochUnsafe]=GenerationChangesOnlyOnSuccessfulBond
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecyclePlayOnlySubsidyUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecyclePlayOnlySubsidyUnsafe]=PlayReplayIssuanceAgree
EXPECTED_REFUTATION_WRAPPER[BondIssuanceLifecycleReplayOnlySubsidyUnsafe]=MC_BondIssuanceLifecycle
EXPECTED_REFUTATION_INVARIANT[BondIssuanceLifecycleReplayOnlySubsidyUnsafe]=PlayReplayIssuanceAgree
EXPECTED_REFUTATION_WRAPPER[EpochMintAtomicitySwallowFailureUnsafe]=MC_EpochMintAtomicity
EXPECTED_REFUTATION_INVARIANT[EpochMintAtomicitySwallowFailureUnsafe]=CommitRequiresAllEligibleMints
EXPECTED_REFUTATION_WRAPPER[EpochMintAtomicityEarlyBalanceUnsafe]=MC_EpochMintAtomicity
EXPECTED_REFUTATION_INVARIANT[EpochMintAtomicityEarlyBalanceUnsafe]=NoPartialBalancePublication
EXPECTED_REFUTATION_WRAPPER[EpochMintAtomicityEarlyReceiptUnsafe]=MC_EpochMintAtomicity
EXPECTED_REFUTATION_INVARIANT[EpochMintAtomicityEarlyReceiptUnsafe]=NoPartialReceiptPublication
EXPECTED_REFUTATION_WRAPPER[EpochMintAtomicityMissingRuntimeRollbackUnsafe]=MC_EpochMintAtomicity
EXPECTED_REFUTATION_INVARIANT[EpochMintAtomicityMissingRuntimeRollbackUnsafe]=AbortRestoresCommittedState
EXPECTED_REFUTATION_WRAPPER[EpochMintAtomicityReplayPartialUnsafe]=MC_EpochMintAtomicity
EXPECTED_REFUTATION_INVARIANT[EpochMintAtomicityReplayPartialUnsafe]=PlayReplayCommittedStateEqual
EXPECTED_REFUTATION_WRAPPER[EpochMintAtomicityZeroCallsStrictMintUnsafe]=MC_EpochMintAtomicity
EXPECTED_REFUTATION_INVARIANT[EpochMintAtomicityZeroCallsStrictMintUnsafe]=ZeroIssuanceCompletesWithoutFailure
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleAddressOnlyRoleCollapseUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleAddressOnlyRoleCollapseUnsafe]=AddressAndRoleIdentifyCustody
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleBurnWithoutSupplyReductionUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleBurnWithoutSupplyReductionUnsafe]=BurnReducesCirculatingSupply
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleCapacityFromGeneralUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleCapacityFromGeneralUnsafe]=CapacityUsesValidatorFuel
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleDirectRedemptionMintUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleDirectRedemptionMintUnsafe]=RedemptionCreatesNoFuel
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleDuplicateGuiltyPenaltyUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleDuplicateGuiltyPenaltyUnsafe]=GuiltyResolutionIsIdempotent
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleEpochToGeneralUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleEpochToGeneralUnsafe]=EpochCreditsValidatorFuel
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleFeeToFuelUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleFeeToFuelUnsafe]=FeeCreditsGeneralCustody
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleFreshBondSubsidyUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleFreshBondSubsidyUnsafe]=FreshBondCreatesNoFuel
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleFuelToGeneralWithdrawalUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleFuelToGeneralWithdrawalUnsafe]=FuelHasNoWithdrawalPath
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleGlobalValidatorEconomicsLockUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleGlobalValidatorEconomicsLockUnsafe]=ValidatorOperationsRemainIndependent
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleHandlerFromGeneralUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleHandlerFromGeneralUnsafe]=HandlerUsesValidatorFuel
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecyclePartialEpochPublicationUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecyclePartialEpochPublicationUnsafe]=EpochPublicationIsAtomic
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecyclePartialSlashRedemptionUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecyclePartialSlashRedemptionUnsafe]=SlashResolutionIsAtomic
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleRebondSubsidyUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleRebondSubsidyUnsafe]=RebondCreatesNoFuel
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleReplayRoleSubstitutionUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleReplayRoleSubstitutionUnsafe]=PlayReplayRolesAgree
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleSameCandidateTopUpUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleSameCandidateTopUpUnsafe]=CandidateCannotSelfFundHandler
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleSiblingAggregateFuelOverdrawUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleSiblingAggregateFuelOverdrawUnsafe]=SiblingReservationsAreBounded
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleSlashGeneralUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleSlashGeneralUnsafe]=SlashPreservesGeneralCustody
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleSlashLeavesFuelUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleSlashLeavesFuelUnsafe]=SlashRemovesAvailableFuel
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleStaleGenerationResolutionUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleStaleGenerationResolutionUnsafe]=ResolutionUsesCurrentGeneration
EXPECTED_REFUTATION_WRAPPER[ValidatorEconomicsLifecycleTopUpWithoutGeneralDebitUnsafe]=MC_ValidatorEconomicsLifecycle
EXPECTED_REFUTATION_INVARIANT[ValidatorEconomicsLifecycleTopUpWithoutGeneralDebitUnsafe]=TopUpConservesCustody
EXPECTED_REFUTATION_WRAPPER[MintedEpochFrontierInitAtZeroUnsafe]=MintedEpochFrontier
EXPECTED_REFUTATION_INVARIANT[MintedEpochFrontierInitAtZeroUnsafe]=InitialFrontierIsUnminted
EXPECTED_REFUTATION_WRAPPER[MintedEpochFrontierRejectBootstrapUnsafe]=MintedEpochFrontier
EXPECTED_REFUTATION_INVARIANT[MintedEpochFrontierRejectBootstrapUnsafe]=RequiredBootstrapIsAccepted
EXPECTED_REFUTATION_WRAPPER[MintedEpochFrontierGapUnsafe]=MintedEpochFrontier
EXPECTED_REFUTATION_INVARIANT[MintedEpochFrontierGapUnsafe]=GapCloseIsRejected
EXPECTED_REFUTATION_WRAPPER[MintedEpochFrontierDoubleSiblingUnsafe]=MintedEpochFrontier
EXPECTED_REFUTATION_INVARIANT[MintedEpochFrontierDoubleSiblingUnsafe]=SiblingCloseKeepsExactlyOne
EXPECTED_REFUTATION_WRAPPER[MintedEpochFrontierDropSiblingUnsafe]=MintedEpochFrontier
EXPECTED_REFUTATION_INVARIANT[MintedEpochFrontierDropSiblingUnsafe]=SiblingCloseKeepsExactlyOne
EXPECTED_REFUTATION_WRAPPER[MintedEpochFrontierCatchupBondUnsafe]=MintedEpochFrontier
EXPECTED_REFUTATION_INVARIANT[MintedEpochFrontierCatchupBondUnsafe]=LifecycleDoesNotMint
EXPECTED_REFUTATION_WRAPPER[MintedEpochFrontierClearRedemptionUnsafe]=MintedEpochFrontier
EXPECTED_REFUTATION_INVARIANT[MintedEpochFrontierClearRedemptionUnsafe]=LifecyclePreservesFrontier
EXPECTED_REFUTATION_WRAPPER[MintedEpochFrontierRetroactiveMintUnsafe]=MintedEpochFrontier
EXPECTED_REFUTATION_INVARIANT[MintedEpochFrontierRetroactiveMintUnsafe]=LifecycleDoesNotMint

# Collect all .cfg files whose paired .tla module exists.
specs=()
spec_roots=()
for cfg in *.cfg; do
    [[ -e "$cfg" ]] || continue
    base="${cfg%.cfg}"
    if [[ -z "$FILTER" || "$base" == *"$FILTER"* ]]; then
        if [[ "$base" != MC* ]] && [[ -n "${WRAPPED_BY[$base]:-}" ]]; then
            wrapper="${WRAPPED_BY[$base]}"
            if [[ -f "${wrapper}.tla" ]]; then
                specs+=("$base")
                spec_roots+=("${wrapper}.tla")
            fi
        elif [[ -f "${base}.tla" ]]; then
            specs+=("$base")
            spec_roots+=("${base}.tla")
        fi
    fi
done

matching_refutations=0
for base in "${!EXPECTED_REFUTATION_WRAPPER[@]}"; do
    if [[ -z "$FILTER" || "$base" == *"$FILTER"* ]]; then
        matching_refutations=$((matching_refutations + 1))
    fi
done

matching_external=0
if [[ -z "$FILTER" || "DeterministicParallelReduction" == *"$FILTER"* ]]; then
    matching_external=$((matching_external + 1))
fi
if [[ -z "$FILTER" || "Validator" == *"$FILTER"* ]]; then
    matching_external=$((matching_external + 1))
fi

if [[ ${#specs[@]} -eq 0 && $matching_refutations -eq 0 && $matching_external -eq 0 ]]; then
    echo "No matching specs found" >&2
    exit 2
fi

echo "Running TLC against ${#specs[@]} cost_accounted_rho specs"
echo "Memory envelope: -Xmx${TLC_HEAP}, ${TLC_WORKERS} workers, on-disk metadir, MemoryMax=${TLC_RSS} (MemorySwapMax=0)"
echo

passes=0
failures=0
failed_specs=()
# Per-spec metadirs under an ON-DISK root. NOT mktemp -d, which lands in
# TMPDIR=/tmp — tmpfs (RAM) on this host, so TLC's multi-GB state graph
# would spill into RAM instead of onto the NVMe. Cleared up front (a prior
# SIGKILL'd run leaks its metadir because the EXIT trap never fires) and
# again on exit.
METADIR_ROOT="$TLC_METADIR_ROOT/cost-accounted-gate"
rm -rf "$METADIR_ROOT"
mkdir -p "$METADIR_ROOT"
trap 'rm -rf "$METADIR_ROOT"' EXIT

for i in "${!specs[@]}"; do
    base="${specs[$i]}"
    spec_root="${spec_roots[$i]}"
    printf "  %-40s " "${base} (${spec_root%.tla})"
    metadir="$METADIR_ROOT/$base"
    output=$(tlc_run "$metadir" "${base}.cfg" "$spec_root" -deadlock 2>&1 || true)
    if grep -q "Model checking completed. No error has been found" <<<"$output"; then
        echo "PASS"
        passes=$((passes + 1))
    elif grep -q "Error:" <<<"$output"; then
        echo "FAIL"
        failures=$((failures + 1))
        failed_specs+=("$base")
        echo "$output" | tail -10 | sed 's/^/    /'
    else
        echo "INCONCLUSIVE"
        failures=$((failures + 1))
        failed_specs+=("$base")
        echo "$output" | tail -5 | sed 's/^/    /'
    fi
done

expected_refutations=0
for base in "${!EXPECTED_REFUTATION_WRAPPER[@]}"; do
    if [[ -n "$FILTER" && "$base" != *"$FILTER"* ]]; then
        continue
    fi
    wrapper="${EXPECTED_REFUTATION_WRAPPER[$base]}"
    invariant="${EXPECTED_REFUTATION_INVARIANT[$base]}"
    if [[ ! -f "${base}.cfg" || ! -f "${wrapper}.tla" ]]; then
        printf "  %-40s FAIL\n" "${base} (expected refutation)"
        failures=$((failures + 1))
        failed_specs+=("$base(missing-control)")
        continue
    fi
    expected_refutations=$((expected_refutations + 1))
    printf "  %-40s " "${base} (expected refutation)"
    metadir="$METADIR_ROOT/$base"
    output=$(tlc_run "$metadir" "${base}.cfg" "${wrapper}.tla" -deadlock 2>&1 || true)
    if grep -Fq "Invariant ${invariant} is violated" <<<"$output" \
       || grep -Fq "The invariant of ${invariant} is equal to FALSE" <<<"$output"; then
        echo "PASS (refuted ${invariant})"
        passes=$((passes + 1))
    else
        echo "FAIL (expected ${invariant} counterexample)"
        failures=$((failures + 1))
        failed_specs+=("$base(expected-refutation)")
        echo "$output" | tail -10 | sed 's/^/    /'
    fi
done

# Deterministic parallel reduction lives beside the runtime-isolation models
# because it covers the interpreter/RSpace boundary rather than only economic
# state. It is still a mandatory part of this gate: cost and replay evidence
# cannot be canonical if competing COMMs commit by Tokio arrival order.
REDUCTION_TLA_DIR="$REPO_ROOT/formal/tlaplus/deterministic_parallel_reduction"
if [[ -z "$FILTER" || "DeterministicParallelReduction" == *"$FILTER"* ]]; then
    reduction_module="$REDUCTION_TLA_DIR/DeterministicParallelReduction.tla"
    reduction_safe="$REDUCTION_TLA_DIR/MC_DeterministicParallelReduction.cfg"
    printf "  %-40s " "DeterministicParallelReduction"
    reduction_output=$(tlc_run "$METADIR_ROOT/DeterministicParallelReduction" \
        "$reduction_safe" "$reduction_module" -deadlock 2>&1 || true)
    if grep -q "Model checking completed. No error has been found" <<<"$reduction_output"; then
        echo "PASS"
        passes=$((passes + 1))
    else
        echo "FAIL"
        failures=$((failures + 1))
        failed_specs+=("DeterministicParallelReduction")
        echo "$reduction_output" | tail -10 | sed 's/^/    /'
    fi

    declare -A REDUCTION_UNSAFE_INVARIANTS=(
        [arrival]="Inv_CommitRequiresCompleteFrontier"
        [order]="Inv_ConflictComponentCommitsInOrder"
        [checkpoint]="Inv_CheckpointAtQuiescence"
        [serial]="Inv_FirstCommitRetainsDisjointParallelism"
        [authority]="Inv_SharedAuthorityNeverRunsAsDisjoint"
    )
    for control in arrival order checkpoint serial authority; do
        invariant="${REDUCTION_UNSAFE_INVARIANTS[$control]}"
        config="$REDUCTION_TLA_DIR/MC_DeterministicParallelReduction_${control}_unsafe.cfg"
        printf "  %-40s " "DeterministicParallelReduction_${control} (expected refutation)"
        reduction_output=$(tlc_run "$METADIR_ROOT/DeterministicParallelReduction_${control}" \
            "$config" "$reduction_module" -deadlock 2>&1 || true)
        if grep -Fq "Invariant ${invariant} is violated" <<<"$reduction_output"; then
            echo "PASS (refuted ${invariant})"
            passes=$((passes + 1))
            expected_refutations=$((expected_refutations + 1))
        else
            echo "FAIL (expected ${invariant} counterexample)"
            failures=$((failures + 1))
            failed_specs+=("DeterministicParallelReduction_${control}(expected-refutation)")
            echo "$reduction_output" | tail -10 | sed 's/^/    /'
        fi
    done

    driver_module="$REDUCTION_TLA_DIR/ReductionDriverLifecycle.tla"
    for driver_mode in async inline; do
        if [[ "$driver_mode" == "async" ]]; then
            driver_config="$REDUCTION_TLA_DIR/MC_ReductionDriverLifecycle.cfg"
        else
            driver_config="$REDUCTION_TLA_DIR/MC_ReductionDriverLifecycle_inline.cfg"
        fi
        printf "  %-40s " "ReductionDriverLifecycle_${driver_mode}"
        driver_output=$(tlc_run "$METADIR_ROOT/ReductionDriverLifecycle_${driver_mode}" \
            "$driver_config" "$driver_module" -deadlock 2>&1 || true)
        if grep -q "Model checking completed. No error has been found" <<<"$driver_output"; then
            echo "PASS"
            passes=$((passes + 1))
        else
            echo "FAIL"
            failures=$((failures + 1))
            failed_specs+=("ReductionDriverLifecycle_${driver_mode}")
            echo "$driver_output" | tail -10 | sed 's/^/    /'
        fi
    done

    declare -A DRIVER_UNSAFE_INVARIANTS=(
        [claim]="Inv_ReadyHasDriver"
        [transfer]="Inv_PendingInlineIsTransferable"
        [reentry]="Inv_InternalExecutionNeverResubmits"
    )
    for control in claim transfer reentry; do
        invariant="${DRIVER_UNSAFE_INVARIANTS[$control]}"
        config="$REDUCTION_TLA_DIR/MC_ReductionDriverLifecycle_${control}_unsafe.cfg"
        printf "  %-40s " "ReductionDriverLifecycle_${control} (expected refutation)"
        driver_output=$(tlc_run "$METADIR_ROOT/ReductionDriverLifecycle_${control}" \
            "$config" "$driver_module" -deadlock 2>&1 || true)
        if grep -Fq "Invariant ${invariant} is violated" <<<"$driver_output"; then
            echo "PASS (refuted ${invariant})"
            passes=$((passes + 1))
            expected_refutations=$((expected_refutations + 1))
        else
            echo "FAIL (expected ${invariant} counterexample)"
            failures=$((failures + 1))
            failed_specs+=("ReductionDriverLifecycle_${control}(expected-refutation)")
            echo "$driver_output" | tail -10 | sed 's/^/    /'
        fi
    done

    singleton_module="$REDUCTION_TLA_DIR/SingleParticipantFastPath.tla"
    singleton_safe="$REDUCTION_TLA_DIR/MC_SingleParticipantFastPath.cfg"
    printf "  %-40s " "SingleParticipantFastPath"
    singleton_output=$(tlc_run "$METADIR_ROOT/SingleParticipantFastPath" \
        "$singleton_safe" "$singleton_module" -deadlock 2>&1 || true)
    if grep -q "Model checking completed. No error has been found" <<<"$singleton_output"; then
        echo "PASS"
        passes=$((passes + 1))
    else
        echo "FAIL"
        failures=$((failures + 1))
        failed_specs+=("SingleParticipantFastPath")
        echo "$singleton_output" | tail -10 | sed 's/^/    /'
    fi

    singleton_unsafe="$REDUCTION_TLA_DIR/MC_SingleParticipantFastPath_unsafe.cfg"
    printf "  %-40s " "SingleParticipantFastPath_unsafe (expected refutation)"
    singleton_output=$(tlc_run "$METADIR_ROOT/SingleParticipantFastPath_unsafe" \
        "$singleton_unsafe" "$singleton_module" -deadlock 2>&1 || true)
    if grep -Fq "Invariant Inv_DirectOwnerRequiresSingleton is violated" <<<"$singleton_output"; then
        echo "PASS (refuted Inv_DirectOwnerRequiresSingleton)"
        passes=$((passes + 1))
        expected_refutations=$((expected_refutations + 1))
    else
        echo "FAIL (expected Inv_DirectOwnerRequiresSingleton counterexample)"
        failures=$((failures + 1))
        failed_specs+=("SingleParticipantFastPath_unsafe(expected-refutation)")
        echo "$singleton_output" | tail -10 | sed 's/^/    /'
    fi

    boundary_module="$REDUCTION_TLA_DIR/EvaluationBoundary.tla"
    boundary_safe="$REDUCTION_TLA_DIR/MC_EvaluationBoundary.cfg"
    printf "  %-40s " "EvaluationBoundary"
    boundary_output=$(tlc_run "$METADIR_ROOT/EvaluationBoundary" \
        "$boundary_safe" "$boundary_module" -deadlock 2>&1 || true)
    if grep -q "Model checking completed. No error has been found" <<<"$boundary_output"; then
        echo "PASS"
        passes=$((passes + 1))
    else
        echo "FAIL"
        failures=$((failures + 1))
        failed_specs+=("EvaluationBoundary")
        echo "$boundary_output" | tail -10 | sed 's/^/    /'
    fi

    boundary_unsafe="$REDUCTION_TLA_DIR/MC_EvaluationBoundary_cancel_unsafe.cfg"
    printf "  %-40s " "EvaluationBoundary_cancel (expected refutation)"
    boundary_output=$(tlc_run "$METADIR_ROOT/EvaluationBoundary_cancel" \
        "$boundary_unsafe" "$boundary_module" -deadlock 2>&1 || true)
    if grep -Fq "Invariant Inv_CheckpointAtEvaluationQuiescence is violated" <<<"$boundary_output"; then
        echo "PASS (refuted Inv_CheckpointAtEvaluationQuiescence)"
        passes=$((passes + 1))
        expected_refutations=$((expected_refutations + 1))
    else
        echo "FAIL (expected Inv_CheckpointAtEvaluationQuiescence counterexample)"
        failures=$((failures + 1))
        failed_specs+=("EvaluationBoundary_cancel(expected-refutation)")
        echo "$boundary_output" | tail -10 | sed 's/^/    /'
    fi
fi

# ─────────────────────────────────────────────────────────────────────────
# Validator behavioral contract (Workstream E, stage E5): the arithmetic
# obligations of the built-in validator's contract, discharged DEDUCTIVELY
# by TLAPS (not bounded model-checking) in formal/tlaplus/validator/
# Validator.tla. The state-machine obligations stay TLC-checked above
# (RuntimeBudgetReplay). Local-only, like the rest of this script.
VALIDATOR_TLA_DIR="$REPO_ROOT/formal/tlaplus/validator"
if [[ -z "$FILTER" || "Validator" == *"$FILTER"* ]] \
   && [[ -f "$VALIDATOR_TLA_DIR/Validator.tla" ]]; then
    printf "  %-40s " "Validator (TLAPS contract proofs)"
    # TLAPS and its zenon backend install under ~/.local; make them findable
    # without disturbing the TLC PATH used above (scoped to this subshell).
    VALIDATOR_PATH="$HOME/.local/tlaps/bin:$HOME/.local/bin:/usr/bin:$PATH"
    if PATH="$VALIDATOR_PATH" command -v tlapm >/dev/null 2>&1; then
        # Run TLAPS from the validator dir so its .tlacache lands locally.
        tlaps_out=$( cd "$VALIDATOR_TLA_DIR" \
            && PATH="$VALIDATOR_PATH" tlapm Validator.tla 2>&1 || true )
        # tlapm prints one "All N obligations proved." per module root; the
        # imported TLAPS.tla reports "All 0 obligation proved", so success is
        # a non-zero-obligation "All N obligations proved." for Validator.tla
        # with no "failed"/"omitted" anywhere.
        if grep -Eq "All [1-9][0-9]* obligations? proved\." <<<"$tlaps_out" \
           && ! grep -Eiq "obligation.*(failed|omitted)|[1-9][0-9]* (failed|omitted)" <<<"$tlaps_out"; then
            echo "PASS"
            passes=$((passes + 1))
        else
            echo "FAIL"
            failures=$((failures + 1))
            failed_specs+=("Validator(TLAPS)")
            echo "$tlaps_out" | tail -10 | sed 's/^/    /'
        fi
    else
        echo "SKIP (tlapm not on PATH)"
    fi
fi

echo
echo "Summary: $passes passed, $failures failed ($expected_refutations expected refutations exercised)"
if [[ $failures -gt 0 ]]; then
    echo "Failed specs:"
    printf '  - %s\n' "${failed_specs[@]}"
    exit 1
fi
