// Upstream code uses patterns that trigger these clippy lints extensively.
// Suppressed at crate level to avoid hundreds of individual annotations.
// TODO: Address these incrementally in upstream f1r3node.
#![allow(clippy::type_complexity)]
#![allow(clippy::ptr_arg)]
#![allow(clippy::borrowed_box)]
#![allow(clippy::manual_memcpy)]
#![allow(clippy::unnecessary_sort_by)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::module_inception)]
#![allow(clippy::redundant_clone)]
#![allow(clippy::new_ret_no_self)]
#![allow(clippy::derived_hash_with_manual_eq)]
#![allow(clippy::redundant_closure_for_method_calls)]
#![allow(clippy::collapsible_if)]
#![allow(clippy::nonminimal_bool)]
#![allow(clippy::no_effect)]
#![allow(clippy::non_canonical_partial_ord_impl)]
#![allow(clippy::empty_line_after_doc_comments)]
#![allow(clippy::unwrap_used, clippy::needless_bool)]
#![allow(clippy::items_after_test_module)]
#![allow(clippy::collapsible_match)]
#![allow(clippy::unnecessary_to_owned)]
#![allow(clippy::needless_option_as_deref)]
#![allow(clippy::panicking_unwrap)]
#![allow(clippy::assigning_clones)]
#![allow(clippy::assertions_on_constants)]
#![allow(clippy::iter_overeager_cloned)]
#![allow(clippy::redundant_iter_cloned)]
#![allow(clippy::unnecessary_unwrap)]

pub mod rspace;
